noPoll websocket implementation , WebSocket implementation, RFC 6455 implementation, (Servidores Linux http://www.aspl.es)
nopoll_base64_decode
nopoll_base64_encode
nopoll_cleanup_library
nopoll_cmp
nopoll_get_32bit
nopoll_mutex_create
nopoll_mutex_destroy
nopoll_mutex_lock
nopoll_mutex_unlock
nopoll_ncmp
nopoll_nonce
nopoll_sleep
nopoll_strdup
nopoll_strdup_printf
nopoll_strdup_printfv
nopoll_thread_handlers
nopoll_timeval_substract
nopoll_trim
nopoll_vprintf_len
nopoll_strdup()
char* nopoll_strdup (const char * buffer)
Safe strdup () wrapper.
Parameters
buffer The string to copy
Returns
A reference to the string copied or NULL if it fails.
Referenced by nopoll_conn_opts_set_cookie(), nopoll_conn_opts_set_extra_headers(), nopoll_conn_opts_set_interface(), nopoll_conn_opts_set_ssl_certs(), nopoll_conn_set_accepted_protocol(), and nopoll_ctx_set_certificate().