#ifndef NETWORK_INTERFACE_MESSAGE_ID_E2SM_H
#define NETWORK_INTERFACE_MESSAGE_ID_E2SM_H

#include <stdint.h>

typedef enum{

  RESET_INTERFACE_PROC_ID,
  F1_SETUP_INTERFACE_PROC_ID,
  GNB_DU_CONFIGURATION_UPDATE_INTERFACE_PROC_ID,
  GNB_CU_CONFIGURATION_UPDATE_INTERFACE_PROC_ID,
  UE_CONTEXT_SETUP_INTERFACE_PROC_ID,
  UE_CONTEXT_RELEASE_GNB_CU_INITIATED_INTERFACE_PROC_ID,
  UE_CONTEXT_MODIFICATION_GNB_CU_INITIATED_INTERFACE_PROC_ID,
  UE_CONTEXT_MODIFICATION_REQUIRED_GNB_DU_INITIATED_INTERFACE_PROC_ID,
  WRITE_REPLACE_WARNING_INTERFACE_PROC_ID,
  PWS_CANCEL_INTERFACE_PROC_ID,
  GNB_DU_RESOURCE_COORDINATION_INTERFACE_PROC_ID,

  END_INTERFACE_PROC_ID

} interface_proc_id_e; 

typedef enum{

  INITIATINGMESSAGE_NETWORK_INTERFACE_MSG_ID,
  SUCCESSFULOUTCOME_NETWORK_INTERFACE_MSG_ID,
  UNSUCCESSFULOUTCOME_NETWORK_INTERFACE_MSG_ID,

  END_NETWORK_INTERFACE_MSG_ID

} network_interface_msg_id_e; 

typedef struct{

  // Interface Procedure ID
  // Mandatory
  // INTEGER
  interface_proc_id_e interface_proc_id;

  // Message Type
  // Mandatory
  network_interface_msg_id_e msg_type;

} network_interface_msg_id_t;

#endif

