#ifndef E2SM_RRC_V00_VERIFIER_H
#define E2SM_RRC_V00_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef E2SM_RRC_V00_READER_H
#include "e2sm_rrc_v00_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_EventTrigger_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_RanParameterItem_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_ActionDefinitionFormat1_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_ActionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_IndicationHeaderFormat1_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_IndicationHeader_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_IndicationMessage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_UEStats_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_ControlHeaderFormat1_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_ControlHeader_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_ControlMessageFormat1_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_ControlMessage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int E2SM_RRCStats_ControlOutcome_verify_table(flatcc_table_verifier_descriptor_t *td);

static int E2SM_RRCStats_ActionDefinitionUnion_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, E2SM_RRCStats_ActionDefinitionFormat1_verify_table); /* actionDefF1 */
    default: return flatcc_verify_ok;
    }
}

static int E2SM_RRCStats_IndicationHeaderUnion_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, E2SM_RRCStats_IndicationHeaderFormat1_verify_table); /* indHeaderF1 */
    default: return flatcc_verify_ok;
    }
}

static int E2SM_RRCStats_ControlHeaderUnion_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, E2SM_RRCStats_ControlHeaderFormat1_verify_table); /* ctrlHeaderF1 */
    default: return flatcc_verify_ok;
    }
}

static int E2SM_RRCStats_ControlMessageUnion_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, E2SM_RRCStats_ControlMessageFormat1_verify_table); /* ctrlMessageF1 */
    default: return flatcc_verify_ok;
    }
}

static int E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* triggerNature */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_EventTriggerDefinitionFormat1_identifier, &E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_table);
}

static inline int E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_EventTriggerDefinitionFormat1_type_identifier, &E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_table);
}

static inline int E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_table);
}

static inline int E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_EventTriggerDefinitionFormat1_verify_table);
}

static int E2SM_RRCStats_EventTrigger_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* trig */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_EventTrigger_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_EventTrigger_identifier, &E2SM_RRCStats_EventTrigger_verify_table);
}

static inline int E2SM_RRCStats_EventTrigger_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_EventTrigger_type_identifier, &E2SM_RRCStats_EventTrigger_verify_table);
}

static inline int E2SM_RRCStats_EventTrigger_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_EventTrigger_verify_table);
}

static inline int E2SM_RRCStats_EventTrigger_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_EventTrigger_verify_table);
}

static int E2SM_RRCStats_RanParameterItem_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* test */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* value */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_RanParameterItem_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_RanParameterItem_identifier, &E2SM_RRCStats_RanParameterItem_verify_table);
}

static inline int E2SM_RRCStats_RanParameterItem_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_RanParameterItem_type_identifier, &E2SM_RRCStats_RanParameterItem_verify_table);
}

static inline int E2SM_RRCStats_RanParameterItem_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_RanParameterItem_verify_table);
}

static inline int E2SM_RRCStats_RanParameterItem_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_RanParameterItem_verify_table);
}

static int E2SM_RRCStats_ActionDefinitionFormat1_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &E2SM_RRCStats_RanParameterItem_verify_table) /* ranParameterList */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_ActionDefinitionFormat1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ActionDefinitionFormat1_identifier, &E2SM_RRCStats_ActionDefinitionFormat1_verify_table);
}

static inline int E2SM_RRCStats_ActionDefinitionFormat1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ActionDefinitionFormat1_type_identifier, &E2SM_RRCStats_ActionDefinitionFormat1_verify_table);
}

static inline int E2SM_RRCStats_ActionDefinitionFormat1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_ActionDefinitionFormat1_verify_table);
}

static inline int E2SM_RRCStats_ActionDefinitionFormat1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_ActionDefinitionFormat1_verify_table);
}

static int E2SM_RRCStats_ActionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &E2SM_RRCStats_ActionDefinitionUnion_union_verifier) /* def */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_ActionDefinition_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ActionDefinition_identifier, &E2SM_RRCStats_ActionDefinition_verify_table);
}

static inline int E2SM_RRCStats_ActionDefinition_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ActionDefinition_type_identifier, &E2SM_RRCStats_ActionDefinition_verify_table);
}

static inline int E2SM_RRCStats_ActionDefinition_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_ActionDefinition_verify_table);
}

static inline int E2SM_RRCStats_ActionDefinition_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_ActionDefinition_verify_table);
}

static int E2SM_RRCStats_IndicationHeaderFormat1_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* param */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_IndicationHeaderFormat1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_IndicationHeaderFormat1_identifier, &E2SM_RRCStats_IndicationHeaderFormat1_verify_table);
}

static inline int E2SM_RRCStats_IndicationHeaderFormat1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_IndicationHeaderFormat1_type_identifier, &E2SM_RRCStats_IndicationHeaderFormat1_verify_table);
}

static inline int E2SM_RRCStats_IndicationHeaderFormat1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_IndicationHeaderFormat1_verify_table);
}

static inline int E2SM_RRCStats_IndicationHeaderFormat1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_IndicationHeaderFormat1_verify_table);
}

static int E2SM_RRCStats_IndicationHeader_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &E2SM_RRCStats_IndicationHeaderUnion_union_verifier) /* hdr */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_IndicationHeader_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_IndicationHeader_identifier, &E2SM_RRCStats_IndicationHeader_verify_table);
}

static inline int E2SM_RRCStats_IndicationHeader_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_IndicationHeader_type_identifier, &E2SM_RRCStats_IndicationHeader_verify_table);
}

static inline int E2SM_RRCStats_IndicationHeader_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_IndicationHeader_verify_table);
}

static inline int E2SM_RRCStats_IndicationHeader_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_IndicationHeader_verify_table);
}

static int E2SM_RRCStats_IndicationMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* tstamp */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &E2SM_RRCStats_UEStats_verify_table) /* ue_stats */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_IndicationMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_IndicationMessage_identifier, &E2SM_RRCStats_IndicationMessage_verify_table);
}

static inline int E2SM_RRCStats_IndicationMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_IndicationMessage_type_identifier, &E2SM_RRCStats_IndicationMessage_verify_table);
}

static inline int E2SM_RRCStats_IndicationMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_IndicationMessage_verify_table);
}

static inline int E2SM_RRCStats_IndicationMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_IndicationMessage_verify_table);
}

static int E2SM_RRCStats_UEStats_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* rnti */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* rbid */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 2, 0, 1, 1, INT64_C(4294967295)) /* drb_active */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* status_rrc */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 1, 1) /* setup_pdu_session */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 1, 1) /* nb_of_pdu_sessions */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 1, 1) /* ue_rrc_inactivity_timer */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_UEStats_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_UEStats_identifier, &E2SM_RRCStats_UEStats_verify_table);
}

static inline int E2SM_RRCStats_UEStats_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_UEStats_type_identifier, &E2SM_RRCStats_UEStats_verify_table);
}

static inline int E2SM_RRCStats_UEStats_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_UEStats_verify_table);
}

static inline int E2SM_RRCStats_UEStats_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_UEStats_verify_table);
}

static int E2SM_RRCStats_ControlHeaderFormat1_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* param */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_ControlHeaderFormat1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlHeaderFormat1_identifier, &E2SM_RRCStats_ControlHeaderFormat1_verify_table);
}

static inline int E2SM_RRCStats_ControlHeaderFormat1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlHeaderFormat1_type_identifier, &E2SM_RRCStats_ControlHeaderFormat1_verify_table);
}

static inline int E2SM_RRCStats_ControlHeaderFormat1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_ControlHeaderFormat1_verify_table);
}

static inline int E2SM_RRCStats_ControlHeaderFormat1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_ControlHeaderFormat1_verify_table);
}

static int E2SM_RRCStats_ControlHeader_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &E2SM_RRCStats_ControlHeaderUnion_union_verifier) /* hdr */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_ControlHeader_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlHeader_identifier, &E2SM_RRCStats_ControlHeader_verify_table);
}

static inline int E2SM_RRCStats_ControlHeader_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlHeader_type_identifier, &E2SM_RRCStats_ControlHeader_verify_table);
}

static inline int E2SM_RRCStats_ControlHeader_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_ControlHeader_verify_table);
}

static inline int E2SM_RRCStats_ControlHeader_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_ControlHeader_verify_table);
}

static int E2SM_RRCStats_ControlMessageFormat1_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* action */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_ControlMessageFormat1_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlMessageFormat1_identifier, &E2SM_RRCStats_ControlMessageFormat1_verify_table);
}

static inline int E2SM_RRCStats_ControlMessageFormat1_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlMessageFormat1_type_identifier, &E2SM_RRCStats_ControlMessageFormat1_verify_table);
}

static inline int E2SM_RRCStats_ControlMessageFormat1_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_ControlMessageFormat1_verify_table);
}

static inline int E2SM_RRCStats_ControlMessageFormat1_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_ControlMessageFormat1_verify_table);
}

static int E2SM_RRCStats_ControlMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &E2SM_RRCStats_ControlMessageUnion_union_verifier) /* msg */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_ControlMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlMessage_identifier, &E2SM_RRCStats_ControlMessage_verify_table);
}

static inline int E2SM_RRCStats_ControlMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlMessage_type_identifier, &E2SM_RRCStats_ControlMessage_verify_table);
}

static inline int E2SM_RRCStats_ControlMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_ControlMessage_verify_table);
}

static inline int E2SM_RRCStats_ControlMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_ControlMessage_verify_table);
}

static int E2SM_RRCStats_ControlOutcome_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* ans */)) return ret;
    return flatcc_verify_ok;
}

static inline int E2SM_RRCStats_ControlOutcome_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlOutcome_identifier, &E2SM_RRCStats_ControlOutcome_verify_table);
}

static inline int E2SM_RRCStats_ControlOutcome_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, E2SM_RRCStats_ControlOutcome_type_identifier, &E2SM_RRCStats_ControlOutcome_verify_table);
}

static inline int E2SM_RRCStats_ControlOutcome_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &E2SM_RRCStats_ControlOutcome_verify_table);
}

static inline int E2SM_RRCStats_ControlOutcome_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &E2SM_RRCStats_ControlOutcome_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* E2SM_RRC_V00_VERIFIER_H */
