#ifndef E2SM_RRC_V00_READER_H
#define E2SM_RRC_V00_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct E2SM_RRCStats_EventTriggerDefinitionFormat1_table *E2SM_RRCStats_EventTriggerDefinitionFormat1_table_t;
typedef struct E2SM_RRCStats_EventTriggerDefinitionFormat1_table *E2SM_RRCStats_EventTriggerDefinitionFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_EventTriggerDefinitionFormat1_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_EventTriggerDefinitionFormat1_mutable_vec_t;
typedef const struct E2SM_RRCStats_EventTrigger_table *E2SM_RRCStats_EventTrigger_table_t;
typedef struct E2SM_RRCStats_EventTrigger_table *E2SM_RRCStats_EventTrigger_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_EventTrigger_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_EventTrigger_mutable_vec_t;
typedef const struct E2SM_RRCStats_RanParameterItem_table *E2SM_RRCStats_RanParameterItem_table_t;
typedef struct E2SM_RRCStats_RanParameterItem_table *E2SM_RRCStats_RanParameterItem_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_RanParameterItem_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_RanParameterItem_mutable_vec_t;
typedef const struct E2SM_RRCStats_ActionDefinitionFormat1_table *E2SM_RRCStats_ActionDefinitionFormat1_table_t;
typedef struct E2SM_RRCStats_ActionDefinitionFormat1_table *E2SM_RRCStats_ActionDefinitionFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_ActionDefinitionFormat1_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_ActionDefinitionFormat1_mutable_vec_t;
typedef const struct E2SM_RRCStats_ActionDefinition_table *E2SM_RRCStats_ActionDefinition_table_t;
typedef struct E2SM_RRCStats_ActionDefinition_table *E2SM_RRCStats_ActionDefinition_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_ActionDefinition_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_ActionDefinition_mutable_vec_t;
typedef const struct E2SM_RRCStats_IndicationHeaderFormat1_table *E2SM_RRCStats_IndicationHeaderFormat1_table_t;
typedef struct E2SM_RRCStats_IndicationHeaderFormat1_table *E2SM_RRCStats_IndicationHeaderFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_IndicationHeaderFormat1_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_IndicationHeaderFormat1_mutable_vec_t;
typedef const struct E2SM_RRCStats_IndicationHeader_table *E2SM_RRCStats_IndicationHeader_table_t;
typedef struct E2SM_RRCStats_IndicationHeader_table *E2SM_RRCStats_IndicationHeader_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_IndicationHeader_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_IndicationHeader_mutable_vec_t;
typedef const struct E2SM_RRCStats_IndicationMessage_table *E2SM_RRCStats_IndicationMessage_table_t;
typedef struct E2SM_RRCStats_IndicationMessage_table *E2SM_RRCStats_IndicationMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_IndicationMessage_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_IndicationMessage_mutable_vec_t;
typedef const struct E2SM_RRCStats_UEStats_table *E2SM_RRCStats_UEStats_table_t;
typedef struct E2SM_RRCStats_UEStats_table *E2SM_RRCStats_UEStats_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_UEStats_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_UEStats_mutable_vec_t;
typedef const struct E2SM_RRCStats_ControlHeaderFormat1_table *E2SM_RRCStats_ControlHeaderFormat1_table_t;
typedef struct E2SM_RRCStats_ControlHeaderFormat1_table *E2SM_RRCStats_ControlHeaderFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_ControlHeaderFormat1_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_ControlHeaderFormat1_mutable_vec_t;
typedef const struct E2SM_RRCStats_ControlHeader_table *E2SM_RRCStats_ControlHeader_table_t;
typedef struct E2SM_RRCStats_ControlHeader_table *E2SM_RRCStats_ControlHeader_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_ControlHeader_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_ControlHeader_mutable_vec_t;
typedef const struct E2SM_RRCStats_ControlMessageFormat1_table *E2SM_RRCStats_ControlMessageFormat1_table_t;
typedef struct E2SM_RRCStats_ControlMessageFormat1_table *E2SM_RRCStats_ControlMessageFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_ControlMessageFormat1_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_ControlMessageFormat1_mutable_vec_t;
typedef const struct E2SM_RRCStats_ControlMessage_table *E2SM_RRCStats_ControlMessage_table_t;
typedef struct E2SM_RRCStats_ControlMessage_table *E2SM_RRCStats_ControlMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_ControlMessage_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_ControlMessage_mutable_vec_t;
typedef const struct E2SM_RRCStats_ControlOutcome_table *E2SM_RRCStats_ControlOutcome_table_t;
typedef struct E2SM_RRCStats_ControlOutcome_table *E2SM_RRCStats_ControlOutcome_mutable_table_t;
typedef const flatbuffers_uoffset_t *E2SM_RRCStats_ControlOutcome_vec_t;
typedef flatbuffers_uoffset_t *E2SM_RRCStats_ControlOutcome_mutable_vec_t;
#ifndef E2SM_RRCStats_EventTriggerDefinitionFormat1_file_identifier
#define E2SM_RRCStats_EventTriggerDefinitionFormat1_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_EventTriggerDefinitionFormat1_file_identifier */
#ifndef E2SM_RRCStats_EventTriggerDefinitionFormat1_identifier
#define E2SM_RRCStats_EventTriggerDefinitionFormat1_identifier 0
#endif
#define E2SM_RRCStats_EventTriggerDefinitionFormat1_type_hash ((flatbuffers_thash_t)0x2f1ef5ec)
#define E2SM_RRCStats_EventTriggerDefinitionFormat1_type_identifier "\xec\xf5\x1e\x2f"
#ifndef E2SM_RRCStats_EventTriggerDefinitionFormat1_file_extension
#define E2SM_RRCStats_EventTriggerDefinitionFormat1_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_EventTrigger_file_identifier
#define E2SM_RRCStats_EventTrigger_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_EventTrigger_file_identifier */
#ifndef E2SM_RRCStats_EventTrigger_identifier
#define E2SM_RRCStats_EventTrigger_identifier 0
#endif
#define E2SM_RRCStats_EventTrigger_type_hash ((flatbuffers_thash_t)0x904d3ecb)
#define E2SM_RRCStats_EventTrigger_type_identifier "\xcb\x3e\x4d\x90"
#ifndef E2SM_RRCStats_EventTrigger_file_extension
#define E2SM_RRCStats_EventTrigger_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_RanParameterItem_file_identifier
#define E2SM_RRCStats_RanParameterItem_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_RanParameterItem_file_identifier */
#ifndef E2SM_RRCStats_RanParameterItem_identifier
#define E2SM_RRCStats_RanParameterItem_identifier 0
#endif
#define E2SM_RRCStats_RanParameterItem_type_hash ((flatbuffers_thash_t)0x5806411c)
#define E2SM_RRCStats_RanParameterItem_type_identifier "\x1c\x41\x06\x58"
#ifndef E2SM_RRCStats_RanParameterItem_file_extension
#define E2SM_RRCStats_RanParameterItem_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_ActionDefinitionFormat1_file_identifier
#define E2SM_RRCStats_ActionDefinitionFormat1_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_ActionDefinitionFormat1_file_identifier */
#ifndef E2SM_RRCStats_ActionDefinitionFormat1_identifier
#define E2SM_RRCStats_ActionDefinitionFormat1_identifier 0
#endif
#define E2SM_RRCStats_ActionDefinitionFormat1_type_hash ((flatbuffers_thash_t)0xced80486)
#define E2SM_RRCStats_ActionDefinitionFormat1_type_identifier "\x86\x04\xd8\xce"
#ifndef E2SM_RRCStats_ActionDefinitionFormat1_file_extension
#define E2SM_RRCStats_ActionDefinitionFormat1_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_ActionDefinition_file_identifier
#define E2SM_RRCStats_ActionDefinition_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_ActionDefinition_file_identifier */
#ifndef E2SM_RRCStats_ActionDefinition_identifier
#define E2SM_RRCStats_ActionDefinition_identifier 0
#endif
#define E2SM_RRCStats_ActionDefinition_type_hash ((flatbuffers_thash_t)0xde848410)
#define E2SM_RRCStats_ActionDefinition_type_identifier "\x10\x84\x84\xde"
#ifndef E2SM_RRCStats_ActionDefinition_file_extension
#define E2SM_RRCStats_ActionDefinition_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_IndicationHeaderFormat1_file_identifier
#define E2SM_RRCStats_IndicationHeaderFormat1_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_IndicationHeaderFormat1_file_identifier */
#ifndef E2SM_RRCStats_IndicationHeaderFormat1_identifier
#define E2SM_RRCStats_IndicationHeaderFormat1_identifier 0
#endif
#define E2SM_RRCStats_IndicationHeaderFormat1_type_hash ((flatbuffers_thash_t)0x6db69c06)
#define E2SM_RRCStats_IndicationHeaderFormat1_type_identifier "\x06\x9c\xb6\x6d"
#ifndef E2SM_RRCStats_IndicationHeaderFormat1_file_extension
#define E2SM_RRCStats_IndicationHeaderFormat1_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_IndicationHeader_file_identifier
#define E2SM_RRCStats_IndicationHeader_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_IndicationHeader_file_identifier */
#ifndef E2SM_RRCStats_IndicationHeader_identifier
#define E2SM_RRCStats_IndicationHeader_identifier 0
#endif
#define E2SM_RRCStats_IndicationHeader_type_hash ((flatbuffers_thash_t)0x3805b290)
#define E2SM_RRCStats_IndicationHeader_type_identifier "\x90\xb2\x05\x38"
#ifndef E2SM_RRCStats_IndicationHeader_file_extension
#define E2SM_RRCStats_IndicationHeader_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_IndicationMessage_file_identifier
#define E2SM_RRCStats_IndicationMessage_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_IndicationMessage_file_identifier */
#ifndef E2SM_RRCStats_IndicationMessage_identifier
#define E2SM_RRCStats_IndicationMessage_identifier 0
#endif
#define E2SM_RRCStats_IndicationMessage_type_hash ((flatbuffers_thash_t)0x3aaf7154)
#define E2SM_RRCStats_IndicationMessage_type_identifier "\x54\x71\xaf\x3a"
#ifndef E2SM_RRCStats_IndicationMessage_file_extension
#define E2SM_RRCStats_IndicationMessage_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_UEStats_file_identifier
#define E2SM_RRCStats_UEStats_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_UEStats_file_identifier */
#ifndef E2SM_RRCStats_UEStats_identifier
#define E2SM_RRCStats_UEStats_identifier 0
#endif
#define E2SM_RRCStats_UEStats_type_hash ((flatbuffers_thash_t)0x9794be00)
#define E2SM_RRCStats_UEStats_type_identifier "\x00\xbe\x94\x97"
#ifndef E2SM_RRCStats_UEStats_file_extension
#define E2SM_RRCStats_UEStats_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_ControlHeaderFormat1_file_identifier
#define E2SM_RRCStats_ControlHeaderFormat1_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_ControlHeaderFormat1_file_identifier */
#ifndef E2SM_RRCStats_ControlHeaderFormat1_identifier
#define E2SM_RRCStats_ControlHeaderFormat1_identifier 0
#endif
#define E2SM_RRCStats_ControlHeaderFormat1_type_hash ((flatbuffers_thash_t)0x9b082089)
#define E2SM_RRCStats_ControlHeaderFormat1_type_identifier "\x89\x20\x08\x9b"
#ifndef E2SM_RRCStats_ControlHeaderFormat1_file_extension
#define E2SM_RRCStats_ControlHeaderFormat1_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_ControlHeader_file_identifier
#define E2SM_RRCStats_ControlHeader_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_ControlHeader_file_identifier */
#ifndef E2SM_RRCStats_ControlHeader_identifier
#define E2SM_RRCStats_ControlHeader_identifier 0
#endif
#define E2SM_RRCStats_ControlHeader_type_hash ((flatbuffers_thash_t)0x79f68095)
#define E2SM_RRCStats_ControlHeader_type_identifier "\x95\x80\xf6\x79"
#ifndef E2SM_RRCStats_ControlHeader_file_extension
#define E2SM_RRCStats_ControlHeader_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_ControlMessageFormat1_file_identifier
#define E2SM_RRCStats_ControlMessageFormat1_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_ControlMessageFormat1_file_identifier */
#ifndef E2SM_RRCStats_ControlMessageFormat1_identifier
#define E2SM_RRCStats_ControlMessageFormat1_identifier 0
#endif
#define E2SM_RRCStats_ControlMessageFormat1_type_hash ((flatbuffers_thash_t)0x45af38c3)
#define E2SM_RRCStats_ControlMessageFormat1_type_identifier "\xc3\x38\xaf\x45"
#ifndef E2SM_RRCStats_ControlMessageFormat1_file_extension
#define E2SM_RRCStats_ControlMessageFormat1_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_ControlMessage_file_identifier
#define E2SM_RRCStats_ControlMessage_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_ControlMessage_file_identifier */
#ifndef E2SM_RRCStats_ControlMessage_identifier
#define E2SM_RRCStats_ControlMessage_identifier 0
#endif
#define E2SM_RRCStats_ControlMessage_type_hash ((flatbuffers_thash_t)0xba94cc97)
#define E2SM_RRCStats_ControlMessage_type_identifier "\x97\xcc\x94\xba"
#ifndef E2SM_RRCStats_ControlMessage_file_extension
#define E2SM_RRCStats_ControlMessage_file_extension "bin"
#endif
#ifndef E2SM_RRCStats_ControlOutcome_file_identifier
#define E2SM_RRCStats_ControlOutcome_file_identifier 0
#endif
/* deprecated, use E2SM_RRCStats_ControlOutcome_file_identifier */
#ifndef E2SM_RRCStats_ControlOutcome_identifier
#define E2SM_RRCStats_ControlOutcome_identifier 0
#endif
#define E2SM_RRCStats_ControlOutcome_type_hash ((flatbuffers_thash_t)0x9f2974a4)
#define E2SM_RRCStats_ControlOutcome_type_identifier "\xa4\x74\x29\x9f"
#ifndef E2SM_RRCStats_ControlOutcome_file_extension
#define E2SM_RRCStats_ControlOutcome_file_extension "bin"
#endif

typedef uint8_t E2SM_RRCStats_TriggerNature_enum_t;
__flatbuffers_define_integer_type(E2SM_RRCStats_TriggerNature, E2SM_RRCStats_TriggerNature_enum_t, 8)
#define E2SM_RRCStats_TriggerNature_oneMs ((E2SM_RRCStats_TriggerNature_enum_t)UINT8_C(0))
#define E2SM_RRCStats_TriggerNature_twoMs ((E2SM_RRCStats_TriggerNature_enum_t)UINT8_C(1))
#define E2SM_RRCStats_TriggerNature_fiveMs ((E2SM_RRCStats_TriggerNature_enum_t)UINT8_C(2))

static inline const char *E2SM_RRCStats_TriggerNature_name(E2SM_RRCStats_TriggerNature_enum_t value)
{
    switch (value) {
    case E2SM_RRCStats_TriggerNature_oneMs: return "oneMs";
    case E2SM_RRCStats_TriggerNature_twoMs: return "twoMs";
    case E2SM_RRCStats_TriggerNature_fiveMs: return "fiveMs";
    default: return "";
    }
}

static inline int E2SM_RRCStats_TriggerNature_is_known_value(E2SM_RRCStats_TriggerNature_enum_t value)
{
    switch (value) {
    case E2SM_RRCStats_TriggerNature_oneMs: return 1;
    case E2SM_RRCStats_TriggerNature_twoMs: return 1;
    case E2SM_RRCStats_TriggerNature_fiveMs: return 1;
    default: return 0;
    }
}

typedef uint8_t E2SM_RRCStats_RanParameterTest_enum_t;
__flatbuffers_define_integer_type(E2SM_RRCStats_RanParameterTest, E2SM_RRCStats_RanParameterTest_enum_t, 8)
#define E2SM_RRCStats_RanParameterTest_equal ((E2SM_RRCStats_RanParameterTest_enum_t)UINT8_C(0))
#define E2SM_RRCStats_RanParameterTest_greaterThan ((E2SM_RRCStats_RanParameterTest_enum_t)UINT8_C(1))
#define E2SM_RRCStats_RanParameterTest_lessThan ((E2SM_RRCStats_RanParameterTest_enum_t)UINT8_C(2))
#define E2SM_RRCStats_RanParameterTest_contains ((E2SM_RRCStats_RanParameterTest_enum_t)UINT8_C(3))
#define E2SM_RRCStats_RanParameterTest_present ((E2SM_RRCStats_RanParameterTest_enum_t)UINT8_C(4))

static inline const char *E2SM_RRCStats_RanParameterTest_name(E2SM_RRCStats_RanParameterTest_enum_t value)
{
    switch (value) {
    case E2SM_RRCStats_RanParameterTest_equal: return "equal";
    case E2SM_RRCStats_RanParameterTest_greaterThan: return "greaterThan";
    case E2SM_RRCStats_RanParameterTest_lessThan: return "lessThan";
    case E2SM_RRCStats_RanParameterTest_contains: return "contains";
    case E2SM_RRCStats_RanParameterTest_present: return "present";
    default: return "";
    }
}

static inline int E2SM_RRCStats_RanParameterTest_is_known_value(E2SM_RRCStats_RanParameterTest_enum_t value)
{
    switch (value) {
    case E2SM_RRCStats_RanParameterTest_equal: return 1;
    case E2SM_RRCStats_RanParameterTest_greaterThan: return 1;
    case E2SM_RRCStats_RanParameterTest_lessThan: return 1;
    case E2SM_RRCStats_RanParameterTest_contains: return 1;
    case E2SM_RRCStats_RanParameterTest_present: return 1;
    default: return 0;
    }
}

typedef uint8_t E2SM_RRCStats_ControlOutcomeResponse_enum_t;
__flatbuffers_define_integer_type(E2SM_RRCStats_ControlOutcomeResponse, E2SM_RRCStats_ControlOutcomeResponse_enum_t, 8)
#define E2SM_RRCStats_ControlOutcomeResponse_RRC_CTRL_OUT_OK ((E2SM_RRCStats_ControlOutcomeResponse_enum_t)UINT8_C(0))
#define E2SM_RRCStats_ControlOutcomeResponse_RRC_CTRL_OUT_END ((E2SM_RRCStats_ControlOutcomeResponse_enum_t)UINT8_C(1))

static inline const char *E2SM_RRCStats_ControlOutcomeResponse_name(E2SM_RRCStats_ControlOutcomeResponse_enum_t value)
{
    switch (value) {
    case E2SM_RRCStats_ControlOutcomeResponse_RRC_CTRL_OUT_OK: return "RRC_CTRL_OUT_OK";
    case E2SM_RRCStats_ControlOutcomeResponse_RRC_CTRL_OUT_END: return "RRC_CTRL_OUT_END";
    default: return "";
    }
}

static inline int E2SM_RRCStats_ControlOutcomeResponse_is_known_value(E2SM_RRCStats_ControlOutcomeResponse_enum_t value)
{
    switch (value) {
    case E2SM_RRCStats_ControlOutcomeResponse_RRC_CTRL_OUT_OK: return 1;
    case E2SM_RRCStats_ControlOutcomeResponse_RRC_CTRL_OUT_END: return 1;
    default: return 0;
    }
}



struct E2SM_RRCStats_EventTriggerDefinitionFormat1_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_EventTriggerDefinitionFormat1_vec_len(E2SM_RRCStats_EventTriggerDefinitionFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_EventTriggerDefinitionFormat1_table_t E2SM_RRCStats_EventTriggerDefinitionFormat1_vec_at(E2SM_RRCStats_EventTriggerDefinitionFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_EventTriggerDefinitionFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_EventTriggerDefinitionFormat1)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_EventTriggerDefinitionFormat1, triggerNature, E2SM_RRCStats_TriggerNature, E2SM_RRCStats_TriggerNature_enum_t, UINT8_C(0))

struct E2SM_RRCStats_EventTrigger_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_EventTrigger_vec_len(E2SM_RRCStats_EventTrigger_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_EventTrigger_table_t E2SM_RRCStats_EventTrigger_vec_at(E2SM_RRCStats_EventTrigger_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_EventTrigger_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_EventTrigger)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_EventTrigger, trig, E2SM_RRCStats_TriggerNature, E2SM_RRCStats_TriggerNature_enum_t, UINT8_C(0))

struct E2SM_RRCStats_RanParameterItem_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_RanParameterItem_vec_len(E2SM_RRCStats_RanParameterItem_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_RanParameterItem_table_t E2SM_RRCStats_RanParameterItem_vec_at(E2SM_RRCStats_RanParameterItem_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_RanParameterItem_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_RanParameterItem)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_RanParameterItem, id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_string_field(1, E2SM_RRCStats_RanParameterItem, name, 0)
__flatbuffers_define_scalar_field(2, E2SM_RRCStats_RanParameterItem, test, E2SM_RRCStats_RanParameterTest, E2SM_RRCStats_RanParameterTest_enum_t, UINT8_C(0))
__flatbuffers_define_string_field(3, E2SM_RRCStats_RanParameterItem, value, 0)

struct E2SM_RRCStats_ActionDefinitionFormat1_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_ActionDefinitionFormat1_vec_len(E2SM_RRCStats_ActionDefinitionFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_ActionDefinitionFormat1_table_t E2SM_RRCStats_ActionDefinitionFormat1_vec_at(E2SM_RRCStats_ActionDefinitionFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_ActionDefinitionFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_ActionDefinitionFormat1)

__flatbuffers_define_vector_field(0, E2SM_RRCStats_ActionDefinitionFormat1, ranParameterList, E2SM_RRCStats_RanParameterItem_vec_t, 0)
typedef uint8_t E2SM_RRCStats_ActionDefinitionUnion_union_type_t;
__flatbuffers_define_integer_type(E2SM_RRCStats_ActionDefinitionUnion, E2SM_RRCStats_ActionDefinitionUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, E2SM_RRCStats_ActionDefinitionUnion)
#define E2SM_RRCStats_ActionDefinitionUnion_NONE ((E2SM_RRCStats_ActionDefinitionUnion_union_type_t)UINT8_C(0))
#define E2SM_RRCStats_ActionDefinitionUnion_actionDefF1 ((E2SM_RRCStats_ActionDefinitionUnion_union_type_t)UINT8_C(1))

static inline const char *E2SM_RRCStats_ActionDefinitionUnion_type_name(E2SM_RRCStats_ActionDefinitionUnion_union_type_t type)
{
    switch (type) {
    case E2SM_RRCStats_ActionDefinitionUnion_NONE: return "NONE";
    case E2SM_RRCStats_ActionDefinitionUnion_actionDefF1: return "actionDefF1";
    default: return "";
    }
}

static inline int E2SM_RRCStats_ActionDefinitionUnion_is_known_type(E2SM_RRCStats_ActionDefinitionUnion_union_type_t type)
{
    switch (type) {
    case E2SM_RRCStats_ActionDefinitionUnion_NONE: return 1;
    case E2SM_RRCStats_ActionDefinitionUnion_actionDefF1: return 1;
    default: return 0;
    }
}


struct E2SM_RRCStats_ActionDefinition_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_ActionDefinition_vec_len(E2SM_RRCStats_ActionDefinition_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_ActionDefinition_table_t E2SM_RRCStats_ActionDefinition_vec_at(E2SM_RRCStats_ActionDefinition_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_ActionDefinition_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_ActionDefinition)

__flatbuffers_define_union_field(flatbuffers_, 1, E2SM_RRCStats_ActionDefinition, def, E2SM_RRCStats_ActionDefinitionUnion, 0)

struct E2SM_RRCStats_IndicationHeaderFormat1_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_IndicationHeaderFormat1_vec_len(E2SM_RRCStats_IndicationHeaderFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_IndicationHeaderFormat1_table_t E2SM_RRCStats_IndicationHeaderFormat1_vec_at(E2SM_RRCStats_IndicationHeaderFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_IndicationHeaderFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_IndicationHeaderFormat1)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_IndicationHeaderFormat1, param, flatbuffers_int32, int32_t, INT32_C(0))
typedef uint8_t E2SM_RRCStats_IndicationHeaderUnion_union_type_t;
__flatbuffers_define_integer_type(E2SM_RRCStats_IndicationHeaderUnion, E2SM_RRCStats_IndicationHeaderUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, E2SM_RRCStats_IndicationHeaderUnion)
#define E2SM_RRCStats_IndicationHeaderUnion_NONE ((E2SM_RRCStats_IndicationHeaderUnion_union_type_t)UINT8_C(0))
#define E2SM_RRCStats_IndicationHeaderUnion_indHeaderF1 ((E2SM_RRCStats_IndicationHeaderUnion_union_type_t)UINT8_C(1))

static inline const char *E2SM_RRCStats_IndicationHeaderUnion_type_name(E2SM_RRCStats_IndicationHeaderUnion_union_type_t type)
{
    switch (type) {
    case E2SM_RRCStats_IndicationHeaderUnion_NONE: return "NONE";
    case E2SM_RRCStats_IndicationHeaderUnion_indHeaderF1: return "indHeaderF1";
    default: return "";
    }
}

static inline int E2SM_RRCStats_IndicationHeaderUnion_is_known_type(E2SM_RRCStats_IndicationHeaderUnion_union_type_t type)
{
    switch (type) {
    case E2SM_RRCStats_IndicationHeaderUnion_NONE: return 1;
    case E2SM_RRCStats_IndicationHeaderUnion_indHeaderF1: return 1;
    default: return 0;
    }
}


struct E2SM_RRCStats_IndicationHeader_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_IndicationHeader_vec_len(E2SM_RRCStats_IndicationHeader_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_IndicationHeader_table_t E2SM_RRCStats_IndicationHeader_vec_at(E2SM_RRCStats_IndicationHeader_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_IndicationHeader_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_IndicationHeader)

__flatbuffers_define_union_field(flatbuffers_, 1, E2SM_RRCStats_IndicationHeader, hdr, E2SM_RRCStats_IndicationHeaderUnion, 0)

struct E2SM_RRCStats_IndicationMessage_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_IndicationMessage_vec_len(E2SM_RRCStats_IndicationMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_IndicationMessage_table_t E2SM_RRCStats_IndicationMessage_vec_at(E2SM_RRCStats_IndicationMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_IndicationMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_IndicationMessage)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_IndicationMessage, tstamp, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_vector_field(1, E2SM_RRCStats_IndicationMessage, ue_stats, E2SM_RRCStats_UEStats_vec_t, 0)

struct E2SM_RRCStats_UEStats_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_UEStats_vec_len(E2SM_RRCStats_UEStats_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_UEStats_table_t E2SM_RRCStats_UEStats_vec_at(E2SM_RRCStats_UEStats_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_UEStats_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_UEStats)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_UEStats, rnti, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(1, E2SM_RRCStats_UEStats, rbid, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_vector_field(2, E2SM_RRCStats_UEStats, drb_active, flatbuffers_int8_vec_t, 0)
__flatbuffers_define_scalar_field(3, E2SM_RRCStats_UEStats, status_rrc, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(4, E2SM_RRCStats_UEStats, setup_pdu_session, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(5, E2SM_RRCStats_UEStats, nb_of_pdu_sessions, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(6, E2SM_RRCStats_UEStats, ue_rrc_inactivity_timer, flatbuffers_int8, int8_t, INT8_C(0))

struct E2SM_RRCStats_ControlHeaderFormat1_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_ControlHeaderFormat1_vec_len(E2SM_RRCStats_ControlHeaderFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_ControlHeaderFormat1_table_t E2SM_RRCStats_ControlHeaderFormat1_vec_at(E2SM_RRCStats_ControlHeaderFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_ControlHeaderFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_ControlHeaderFormat1)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_ControlHeaderFormat1, param, flatbuffers_int32, int32_t, INT32_C(0))
typedef uint8_t E2SM_RRCStats_ControlHeaderUnion_union_type_t;
__flatbuffers_define_integer_type(E2SM_RRCStats_ControlHeaderUnion, E2SM_RRCStats_ControlHeaderUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, E2SM_RRCStats_ControlHeaderUnion)
#define E2SM_RRCStats_ControlHeaderUnion_NONE ((E2SM_RRCStats_ControlHeaderUnion_union_type_t)UINT8_C(0))
#define E2SM_RRCStats_ControlHeaderUnion_ctrlHeaderF1 ((E2SM_RRCStats_ControlHeaderUnion_union_type_t)UINT8_C(1))

static inline const char *E2SM_RRCStats_ControlHeaderUnion_type_name(E2SM_RRCStats_ControlHeaderUnion_union_type_t type)
{
    switch (type) {
    case E2SM_RRCStats_ControlHeaderUnion_NONE: return "NONE";
    case E2SM_RRCStats_ControlHeaderUnion_ctrlHeaderF1: return "ctrlHeaderF1";
    default: return "";
    }
}

static inline int E2SM_RRCStats_ControlHeaderUnion_is_known_type(E2SM_RRCStats_ControlHeaderUnion_union_type_t type)
{
    switch (type) {
    case E2SM_RRCStats_ControlHeaderUnion_NONE: return 1;
    case E2SM_RRCStats_ControlHeaderUnion_ctrlHeaderF1: return 1;
    default: return 0;
    }
}


struct E2SM_RRCStats_ControlHeader_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_ControlHeader_vec_len(E2SM_RRCStats_ControlHeader_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_ControlHeader_table_t E2SM_RRCStats_ControlHeader_vec_at(E2SM_RRCStats_ControlHeader_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_ControlHeader_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_ControlHeader)

__flatbuffers_define_union_field(flatbuffers_, 1, E2SM_RRCStats_ControlHeader, hdr, E2SM_RRCStats_ControlHeaderUnion, 0)

struct E2SM_RRCStats_ControlMessageFormat1_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_ControlMessageFormat1_vec_len(E2SM_RRCStats_ControlMessageFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_ControlMessageFormat1_table_t E2SM_RRCStats_ControlMessageFormat1_vec_at(E2SM_RRCStats_ControlMessageFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_ControlMessageFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_ControlMessageFormat1)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_ControlMessageFormat1, action, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t E2SM_RRCStats_ControlMessageUnion_union_type_t;
__flatbuffers_define_integer_type(E2SM_RRCStats_ControlMessageUnion, E2SM_RRCStats_ControlMessageUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, E2SM_RRCStats_ControlMessageUnion)
#define E2SM_RRCStats_ControlMessageUnion_NONE ((E2SM_RRCStats_ControlMessageUnion_union_type_t)UINT8_C(0))
#define E2SM_RRCStats_ControlMessageUnion_ctrlMessageF1 ((E2SM_RRCStats_ControlMessageUnion_union_type_t)UINT8_C(1))

static inline const char *E2SM_RRCStats_ControlMessageUnion_type_name(E2SM_RRCStats_ControlMessageUnion_union_type_t type)
{
    switch (type) {
    case E2SM_RRCStats_ControlMessageUnion_NONE: return "NONE";
    case E2SM_RRCStats_ControlMessageUnion_ctrlMessageF1: return "ctrlMessageF1";
    default: return "";
    }
}

static inline int E2SM_RRCStats_ControlMessageUnion_is_known_type(E2SM_RRCStats_ControlMessageUnion_union_type_t type)
{
    switch (type) {
    case E2SM_RRCStats_ControlMessageUnion_NONE: return 1;
    case E2SM_RRCStats_ControlMessageUnion_ctrlMessageF1: return 1;
    default: return 0;
    }
}


struct E2SM_RRCStats_ControlMessage_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_ControlMessage_vec_len(E2SM_RRCStats_ControlMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_ControlMessage_table_t E2SM_RRCStats_ControlMessage_vec_at(E2SM_RRCStats_ControlMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_ControlMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_ControlMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, E2SM_RRCStats_ControlMessage, msg, E2SM_RRCStats_ControlMessageUnion, 0)

struct E2SM_RRCStats_ControlOutcome_table { uint8_t unused__; };

static inline size_t E2SM_RRCStats_ControlOutcome_vec_len(E2SM_RRCStats_ControlOutcome_vec_t vec)
__flatbuffers_vec_len(vec)
static inline E2SM_RRCStats_ControlOutcome_table_t E2SM_RRCStats_ControlOutcome_vec_at(E2SM_RRCStats_ControlOutcome_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(E2SM_RRCStats_ControlOutcome_table_t, vec, i, 0)
__flatbuffers_table_as_root(E2SM_RRCStats_ControlOutcome)

__flatbuffers_define_scalar_field(0, E2SM_RRCStats_ControlOutcome, ans, E2SM_RRCStats_ControlOutcomeResponse, E2SM_RRCStats_ControlOutcomeResponse_enum_t, UINT8_C(0))


#include "flatcc/flatcc_epilogue.h"
#endif /* E2SM_RRC_V00_READER_H */
