/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_PrintUnformatted<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <string.h>

#include "ric_function_definition_json.h"
#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif



list_of_supported_control_style_element_t * cJSON_Parselist_of_supported_control_style_element(const char * s) {
  list_of_supported_control_style_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_supported_control_style_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_supported_control_style_element_t * cJSON_Getlist_of_supported_control_style_elementValue(const cJSON * j) {
  list_of_supported_control_style_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_supported_control_style_element_t)))) {
      memset(x, 0, sizeof(list_of_supported_control_style_element_t));
      if (cJSON_HasObjectItem(j, "controlServiceControlOutcomeFormatType")) {
        x->control_service_control_outcome_format_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "controlServiceControlOutcomeFormatType"));
      }
      if (cJSON_HasObjectItem(j, "controlServiceHeaderFormatType")) {
        x->control_service_header_format_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "controlServiceHeaderFormatType"));
      }
      if (cJSON_HasObjectItem(j, "controlServiceMessageFormatType")) {
        x->control_service_message_format_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "controlServiceMessageFormatType"));
      }
      if (cJSON_HasObjectItem(j, "controlServiceStyleName")) {
        x->control_service_style_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "controlServiceStyleName")));
      }
      else {
        if (NULL != (x->control_service_style_name = cJSON_malloc(sizeof(char)))) {
          x->control_service_style_name[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "controlServiceStyleType")) {
        x->control_service_style_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "controlServiceStyleType"));
      }
      if (cJSON_HasObjectItem(j, "ricCallProcessIDFormatType")) {
        if (NULL != (x->ric_call_process_id_format_type = cJSON_malloc(sizeof(int64_t)))) {
          *x->ric_call_process_id_format_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ricCallProcessIDFormatType"));
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_supported_control_style_element(const list_of_supported_control_style_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddNumberToObject(j, "controlServiceControlOutcomeFormatType", x->control_service_control_outcome_format_type);
      cJSON_AddNumberToObject(j, "controlServiceHeaderFormatType", x->control_service_header_format_type);
      cJSON_AddNumberToObject(j, "controlServiceMessageFormatType", x->control_service_message_format_type);
      if (NULL != x->control_service_style_name) {
        cJSON_AddStringToObject(j, "controlServiceStyleName", x->control_service_style_name);
      }
      else {
        cJSON_AddStringToObject(j, "controlServiceStyleName", "");
      }
      cJSON_AddNumberToObject(j, "controlServiceStyleType", x->control_service_style_type);
      if (NULL != x->ric_call_process_id_format_type) {
        cJSON_AddNumberToObject(j, "ricCallProcessIDFormatType", *x->ric_call_process_id_format_type);
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_supported_control_style_element(const list_of_supported_control_style_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_supported_control_style_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_supported_control_style_element(list_of_supported_control_style_element_t * x) {
  if (NULL != x) {
    if (NULL != x->control_service_style_name) {
      cJSON_free(x->control_service_style_name);
    }
    if (NULL != x->ric_call_process_id_format_type) {
      cJSON_free(x->ric_call_process_id_format_type);
    }
    cJSON_free(x);
  }
}

control_service_json_t * cJSON_Parsecontrol_service(const char * s) {
  control_service_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getcontrol_serviceValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

control_service_json_t * cJSON_Getcontrol_serviceValue(const cJSON * j) {
  control_service_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(control_service_json_t)))) {
      memset(x, 0, sizeof(control_service_json_t));
      if (cJSON_HasObjectItem(j, "listOfSupportedControlStyles")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfSupportedControlStyles");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_supported_control_style_elementValue(e1), sizeof(list_of_supported_control_style_element_t *));
          }
          x->list_of_supported_control_styles = x1;
        }
      }
      else {
        x->list_of_supported_control_styles = list_create(false, NULL);
      }
    }
  }
  return x;
}

cJSON * cJSON_Createcontrol_service(const control_service_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_supported_control_styles) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfSupportedControlStyles");
        if (NULL != j1) {
          list_of_supported_control_style_element_t * x1 = list_get_head(x->list_of_supported_control_styles);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_supported_control_style_element(x1));
            x1 = list_get_next(x->list_of_supported_control_styles);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printcontrol_service(const control_service_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createcontrol_service(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletecontrol_service(control_service_json_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_supported_control_styles) {
      list_of_supported_control_style_element_t * x1 = list_get_head(x->list_of_supported_control_styles);
      while (NULL != x1) {
        cJSON_Deletelist_of_supported_control_style_element(x1);
        x1 = list_get_next(x->list_of_supported_control_styles);
      }
      list_release(x->list_of_supported_control_styles);
    }
    cJSON_free(x);
  }
}

list_of_supported_event_trigger_style_element_t * cJSON_Parselist_of_supported_event_trigger_style_element(const char * s) {
  list_of_supported_event_trigger_style_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_supported_event_trigger_style_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_supported_event_trigger_style_element_t * cJSON_Getlist_of_supported_event_trigger_style_elementValue(const cJSON * j) {
  list_of_supported_event_trigger_style_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_supported_event_trigger_style_element_t)))) {
      memset(x, 0, sizeof(list_of_supported_event_trigger_style_element_t));
      if (cJSON_HasObjectItem(j, "eventTriggerFormatType")) {
        x->event_trigger_format_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "eventTriggerFormatType"));
      }
      if (cJSON_HasObjectItem(j, "eventTriggerStyleName")) {
        x->event_trigger_style_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "eventTriggerStyleName")));
      }
      else {
        if (NULL != (x->event_trigger_style_name = cJSON_malloc(sizeof(char)))) {
          x->event_trigger_style_name[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "eventTriggerStyleType")) {
        x->event_trigger_style_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "eventTriggerStyleType"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_supported_event_trigger_style_element(const list_of_supported_event_trigger_style_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddNumberToObject(j, "eventTriggerFormatType", x->event_trigger_format_type);
      if (NULL != x->event_trigger_style_name) {
        cJSON_AddStringToObject(j, "eventTriggerStyleName", x->event_trigger_style_name);
      }
      else {
        cJSON_AddStringToObject(j, "eventTriggerStyleName", "");
      }
      cJSON_AddNumberToObject(j, "eventTriggerStyleType", x->event_trigger_style_type);
    }
  }
  return j;
}

char * cJSON_Printlist_of_supported_event_trigger_style_element(const list_of_supported_event_trigger_style_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_supported_event_trigger_style_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_supported_event_trigger_style_element(list_of_supported_event_trigger_style_element_t * x) {
  if (NULL != x) {
    if (NULL != x->event_trigger_style_name) {
      cJSON_free(x->event_trigger_style_name);
    }
    cJSON_free(x);
  }
}

event_trigger_json_t * cJSON_Parseevent_trigger(const char * s) {
  event_trigger_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getevent_triggerValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

event_trigger_json_t * cJSON_Getevent_triggerValue(const cJSON * j) {
  event_trigger_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(event_trigger_json_t)))) {
      memset(x, 0, sizeof(event_trigger_json_t));
      if (cJSON_HasObjectItem(j, "listOfSupportedEventTriggerStyles")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfSupportedEventTriggerStyles");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_supported_event_trigger_style_elementValue(e1), sizeof(list_of_supported_event_trigger_style_element_t *));
          }
          x->list_of_supported_event_trigger_styles = x1;
        }
      }
      else {
        x->list_of_supported_event_trigger_styles = list_create(false, NULL);
      }
    }
  }
  return x;
}

cJSON * cJSON_Createevent_trigger(const event_trigger_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_supported_event_trigger_styles) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfSupportedEventTriggerStyles");
        if (NULL != j1) {
          list_of_supported_event_trigger_style_element_t * x1 = list_get_head(x->list_of_supported_event_trigger_styles);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_supported_event_trigger_style_element(x1));
            x1 = list_get_next(x->list_of_supported_event_trigger_styles);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printevent_trigger(const event_trigger_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createevent_trigger(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteevent_trigger(event_trigger_json_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_supported_event_trigger_styles) {
      list_of_supported_event_trigger_style_element_t * x1 = list_get_head(x->list_of_supported_event_trigger_styles);
      while (NULL != x1) {
        cJSON_Deletelist_of_supported_event_trigger_style_element(x1);
        x1 = list_get_next(x->list_of_supported_event_trigger_styles);
      }
      list_release(x->list_of_supported_event_trigger_styles);
    }
    cJSON_free(x);
  }
}

list_of_supported_event_trigger_styles_for_report_style_element_t * cJSON_Parselist_of_supported_event_trigger_styles_for_report_style_element(const char * s) {
  list_of_supported_event_trigger_styles_for_report_style_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_supported_event_trigger_styles_for_report_style_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_supported_event_trigger_styles_for_report_style_element_t * cJSON_Getlist_of_supported_event_trigger_styles_for_report_style_elementValue(const cJSON * j) {
  list_of_supported_event_trigger_styles_for_report_style_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_supported_event_trigger_styles_for_report_style_element_t)))) {
      memset(x, 0, sizeof(list_of_supported_event_trigger_styles_for_report_style_element_t));
      if (cJSON_HasObjectItem(j, "eventTriggerStyleType")) {
        x->event_trigger_style_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "eventTriggerStyleType"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_supported_event_trigger_styles_for_report_style_element(const list_of_supported_event_trigger_styles_for_report_style_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddNumberToObject(j, "eventTriggerStyleType", x->event_trigger_style_type);
    }
  }
  return j;
}

char * cJSON_Printlist_of_supported_event_trigger_styles_for_report_style_element(const list_of_supported_event_trigger_styles_for_report_style_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_supported_event_trigger_styles_for_report_style_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_supported_event_trigger_styles_for_report_style_element(list_of_supported_event_trigger_styles_for_report_style_element_t * x) {
  if (NULL != x) {
    cJSON_free(x);
  }
}

list_of_supported_report_style_element_t * cJSON_Parselist_of_supported_report_style_element(const char * s) {
  list_of_supported_report_style_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_supported_report_style_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_supported_report_style_element_t * cJSON_Getlist_of_supported_report_style_elementValue(const cJSON * j) {
  list_of_supported_report_style_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_supported_report_style_element_t)))) {
      memset(x, 0, sizeof(list_of_supported_report_style_element_t));
      if (cJSON_HasObjectItem(j, "listOfSupportedEventTriggerStylesForReportStyle")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfSupportedEventTriggerStylesForReportStyle");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_supported_event_trigger_styles_for_report_style_elementValue(e1), sizeof(list_of_supported_event_trigger_styles_for_report_style_element_t *));
          }
          x->list_of_supported_event_trigger_styles_for_report_style = x1;
        }
      }
      else {
        x->list_of_supported_event_trigger_styles_for_report_style = list_create(false, NULL);
      }
      if (cJSON_HasObjectItem(j, "reportServiceActionDefinitionFormatType")) {
        x->report_service_action_definition_format_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "reportServiceActionDefinitionFormatType"));
      }
      if (cJSON_HasObjectItem(j, "reportServiceIndicationHeaderFormatType")) {
        x->report_service_indication_header_format_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "reportServiceIndicationHeaderFormatType"));
      }
      if (cJSON_HasObjectItem(j, "reportServiceIndicationMessageFormatType")) {
        x->report_service_indication_message_format_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "reportServiceIndicationMessageFormatType"));
      }
      if (cJSON_HasObjectItem(j, "reportServiceStyleName")) {
        x->report_service_style_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "reportServiceStyleName")));
      }
      else {
        if (NULL != (x->report_service_style_name = cJSON_malloc(sizeof(char)))) {
          x->report_service_style_name[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "reportServiceStyleType")) {
        x->report_service_style_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "reportServiceStyleType"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_supported_report_style_element(const list_of_supported_report_style_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_supported_event_trigger_styles_for_report_style) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfSupportedEventTriggerStylesForReportStyle");
        if (NULL != j1) {
          list_of_supported_event_trigger_styles_for_report_style_element_t * x1 = list_get_head(x->list_of_supported_event_trigger_styles_for_report_style);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_supported_event_trigger_styles_for_report_style_element(x1));
            x1 = list_get_next(x->list_of_supported_event_trigger_styles_for_report_style);
          }
        }
      }
      cJSON_AddNumberToObject(j, "reportServiceActionDefinitionFormatType", x->report_service_action_definition_format_type);
      cJSON_AddNumberToObject(j, "reportServiceIndicationHeaderFormatType", x->report_service_indication_header_format_type);
      cJSON_AddNumberToObject(j, "reportServiceIndicationMessageFormatType", x->report_service_indication_message_format_type);
      if (NULL != x->report_service_style_name) {
        cJSON_AddStringToObject(j, "reportServiceStyleName", x->report_service_style_name);
      }
      else {
        cJSON_AddStringToObject(j, "reportServiceStyleName", "");
      }
      cJSON_AddNumberToObject(j, "reportServiceStyleType", x->report_service_style_type);
    }
  }
  return j;
}

char * cJSON_Printlist_of_supported_report_style_element(const list_of_supported_report_style_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_supported_report_style_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_supported_report_style_element(list_of_supported_report_style_element_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_supported_event_trigger_styles_for_report_style) {
      list_of_supported_event_trigger_styles_for_report_style_element_t * x1 = list_get_head(x->list_of_supported_event_trigger_styles_for_report_style);
      while (NULL != x1) {
        cJSON_Deletelist_of_supported_event_trigger_styles_for_report_style_element(x1);
        x1 = list_get_next(x->list_of_supported_event_trigger_styles_for_report_style);
      }
      list_release(x->list_of_supported_event_trigger_styles_for_report_style);
    }
    if (NULL != x->report_service_style_name) {
      cJSON_free(x->report_service_style_name);
    }
    cJSON_free(x);
  }
}

report_service_json_t * cJSON_Parsereport_service(const char * s) {
  report_service_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getreport_serviceValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

report_service_json_t * cJSON_Getreport_serviceValue(const cJSON * j) {
  report_service_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(report_service_json_t)))) {
      memset(x, 0, sizeof(report_service_json_t));
      if (cJSON_HasObjectItem(j, "listOfSupportedReportStyles")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfSupportedReportStyles");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_supported_report_style_elementValue(e1), sizeof(list_of_supported_report_style_element_t *));
          }
          x->list_of_supported_report_styles = x1;
        }
      }
      else {
        x->list_of_supported_report_styles = list_create(false, NULL);
      }
    }
  }
  return x;
}

cJSON * cJSON_Createreport_service(const report_service_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_supported_report_styles) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfSupportedReportStyles");
        if (NULL != j1) {
          list_of_supported_report_style_element_t * x1 = list_get_head(x->list_of_supported_report_styles);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_supported_report_style_element(x1));
            x1 = list_get_next(x->list_of_supported_report_styles);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printreport_service(const report_service_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createreport_service(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletereport_service(report_service_json_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_supported_report_styles) {
      list_of_supported_report_style_element_t * x1 = list_get_head(x->list_of_supported_report_styles);
      while (NULL != x1) {
        cJSON_Deletelist_of_supported_report_style_element(x1);
        x1 = list_get_next(x->list_of_supported_report_styles);
      }
      list_release(x->list_of_supported_report_styles);
    }
    cJSON_free(x);
  }
}

supported_services_json_t * cJSON_Parsesupported_services(const char * s) {
  supported_services_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getsupported_servicesValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

supported_services_json_t * cJSON_Getsupported_servicesValue(const cJSON * j) {
  supported_services_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(supported_services_json_t)))) {
      memset(x, 0, sizeof(supported_services_json_t));
      if (cJSON_HasObjectItem(j, "controlService")) {
        x->control_service = cJSON_Getcontrol_serviceValue(cJSON_GetObjectItemCaseSensitive(j, "controlService"));
      }
      if (cJSON_HasObjectItem(j, "eventTrigger")) {
        x->event_trigger = cJSON_Getevent_triggerValue(cJSON_GetObjectItemCaseSensitive(j, "eventTrigger"));
      }
      if (cJSON_HasObjectItem(j, "insertService")) {
        hashtable_t * x1 = hashtable_create(64, false);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "insertService");
          cJSON_ArrayForEach(e1, j1) {
            hashtable_add(x1, e1->string, (void *)0xDEADBEEF, sizeof(void *));
          }
          x->insert_service = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "policyService")) {
        hashtable_t * x1 = hashtable_create(64, false);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "policyService");
          cJSON_ArrayForEach(e1, j1) {
            hashtable_add(x1, e1->string, (void *)0xDEADBEEF, sizeof(void *));
          }
          x->policy_service = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "reportService")) {
        x->report_service = cJSON_Getreport_serviceValue(cJSON_GetObjectItemCaseSensitive(j, "reportService"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createsupported_services(const supported_services_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->control_service) {
        cJSON_AddItemToObject(j, "controlService", cJSON_Createcontrol_service(x->control_service));
      }
      if (NULL != x->event_trigger) {
        cJSON_AddItemToObject(j, "eventTrigger", cJSON_Createevent_trigger(x->event_trigger));
      }
      if (NULL != x->insert_service) {
        cJSON * j1 = cJSON_CreateObject();
        if (NULL != j1) {
          char **keys1 = NULL;
          size_t count1 = hashtable_get_keys(x->insert_service, &keys1);
          if (NULL != keys1) {
            for (size_t index1 = 0; index1 < count1; index1++) {
//              void *x1 = hashtable_lookup(x->insert_service, keys1[index1]);
            }
            cJSON_free(keys1);
          }
          cJSON_AddItemToObject(j, "insertService", j1);
        }
      }
      if (NULL != x->policy_service) {
        cJSON * j1 = cJSON_CreateObject();
        if (NULL != j1) {
          char **keys1 = NULL;
          size_t count1 = hashtable_get_keys(x->policy_service, &keys1);
          if (NULL != keys1) {
            for (size_t index1 = 0; index1 < count1; index1++) {
//              void *x1 = hashtable_lookup(x->policy_service, keys1[index1]);
            }
            cJSON_free(keys1);
          }
          cJSON_AddItemToObject(j, "policyService", j1);
        }
      }
      if (NULL != x->report_service) {
        cJSON_AddItemToObject(j, "reportService", cJSON_Createreport_service(x->report_service));
      }
    }
  }
  return j;
}

char * cJSON_Printsupported_services(const supported_services_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createsupported_services(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletesupported_services(supported_services_json_t * x) {
  if (NULL != x) {
    if (NULL != x->control_service) {
      cJSON_Deletecontrol_service(x->control_service);
    }
    if (NULL != x->event_trigger) {
      cJSON_Deleteevent_trigger(x->event_trigger);
    }
    if (NULL != x->insert_service) {
      char **keys1 = NULL;
      size_t count1 = hashtable_get_keys(x->insert_service, &keys1);
      if (NULL != keys1) {
        for (size_t index1 = 0; index1 < count1; index1++) {
          void *x1 = hashtable_lookup(x->insert_service, keys1[index1]);
          if (NULL != x1) {
          }
        }
        cJSON_free(keys1);
      }
      hashtable_release(x->insert_service);
    }
    if (NULL != x->policy_service) {
      char **keys1 = NULL;
      size_t count1 = hashtable_get_keys(x->policy_service, &keys1);
      if (NULL != keys1) {
        for (size_t index1 = 0; index1 < count1; index1++) {
          void *x1 = hashtable_lookup(x->policy_service, keys1[index1]);
          if (NULL != x1) {
          }
        }
        cJSON_free(keys1);
      }
      hashtable_release(x->policy_service);
    }
    if (NULL != x->report_service) {
      cJSON_Deletereport_service(x->report_service);
    }
    cJSON_free(x);
  }
}

list_of_supported_attribute_element_t * cJSON_Parselist_of_supported_attribute_element(const char * s) {
  list_of_supported_attribute_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_supported_attribute_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_supported_attribute_element_t * cJSON_Getlist_of_supported_attribute_elementValue(const cJSON * j) {
  list_of_supported_attribute_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_supported_attribute_element_t)))) {
      memset(x, 0, sizeof(list_of_supported_attribute_element_t));
      if (cJSON_HasObjectItem(j, "attributeName")) {
        x->attribute_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "attributeName")));
      }
      else {
        if (NULL != (x->attribute_name = cJSON_malloc(sizeof(char)))) {
          x->attribute_name[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "supportedServices")) {
        x->supported_services = cJSON_Getsupported_servicesValue(cJSON_GetObjectItemCaseSensitive(j, "supportedServices"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_supported_attribute_element(const list_of_supported_attribute_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->attribute_name) {
        cJSON_AddStringToObject(j, "attributeName", x->attribute_name);
      }
      else {
        cJSON_AddStringToObject(j, "attributeName", "");
      }
      cJSON_AddItemToObject(j, "supportedServices", cJSON_Createsupported_services(x->supported_services));
    }
  }
  return j;
}

char * cJSON_Printlist_of_supported_attribute_element(const list_of_supported_attribute_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_supported_attribute_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_supported_attribute_element(list_of_supported_attribute_element_t * x) {
  if (NULL != x) {
    if (NULL != x->attribute_name) {
      cJSON_free(x->attribute_name);
    }
    if (NULL != x->supported_services) {
      cJSON_Deletesupported_services(x->supported_services);
    }
    cJSON_free(x);
  }
}

list_of_supported_node_level_configuration_structure_element_t * cJSON_Parselist_of_supported_node_level_configuration_structure_element(const char * s) {
  list_of_supported_node_level_configuration_structure_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_supported_node_level_configuration_structure_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_supported_node_level_configuration_structure_element_t * cJSON_Getlist_of_supported_node_level_configuration_structure_elementValue(const cJSON * j) {
  list_of_supported_node_level_configuration_structure_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_supported_node_level_configuration_structure_element_t)))) {
      memset(x, 0, sizeof(list_of_supported_node_level_configuration_structure_element_t));
      if (cJSON_HasObjectItem(j, "listOfSupportedAttributes")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfSupportedAttributes");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_supported_attribute_elementValue(e1), sizeof(list_of_supported_attribute_element_t *));
          }
          x->list_of_supported_attributes = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructureName")) {
        x->ran_configuration_structure_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructureName")));
      }
      else {
        if (NULL != (x->ran_configuration_structure_name = cJSON_malloc(sizeof(char)))) {
          x->ran_configuration_structure_name[0] = '\0';
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_supported_node_level_configuration_structure_element(const list_of_supported_node_level_configuration_structure_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_supported_attributes) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfSupportedAttributes");
        if (NULL != j1) {
          list_of_supported_attribute_element_t * x1 = list_get_head(x->list_of_supported_attributes);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_supported_attribute_element(x1));
            x1 = list_get_next(x->list_of_supported_attributes);
          }
        }
      }
      if (NULL != x->ran_configuration_structure_name) {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", x->ran_configuration_structure_name);
      }
      else {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", "");
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_supported_node_level_configuration_structure_element(const list_of_supported_node_level_configuration_structure_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_supported_node_level_configuration_structure_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_supported_node_level_configuration_structure_element(list_of_supported_node_level_configuration_structure_element_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_supported_attributes) {
      list_of_supported_attribute_element_t * x1 = list_get_head(x->list_of_supported_attributes);
      while (NULL != x1) {
        cJSON_Deletelist_of_supported_attribute_element(x1);
        x1 = list_get_next(x->list_of_supported_attributes);
      }
      list_release(x->list_of_supported_attributes);
    }
    if (NULL != x->ran_configuration_structure_name) {
      cJSON_free(x->ran_configuration_structure_name);
    }
    cJSON_free(x);
  }
}

list_of_cells_for_ran_function_definition_element_t * cJSON_Parselist_of_cells_for_ran_function_definition_element(const char * s) {
  list_of_cells_for_ran_function_definition_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_cells_for_ran_function_definition_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_cells_for_ran_function_definition_element_t * cJSON_Getlist_of_cells_for_ran_function_definition_elementValue(const cJSON * j) {
  list_of_cells_for_ran_function_definition_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_cells_for_ran_function_definition_element_t)))) {
      memset(x, 0, sizeof(list_of_cells_for_ran_function_definition_element_t));
      if (cJSON_HasObjectItem(j, "cellGlobalID")) {
        x->cell_global_id = cJSON_Getcell_global_idValue(cJSON_GetObjectItemCaseSensitive(j, "cellGlobalID"));
      }
      if (cJSON_HasObjectItem(j, "listOfSupportedCellLevelRANConfigurationStructures")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfSupportedCellLevelRANConfigurationStructures");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_supported_node_level_configuration_structure_elementValue(e1), sizeof(list_of_supported_node_level_configuration_structure_element_t *));
          }
          x->list_of_supported_cell_level_ran_configuration_structures = x1;
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_cells_for_ran_function_definition_element(const list_of_cells_for_ran_function_definition_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "cellGlobalID", cJSON_Createcell_global_id(x->cell_global_id));
      if (NULL != x->list_of_supported_cell_level_ran_configuration_structures) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfSupportedCellLevelRANConfigurationStructures");
        if (NULL != j1) {
          list_of_supported_node_level_configuration_structure_element_t * x1 = list_get_head(x->list_of_supported_cell_level_ran_configuration_structures);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_supported_node_level_configuration_structure_element(x1));
            x1 = list_get_next(x->list_of_supported_cell_level_ran_configuration_structures);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_cells_for_ran_function_definition_element(const list_of_cells_for_ran_function_definition_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_cells_for_ran_function_definition_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_cells_for_ran_function_definition_element(list_of_cells_for_ran_function_definition_element_t * x) {
  if (NULL != x) {
    if (NULL != x->cell_global_id) {
      cJSON_Deletecell_global_id(x->cell_global_id);
    }
    if (NULL != x->list_of_supported_cell_level_ran_configuration_structures) {
      list_of_supported_node_level_configuration_structure_element_t * x1 = list_get_head(x->list_of_supported_cell_level_ran_configuration_structures);
      while (NULL != x1) {
        cJSON_Deletelist_of_supported_node_level_configuration_structure_element(x1);
        x1 = list_get_next(x->list_of_supported_cell_level_ran_configuration_structures);
      }
      list_release(x->list_of_supported_cell_level_ran_configuration_structures);
    }
    cJSON_free(x);
  }
}

ran_function_name_json_t * cJSON_Parseran_function(const char * s) {
  ran_function_name_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getran_functionValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ran_function_name_json_t * cJSON_Getran_functionValue(const cJSON * j) {
  ran_function_name_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ran_function_name_json_t)))) {
      memset(x, 0, sizeof(ran_function_name_json_t));
      if (cJSON_HasObjectItem(j, "ranFunctionDescription")) {
        x->ran_function_description = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranFunctionDescription")));
      }
      else {
        if (NULL != (x->ran_function_description = cJSON_malloc(sizeof(char)))) {
          x->ran_function_description[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "ranFunctionInstance")) {
        if (NULL != (x->ran_function_instance = cJSON_malloc(sizeof(int64_t)))) {
          *x->ran_function_instance = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ranFunctionInstance"));
        }
      }
      if (cJSON_HasObjectItem(j, "ranFunctionServiceModelOID")) {
        x->ran_function_service_model_oid = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranFunctionServiceModelOID")));
      }
      else {
        if (NULL != (x->ran_function_service_model_oid = cJSON_malloc(sizeof(char)))) {
          x->ran_function_service_model_oid[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "ranFunctionShortName")) {
        x->ran_function_short_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranFunctionShortName")));
      }
      else {
        if (NULL != (x->ran_function_short_name = cJSON_malloc(sizeof(char)))) {
          x->ran_function_short_name[0] = '\0';
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createran_function(const ran_function_name_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->ran_function_description) {
        cJSON_AddStringToObject(j, "ranFunctionDescription", x->ran_function_description);
      }
      else {
        cJSON_AddStringToObject(j, "ranFunctionDescription", "");
      }
      if (NULL != x->ran_function_instance) {
        cJSON_AddNumberToObject(j, "ranFunctionInstance", *x->ran_function_instance);
      }
      if (NULL != x->ran_function_service_model_oid) {
        cJSON_AddStringToObject(j, "ranFunctionServiceModelOID", x->ran_function_service_model_oid);
      }
      else {
        cJSON_AddStringToObject(j, "ranFunctionServiceModelOID", "");
      }
      if (NULL != x->ran_function_short_name) {
        cJSON_AddStringToObject(j, "ranFunctionShortName", x->ran_function_short_name);
      }
      else {
        cJSON_AddStringToObject(j, "ranFunctionShortName", "");
      }
    }
  }
  return j;
}

char * cJSON_Printran_function(const ran_function_name_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createran_function(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteran_function(ran_function_name_json_t * x) {
  if (NULL != x) {
    if (NULL != x->ran_function_description) {
      cJSON_free(x->ran_function_description);
    }
    if (NULL != x->ran_function_instance) {
      cJSON_free(x->ran_function_instance);
    }
    if (NULL != x->ran_function_service_model_oid) {
      cJSON_free(x->ran_function_service_model_oid);
    }
    if (NULL != x->ran_function_short_name) {
      cJSON_free(x->ran_function_short_name);
    }
    cJSON_free(x);
  }
}

ric_function_definition_json_t * cJSON_Parseric_function_definition(const char * s) {
  ric_function_definition_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getric_function_definitionValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ric_function_definition_json_t * cJSON_Getric_function_definitionValue(const cJSON * j) {
  ric_function_definition_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ric_function_definition_json_t)))) {
      memset(x, 0, sizeof(ric_function_definition_json_t));
      if (cJSON_HasObjectItem(j, "listOfCellsForRANFunctionDefinition")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfCellsForRANFunctionDefinition");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_cells_for_ran_function_definition_elementValue(e1), sizeof(list_of_cells_for_ran_function_definition_element_t *));
          }
          x->list_of_cells_for_ran_function_definition = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "listOfSupportedNodeLevelConfigurationStructures")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfSupportedNodeLevelConfigurationStructures");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_supported_node_level_configuration_structure_elementValue(e1), sizeof(list_of_supported_node_level_configuration_structure_element_t *));
          }
          x->list_of_supported_node_level_configuration_structures = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "ranFunctionName")) {
        x->ran_function_name = cJSON_Getran_functionValue(cJSON_GetObjectItemCaseSensitive(j, "ranFunctionName"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createric_function_definition(const ric_function_definition_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_cells_for_ran_function_definition) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfCellsForRANFunctionDefinition");
        if (NULL != j1) {
          list_of_cells_for_ran_function_definition_element_t * x1 = list_get_head(x->list_of_cells_for_ran_function_definition);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_cells_for_ran_function_definition_element(x1));
            x1 = list_get_next(x->list_of_cells_for_ran_function_definition);
          }
        }
      }
      if (NULL != x->list_of_supported_node_level_configuration_structures) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfSupportedNodeLevelConfigurationStructures");
        if (NULL != j1) {
          list_of_supported_node_level_configuration_structure_element_t * x1 = list_get_head(x->list_of_supported_node_level_configuration_structures);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_supported_node_level_configuration_structure_element(x1));
            x1 = list_get_next(x->list_of_supported_node_level_configuration_structures);
          }
        }
      }
      cJSON_AddItemToObject(j, "ranFunctionName", cJSON_Createran_function(x->ran_function_name));
    }
  }
  return j;
}

char * cJSON_Printric_function_definition(const ric_function_definition_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createric_function_definition(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteric_function_definition(ric_function_definition_json_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_cells_for_ran_function_definition) {
      list_of_cells_for_ran_function_definition_element_t * x1 = list_get_head(x->list_of_cells_for_ran_function_definition);
      while (NULL != x1) {
        cJSON_Deletelist_of_cells_for_ran_function_definition_element(x1);
        x1 = list_get_next(x->list_of_cells_for_ran_function_definition);
      }
      list_release(x->list_of_cells_for_ran_function_definition);
    }
    if (NULL != x->list_of_supported_node_level_configuration_structures) {
      list_of_supported_node_level_configuration_structure_element_t * x1 = list_get_head(x->list_of_supported_node_level_configuration_structures);
      while (NULL != x1) {
        cJSON_Deletelist_of_supported_node_level_configuration_structure_element(x1);
        x1 = list_get_next(x->list_of_supported_node_level_configuration_structures);
      }
      list_release(x->list_of_supported_node_level_configuration_structures);
    }
    if (NULL != x->ran_function_name) {
      cJSON_Deleteran_function(x->ran_function_name);
    }
    cJSON_free(x);
  }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
