/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_PrintUnformatted<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "ric_indication_message_json.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

list_of_configuration_structures_reported_element_t * cJSON_Parselist_of_configuration_structures_reported_element(const char * s) {
  list_of_configuration_structures_reported_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_configuration_structures_reported_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_configuration_structures_reported_element_t * cJSON_Getlist_of_configuration_structures_reported_elementValue(const cJSON * j) {
  list_of_configuration_structures_reported_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_configuration_structures_reported_element_t)))) {
      memset(x, 0, sizeof(list_of_configuration_structures_reported_element_t));
      if (cJSON_HasObjectItem(j, "changeType")) {
        x->change_type = cJSON_Getchange_typeValue(cJSON_GetObjectItemCaseSensitive(j, "changeType"));
      }
      if (cJSON_HasObjectItem(j, "oldValuesOfAttributes")) {
        x->old_values_of_attributes = cJSON_Getvalues_of_attributesValue(cJSON_GetObjectItemCaseSensitive(j, "oldValuesOfAttributes"));
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructureName")) {
        x->ran_configuration_structure_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructureName")));
      }
      else {
        if (NULL != (x->ran_configuration_structure_name = cJSON_malloc(sizeof(char)))) {
          x->ran_configuration_structure_name[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "valuesOfAttributes")) {
        x->values_of_attributes = cJSON_Getvalues_of_attributesValue(cJSON_GetObjectItemCaseSensitive(j, "valuesOfAttributes"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_configuration_structures_reported_element(const list_of_configuration_structures_reported_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "changeType", cJSON_Createchange_type(x->change_type));
      if (NULL != x->old_values_of_attributes) {
        cJSON_AddItemToObject(j, "oldValuesOfAttributes", cJSON_Createvalues_of_attributes(x->old_values_of_attributes));
      }
      if (NULL != x->ran_configuration_structure_name) {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", x->ran_configuration_structure_name);
      }
      else {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", "");
      }
      cJSON_AddItemToObject(j, "valuesOfAttributes", cJSON_Createvalues_of_attributes(x->values_of_attributes));
    }
  }
  return j;
}

char * cJSON_Printlist_of_configuration_structures_reported_element(const list_of_configuration_structures_reported_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_configuration_structures_reported_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_configuration_structures_reported_element(list_of_configuration_structures_reported_element_t * x) {
  if (NULL != x) {
    if (NULL != x->old_values_of_attributes) {
      cJSON_Deletevalues_of_attributes(x->old_values_of_attributes);
    }
    if (NULL != x->ran_configuration_structure_name) {
      cJSON_free(x->ran_configuration_structure_name);
    }
    if (NULL != x->values_of_attributes) {
      cJSON_Deletevalues_of_attributes(x->values_of_attributes);
    }
    cJSON_free(x);
  }
}

list_of_cells_reported_element_t * cJSON_Parselist_of_cells_reported_element(const char * s) {
  list_of_cells_reported_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_cells_reported_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_cells_reported_element_t * cJSON_Getlist_of_cells_reported_elementValue(const cJSON * j) {
  list_of_cells_reported_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_cells_reported_element_t)))) {
      memset(x, 0, sizeof(list_of_cells_reported_element_t));
      if (cJSON_HasObjectItem(j, "cellGlobalId")) {
        x->cell_global_id = cJSON_Getcell_global_idValue(cJSON_GetObjectItemCaseSensitive(j, "cellGlobalId"));
      }
      if (cJSON_HasObjectItem(j, "listOfConfigurationStructuresReported")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfConfigurationStructuresReported");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_configuration_structures_reported_elementValue(e1), sizeof(list_of_configuration_structures_reported_element_t *));
          }
          x->list_of_configuration_structures_reported = x1;
        }
      }
      else {
        x->list_of_configuration_structures_reported = list_create(false, NULL);
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_cells_reported_element(const list_of_cells_reported_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "cellGlobalId", cJSON_Createcell_global_id(x->cell_global_id));
      if (NULL != x->list_of_configuration_structures_reported) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfConfigurationStructuresReported");
        if (NULL != j1) {
          list_of_configuration_structures_reported_element_t * x1 = list_get_head(x->list_of_configuration_structures_reported);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_configuration_structures_reported_element(x1));
            x1 = list_get_next(x->list_of_configuration_structures_reported);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_cells_reported_element(const list_of_cells_reported_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_cells_reported_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_cells_reported_element(list_of_cells_reported_element_t * x) {
  if (NULL != x) {
    if (NULL != x->cell_global_id) {
      cJSON_Deletecell_global_id(x->cell_global_id);
    }
    if (NULL != x->list_of_configuration_structures_reported) {
      list_of_configuration_structures_reported_element_t * x1 = list_get_head(x->list_of_configuration_structures_reported);
      while (NULL != x1) {
        cJSON_Deletelist_of_configuration_structures_reported_element(x1);
        x1 = list_get_next(x->list_of_configuration_structures_reported);
      }
      list_release(x->list_of_configuration_structures_reported);
    }
    cJSON_free(x);
  }
}

indication_message_format_json_t * cJSON_Parseindication_message_format(const char * s) {
  indication_message_format_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getindication_message_formatValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

indication_message_format_json_t * cJSON_Getindication_message_formatValue(const cJSON * j) {
  indication_message_format_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(indication_message_format_json_t)))) {
      memset(x, 0, sizeof(indication_message_format_json_t));
      if (cJSON_HasObjectItem(j, "listOfConfigurationStructuresReported")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfConfigurationStructuresReported");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_configuration_structures_reported_elementValue(e1), sizeof(list_of_configuration_structures_reported_element_t *));
          }
          x->list_of_configuration_structures_reported = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "listOfCellsReported")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfCellsReported");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_cells_reported_elementValue(e1), sizeof(list_of_cells_reported_element_t *));
          }
          x->list_of_cells_reported = x1;
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createindication_message_format(const indication_message_format_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_configuration_structures_reported) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfConfigurationStructuresReported");
        if (NULL != j1) {
          list_of_configuration_structures_reported_element_t * x1 = list_get_head(x->list_of_configuration_structures_reported);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_configuration_structures_reported_element(x1));
            x1 = list_get_next(x->list_of_configuration_structures_reported);
          }
        }
      }
      if (NULL != x->list_of_cells_reported) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfCellsReported");
        if (NULL != j1) {
          list_of_cells_reported_element_t * x1 = list_get_head(x->list_of_cells_reported);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_cells_reported_element(x1));
            x1 = list_get_next(x->list_of_cells_reported);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printindication_message_format(const indication_message_format_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createindication_message_format(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteindication_message_format(indication_message_format_json_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_configuration_structures_reported) {
      list_of_configuration_structures_reported_element_t * x1 = list_get_head(x->list_of_configuration_structures_reported);
      while (NULL != x1) {
        cJSON_Deletelist_of_configuration_structures_reported_element(x1);
        x1 = list_get_next(x->list_of_configuration_structures_reported);
      }
      list_release(x->list_of_configuration_structures_reported);
    }
    if (NULL != x->list_of_cells_reported) {
      list_of_cells_reported_element_t * x1 = list_get_head(x->list_of_cells_reported);
      while (NULL != x1) {
        cJSON_Deletelist_of_cells_reported_element(x1);
        x1 = list_get_next(x->list_of_cells_reported);
      }
      list_release(x->list_of_cells_reported);
    }
    cJSON_free(x);
  }
}

ric_indication_message_json_t * cJSON_Parseric_indication_message(const char * s) {
  ric_indication_message_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getric_indication_messageValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ric_indication_message_json_t * cJSON_Getric_indication_messageValue(const cJSON * j) {
  ric_indication_message_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ric_indication_message_json_t)))) {
      memset(x, 0, sizeof(ric_indication_message_json_t));
      if (cJSON_HasObjectItem(j, "indicationMessageFormat")) {
        x->indication_message_format = cJSON_Getindication_message_formatValue(cJSON_GetObjectItemCaseSensitive(j, "indicationMessageFormat"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createric_indication_message(const ric_indication_message_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "indicationMessageFormat", cJSON_Createindication_message_format(x->indication_message_format));
    }
  }
  return j;
}

char * cJSON_Printric_indication_message(const ric_indication_message_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createric_indication_message(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteric_indication_message(ric_indication_message_json_t * x) {
  if (NULL != x) {
    if (NULL != x->indication_message_format) {
      cJSON_Deleteindication_message_format(x->indication_message_format);
    }
    cJSON_free(x);
  }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
