/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include "ric_control_header_json.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

control_header_format_json_t * cJSON_ParseControlHeaderFormat(const char * s) {
    control_header_format_json_t * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetControlHeaderFormatValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

control_header_format_json_t * cJSON_GetControlHeaderFormatValue(const cJSON * j) {
    control_header_format_json_t * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(control_header_format_json_t)))) {
            memset(x, 0, sizeof(control_header_format_json_t));
            if (cJSON_HasObjectItem(j, "ricStyleType")) {
                x->ric_style_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ricStyleType"));
            }
        }
    }
    return x;
}

cJSON * cJSON_CreateControlHeaderFormat(const control_header_format_json_t * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddNumberToObject(j, "ricStyleType", x->ric_style_type);
        }
    }
    return j;
}

char * cJSON_PrintControlHeaderFormat(const control_header_format_json_t * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateControlHeaderFormat(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_DeleteControlHeaderFormat(control_header_format_json_t * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

/*ric_control_header_json_t * cJSON_GetRicControlHeaderJsonValue(const cJSON * j) {
    ric_control_header_json_t * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(ric_control_header_json_t)))) {
            memset(x, 0, sizeof(ric_control_header_json_t));
            if (cJSON_HasObjectItem(j, "controlHeaderFormat")) {
                x->control_header_format = cJSON_GetControlHeaderFormatValue(cJSON_GetObjectItemCaseSensitive(j, "controlHeaderFormat"));
            }
            if (cJSON_HasObjectItem(j, "ricStyleType")){
                x->ric_style_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ricStyleType"));
            }
        }
    }
    return x;
}*/


ric_control_header_json_t * cJSON_ParseRicControlHeaderJson(const char * s) {
    ric_control_header_json_t * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetRicControlHeaderJsonValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

ric_control_header_json_t * cJSON_GetRicControlHeaderJsonValue(const cJSON * j) {
    ric_control_header_json_t * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(ric_control_header_json_t)))) {
            memset(x, 0, sizeof(ric_control_header_json_t));
            if (cJSON_HasObjectItem(j, "controlHeaderFormat")) {
                x->control_header_format = cJSON_GetControlHeaderFormatValue(cJSON_GetObjectItemCaseSensitive(j, "controlHeaderFormat"));
            }
            if (cJSON_HasObjectItem(j, "ricStyleType")){
                x->ric_style_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ricStyleType"));
            }
        }
    }
    return x;
}



cJSON * cJSON_CreateRicControlHeaderJson(const ric_control_header_json_t * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddItemToObject(j, "controlHeaderFormat", cJSON_CreateControlHeaderFormat(x->control_header_format));
            cJSON_AddNumberToObject(j, "ricStyleType", x->ric_style_type);
        }
    }
    return j;
}

char * cJSON_PrintRicControlHeaderJson(const ric_control_header_json_t * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateRicControlHeaderJson(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_DeleteRicControlHeaderJson(ric_control_header_json_t * x) {
    if (NULL != x) {
        if (NULL != x->control_header_format) {
            cJSON_DeleteControlHeaderFormat(x->control_header_format);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
