/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <string.h>

#include "ric_indication_header.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

enum indication_reason cJSON_Getindication_reasonValue(const cJSON * j) {
  enum indication_reason x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "periodic")) x = INDICATION_REASON_periodic;
    else if (!strcmp(cJSON_GetStringValue(j), "uponChange")) x = INDICATION_REASON_upon_change;
    else if (!strcmp(cJSON_GetStringValue(j), "uponSubscription")) x = INDICATION_REASON_upon_subscription;
  }
  return x;
}

cJSON * cJSON_Createindication_reason(const enum indication_reason x) {
  cJSON * j = NULL;
  switch (x) {
    case INDICATION_REASON_periodic: j = cJSON_CreateString("periodic"); break;
    case INDICATION_REASON_upon_change: j = cJSON_CreateString("uponChange"); break;
    case INDICATION_REASON_upon_subscription: j = cJSON_CreateString("uponSubscription"); break;
  }
  return j;
}

struct indication_header_format * cJSON_Parseindication_header_format(const char * s) {
  struct indication_header_format * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getindication_header_formatValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

struct indication_header_format * cJSON_Getindication_header_formatValue(const cJSON * j) {
  struct indication_header_format * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(struct indication_header_format)))) {
      memset(x, 0, sizeof(struct indication_header_format));
      if (cJSON_HasObjectItem(j, "eventTime")) {
        x->event_time = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "eventTime")));
      }
      else {
        if (NULL != (x->event_time = cJSON_malloc(sizeof(char)))) {
          x->event_time[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "indicationReason")) {
        x->indication_reason = cJSON_Getindication_reasonValue(cJSON_GetObjectItemCaseSensitive(j, "indicationReason"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createindication_header_format(const struct indication_header_format * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->event_time) {
        cJSON_AddStringToObject(j, "eventTime", x->event_time);
      }
      else {
        cJSON_AddStringToObject(j, "eventTime", "");
      }
      cJSON_AddItemToObject(j, "indicationReason", cJSON_Createindication_reason(x->indication_reason));
    }
  }
  return j;
}

char * cJSON_Printindication_header_format(const struct indication_header_format * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createindication_header_format(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteindication_header_format(struct indication_header_format * x) {
  if (NULL != x) {
    if (NULL != x->event_time) {
      cJSON_free(x->event_time);
    }
    cJSON_free(x);
  }
}

struct ric_indication_header * cJSON_Parseric_indication_header(const char * s) {
  struct ric_indication_header * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getric_indication_headerValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

struct ric_indication_header * cJSON_Getric_indication_headerValue(const cJSON * j) {
  struct ric_indication_header * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(struct ric_indication_header)))) {
      memset(x, 0, sizeof(struct ric_indication_header));
      if (cJSON_HasObjectItem(j, "indicationHeaderFormat")) {
        x->indication_header_format = cJSON_Getindication_header_formatValue(cJSON_GetObjectItemCaseSensitive(j, "indicationHeaderFormat"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createric_indication_header(const struct ric_indication_header * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->indication_header_format) {
        cJSON_AddItemToObject(j, "indicationHeaderFormat", cJSON_Createindication_header_format(x->indication_header_format));
      }
    }
  }
  return j;
}

char * cJSON_Printric_indication_header(const struct ric_indication_header * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createric_indication_header(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteric_indication_header(struct ric_indication_header * x) {
  if (NULL != x) {
    if (NULL != x->indication_header_format) {
      cJSON_Deleteindication_header_format(x->indication_header_format);
    }
    cJSON_free(x);
  }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
