/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <string.h>
#include "ric_action_definition.h"
#include "assert.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif



report_type_e cJSON_Getreport_typeValue(const cJSON * j) {
  report_type_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "all")) x = REPORT_TYPE_ALL;
    else if (!strcmp(cJSON_GetStringValue(j), "change")) x = REPORT_TYPE_CHANGE;
  }
  return x;
}

cJSON * cJSON_Createreport_type(const report_type_e x) {
  cJSON * j = NULL;
  switch (x) {
    case REPORT_TYPE_ALL: j = cJSON_CreateString("all"); break;
    case REPORT_TYPE_CHANGE: j = cJSON_CreateString("change"); break;
    default:
      assert(0 != 0 && "No ccc report type");
  }
  return j;
}

struct plmn_identity * cJSON_Parseplmn_identity(const char * s) {
  struct plmn_identity * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getplmn_identityValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

struct plmn_identity * cJSON_Getplmn_identityValue(const cJSON * j) {
  struct plmn_identity * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(struct plmn_identity)))) {
      memset(x, 0, sizeof(struct plmn_identity));
      if (cJSON_HasObjectItem(j, "mcc")) {
        x->mcc = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "mcc")));
      }
      if (cJSON_HasObjectItem(j, "mnc")) {
        x->mnc = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "mnc")));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createplmn_identity(const struct plmn_identity * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->mcc) {
        cJSON_AddStringToObject(j, "mcc", x->mcc);
      }
      if (NULL != x->mnc) {
        cJSON_AddStringToObject(j, "mnc", x->mnc);
      }
    }
  }
  return j;
}

char * cJSON_Printplmn_identity(const struct plmn_identity * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createplmn_identity(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteplmn_identity(struct plmn_identity * x) {
  if (NULL != x) {
    if (NULL != x->mcc) {
      cJSON_free(x->mcc);
    }
    if (NULL != x->mnc) {
      cJSON_free(x->mnc);
    }
    cJSON_free(x);
  }
}

struct cell_global_id * cJSON_Parsecell_global_id(const char * s) {
  struct cell_global_id * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getcell_global_idValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

struct cell_global_id * cJSON_Getcell_global_idValue(const cJSON * j) {
  struct cell_global_id * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(struct cell_global_id)))) {
      memset(x, 0, sizeof(struct cell_global_id));
      if (cJSON_HasObjectItem(j, "nRCellIdentity")) {
        x->n_r_cell_identity = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "nRCellIdentity")));
      }
      else {
        if (NULL != (x->n_r_cell_identity = cJSON_malloc(sizeof(char)))) {
          x->n_r_cell_identity[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "plmnIdentity")) {
        x->plmn_identity = cJSON_Getplmn_identityValue(cJSON_GetObjectItemCaseSensitive(j, "plmnIdentity"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createcell_global_id(const struct cell_global_id * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->n_r_cell_identity) {
        cJSON_AddStringToObject(j, "nRCellIdentity", x->n_r_cell_identity);
      }
      else {
        cJSON_AddStringToObject(j, "nRCellIdentity", "");
      }
      cJSON_AddItemToObject(j, "plmnIdentity", cJSON_Createplmn_identity(x->plmn_identity));
    }
  }
  return j;
}

char * cJSON_Printcell_global_id(const struct cell_global_id * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createcell_global_id(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletecell_global_id(struct cell_global_id * x) {
  if (NULL != x) {
    if (NULL != x->n_r_cell_identity) {
      cJSON_free(x->n_r_cell_identity);
    }
    if (NULL != x->plmn_identity) {
      cJSON_Deleteplmn_identity(x->plmn_identity);
    }
    cJSON_free(x);
  }
}

list_of_attribute_element_t * cJSON_Parselist_of_attribute_element(const char * s) {
  list_of_attribute_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_attribute_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_attribute_element_t * cJSON_Getlist_of_attribute_elementValue(const cJSON * j) {
  list_of_attribute_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_attribute_element_t)))) {
      memset(x, 0, sizeof(list_of_attribute_element_t));
      if (cJSON_HasObjectItem(j, "attributeName")) {
        x->attribute_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "attributeName")));
      }
      else {
        if (NULL != (x->attribute_name = cJSON_malloc(sizeof(char)))) {
          x->attribute_name[0] = '\0';
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_attribute_element(const list_of_attribute_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->attribute_name) {
        cJSON_AddStringToObject(j, "attributeName", x->attribute_name);
      }
      else {
        cJSON_AddStringToObject(j, "attributeName", "");
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_attribute_element(const list_of_attribute_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_attribute_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_attribute_element(list_of_attribute_element_t * x) {
  if (NULL != x) {
    if (NULL != x->attribute_name) {
      cJSON_free(x->attribute_name);
    }
    cJSON_free(x);
  }
}

lst_act_def_ran_conf_element_t * cJSON_Parselst_act_def_node_ran_conf_element(const char * s) {
  lst_act_def_ran_conf_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlst_act_def_node_ran_conf_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

lst_act_def_ran_conf_element_t * cJSON_Getlst_act_def_node_ran_conf_elementValue(const cJSON * j) {
  lst_act_def_ran_conf_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(lst_act_def_ran_conf_element_t)))) {
      memset(x, 0, sizeof(lst_act_def_ran_conf_element_t));
      if (cJSON_HasObjectItem(j, "listOfAttributes")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfAttributes");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_attribute_elementValue(e1), sizeof(list_of_attribute_element_t *));
          }
          x->list_of_attributes = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructureName")) {
        x->ran_configuration_structure_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructureName")));
      }
      else {
        if (NULL != (x->ran_configuration_structure_name = cJSON_malloc(sizeof(char)))) {
          x->ran_configuration_structure_name[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "reportType")) {
        x->report_type = cJSON_Getreport_typeValue(cJSON_GetObjectItemCaseSensitive(j, "reportType"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlst_act_def_node_ran_conf_element(const lst_act_def_ran_conf_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_attributes) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfAttributes");
        if (NULL != j1) {
          list_of_attribute_element_t * x1 = list_get_head(x->list_of_attributes);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_attribute_element(x1));
            x1 = list_get_next(x->list_of_attributes);
          }
        }
      }
      if (NULL != x->ran_configuration_structure_name) {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", x->ran_configuration_structure_name);
      }
      else {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", "");
      }
      cJSON_AddItemToObject(j, "reportType", cJSON_Createreport_type(x->report_type));
    }
  }
  return j;
}

char * cJSON_Printlst_act_def_node_ran_conf_element(const lst_act_def_ran_conf_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlst_act_def_node_ran_conf_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelst_act_def_node_ran_conf_element(lst_act_def_ran_conf_element_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_attributes) {
      list_of_attribute_element_t * x1 = list_get_head(x->list_of_attributes);
      while (NULL != x1) {
        cJSON_Deletelist_of_attribute_element(x1);
        x1 = list_get_next(x->list_of_attributes);
      }
      list_release(x->list_of_attributes);
    }
    if (NULL != x->ran_configuration_structure_name) {
      cJSON_free(x->ran_configuration_structure_name);
    }
    cJSON_free(x);
  }
}

lst_act_def_cell_ran_conf_element_t * cJSON_Parselst_act_def_cell_ran_conf_element(const char * s) {
  lst_act_def_cell_ran_conf_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlst_act_def_cell_ran_conf_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

lst_act_def_cell_ran_conf_element_t * cJSON_Getlst_act_def_cell_ran_conf_elementValue(const cJSON * j) {
  lst_act_def_cell_ran_conf_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(lst_act_def_cell_ran_conf_element_t)))) {
      memset(x, 0, sizeof(lst_act_def_cell_ran_conf_element_t));
      if (cJSON_HasObjectItem(j, "cellGlobalId")) {
        x->cell_global_id = cJSON_Getcell_global_idValue(cJSON_GetObjectItemCaseSensitive(j, "cellGlobalId"));
      }
      if (cJSON_HasObjectItem(j, "listOfCellLevelRANConfigurationStructuresForADF")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfCellLevelRANConfigurationStructuresForADF");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlst_act_def_node_ran_conf_elementValue(e1), sizeof(lst_act_def_ran_conf_element_t *));
          }
          x->list_of_cell_level_ran_configuration_structures_for_adf = x1;
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlst_act_def_cell_ran_conf_element(const lst_act_def_cell_ran_conf_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->cell_global_id) {
        cJSON_AddItemToObject(j, "cellGlobalId", cJSON_Createcell_global_id(x->cell_global_id));
      }
      if (NULL != x->list_of_cell_level_ran_configuration_structures_for_adf) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfCellLevelRANConfigurationStructuresForADF");
        if (NULL != j1) {
          lst_act_def_ran_conf_element_t * x1 = list_get_head(x->list_of_cell_level_ran_configuration_structures_for_adf);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlst_act_def_node_ran_conf_element(x1));
            x1 = list_get_next(x->list_of_cell_level_ran_configuration_structures_for_adf);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printlst_act_def_cell_ran_conf_element(const lst_act_def_cell_ran_conf_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlst_act_def_cell_ran_conf_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelst_act_def_cell_ran_conf_element(lst_act_def_cell_ran_conf_element_t * x) {
  if (NULL != x) {
    if (NULL != x->cell_global_id) {
      cJSON_Deletecell_global_id(x->cell_global_id);
    }
    if (NULL != x->list_of_cell_level_ran_configuration_structures_for_adf) {
      lst_act_def_ran_conf_element_t * x1 = list_get_head(x->list_of_cell_level_ran_configuration_structures_for_adf);
      while (NULL != x1) {
        cJSON_Deletelst_act_def_node_ran_conf_element(x1);
        x1 = list_get_next(x->list_of_cell_level_ran_configuration_structures_for_adf);
      }
      list_release(x->list_of_cell_level_ran_configuration_structures_for_adf);
    }
    cJSON_free(x);
  }
}

action_definition_format_t * cJSON_Parseaction_definition_format(const char * s) {
  action_definition_format_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getaction_definition_formatValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

action_definition_format_t * cJSON_Getaction_definition_formatValue(const cJSON * j) {
  action_definition_format_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(action_definition_format_t)))) {
      memset(x, 0, sizeof(action_definition_format_t));
      if (cJSON_HasObjectItem(j, "listOfNodeLevelRANConfigurationStructuresForADF")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfNodeLevelRANConfigurationStructuresForADF");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlst_act_def_node_ran_conf_elementValue(e1), sizeof(lst_act_def_ran_conf_element_t *));
          }
          x->lst_act_def_node_ran_conf = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "listOfCellConfigurationsToBeReportedForADF")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfCellConfigurationsToBeReportedForADF");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlst_act_def_cell_ran_conf_elementValue(e1), sizeof(lst_act_def_cell_ran_conf_element_t *));
          }
          x->lst_act_def_cell_ran_conf = x1;
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createaction_definition_format(const action_definition_format_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->lst_act_def_node_ran_conf) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfNodeLevelRANConfigurationStructuresForADF");
        if (NULL != j1) {
          lst_act_def_ran_conf_element_t * x1 = list_get_head(x->lst_act_def_node_ran_conf);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlst_act_def_node_ran_conf_element(x1));
            x1 = list_get_next(x->lst_act_def_node_ran_conf);
          }
        }
      }
      if (NULL != x->lst_act_def_cell_ran_conf) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfCellConfigurationsToBeReportedForADF");
        if (NULL != j1) {
          lst_act_def_cell_ran_conf_element_t * x1 = list_get_head(x->lst_act_def_cell_ran_conf);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlst_act_def_cell_ran_conf_element(x1));
            x1 = list_get_next(x->lst_act_def_cell_ran_conf);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printaction_definition_format(const action_definition_format_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createaction_definition_format(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteaction_definition_format(action_definition_format_t * x) {
  if (NULL != x) {
    if (NULL != x->lst_act_def_node_ran_conf) {
      lst_act_def_ran_conf_element_t * x1 = list_get_head(x->lst_act_def_node_ran_conf);
      while (NULL != x1) {
        cJSON_Deletelst_act_def_node_ran_conf_element(x1);
        x1 = list_get_next(x->lst_act_def_node_ran_conf);
      }
      list_release(x->lst_act_def_node_ran_conf);
    }
    if (NULL != x->lst_act_def_cell_ran_conf) {
      lst_act_def_cell_ran_conf_element_t * x1 = list_get_head(x->lst_act_def_cell_ran_conf);
      while (NULL != x1) {
        cJSON_Deletelst_act_def_cell_ran_conf_element(x1);
        x1 = list_get_next(x->lst_act_def_cell_ran_conf);
      }
      list_release(x->lst_act_def_cell_ran_conf);
    }
    cJSON_free(x);
  }
}

ric_action_definition_t * cJSON_Parseric_action_definition(const char * s) {
  ric_action_definition_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getric_action_definitionValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ric_action_definition_t * cJSON_Getric_action_definitionValue(const cJSON * j) {
  ric_action_definition_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ric_action_definition_t)))) {
      memset(x, 0, sizeof(ric_action_definition_t));
      if (cJSON_HasObjectItem(j, "actionDefinitionFormat")) {
        x->action_definition_format = cJSON_Getaction_definition_formatValue(cJSON_GetObjectItemCaseSensitive(j, "actionDefinitionFormat"));
      }
      if (cJSON_HasObjectItem(j, "ricStyleType")) {
        x->ric_style_type = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ricStyleType"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createric_action_definition(const ric_action_definition_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "actionDefinitionFormat", cJSON_Createaction_definition_format(x->action_definition_format));
      cJSON_AddNumberToObject(j, "ricStyleType", x->ric_style_type);
    }
  }
  return j;
}

char * cJSON_Printric_action_definition(const ric_action_definition_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createric_action_definition(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteric_action_definition(ric_action_definition_t * x) {
  if (NULL != x) {
    if (NULL != x->action_definition_format) {
      cJSON_Deleteaction_definition_format(x->action_definition_format);
    }
    cJSON_free(x);
  }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
