/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "ric_control_outcome_json.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

ccc_cause_e cJSON_GetcauseValue(const cJSON * j) {
  ccc_cause_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "IncompatibleState")) x = CAUSE_INCOMPATIBLE_STATE;
    else if (!strcmp(cJSON_GetStringValue(j), "JsonError")) x = CAUSE_JSON_ERROR;
    else if (!strcmp(cJSON_GetStringValue(j), "NotAvailable")) x = CAUSE_NOT_AVAILABLE;
    else if (!strcmp(cJSON_GetStringValue(j), "NotSupported")) x = CAUSE_NOT_SUPPORTED;
    else if (!strcmp(cJSON_GetStringValue(j), "SemanticError")) x = CAUSE_SEMANTIC_ERROR;
    else if (!strcmp(cJSON_GetStringValue(j), "Unspecified")) x = CAUSE_UNSPECIFIED;
  }
  return x;
}

cJSON * cJSON_Createcause(const ccc_cause_e x) {
  cJSON * j = NULL;
  switch (x) {
    case CAUSE_INCOMPATIBLE_STATE: j = cJSON_CreateString("IncompatibleState"); break;
    case CAUSE_JSON_ERROR: j = cJSON_CreateString("JsonError"); break;
    case CAUSE_NOT_AVAILABLE: j = cJSON_CreateString("NotAvailable"); break;
    case CAUSE_NOT_SUPPORTED: j = cJSON_CreateString("NotSupported"); break;
    case CAUSE_SEMANTIC_ERROR: j = cJSON_CreateString("SemanticError"); break;
    case CAUSE_UNSPECIFIED: j = cJSON_CreateString("Unspecified"); break;
    default:
      break;
  }
  return j;
}

ran_configuration_structures_accepted_list_element_t * cJSON_Parseran_configuration_structures_accepted_list_element(const char * s) {
  ran_configuration_structures_accepted_list_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getran_configuration_structures_accepted_list_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ran_configuration_structures_accepted_list_element_t * cJSON_Getran_configuration_structures_accepted_list_elementValue(const cJSON * j) {
  ran_configuration_structures_accepted_list_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ran_configuration_structures_accepted_list_element_t)))) {
      memset(x, 0, sizeof(ran_configuration_structures_accepted_list_element_t));
      if (cJSON_HasObjectItem(j, "appliedTimestamp")) {
        x->applied_timestamp = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "appliedTimestamp")));
      }
      if (cJSON_HasObjectItem(j, "currentValuesOfAttributes")) {
        x->current_values_of_attributes = cJSON_Getvalues_of_attributesValue(cJSON_GetObjectItemCaseSensitive(j, "currentValuesOfAttributes"));
      }
      if (cJSON_HasObjectItem(j, "oldValuesOfAttributes")) {
        x->old_values_of_attributes = cJSON_Getvalues_of_attributesValue(cJSON_GetObjectItemCaseSensitive(j, "oldValuesOfAttributes"));
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructureName")) {
        x->ran_configuration_structure_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructureName")));
      }
      else {
        if (NULL != (x->ran_configuration_structure_name = cJSON_malloc(sizeof(char)))) {
          x->ran_configuration_structure_name[0] = '\0';
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createran_configuration_structures_accepted_list_element(const ran_configuration_structures_accepted_list_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->applied_timestamp) {
        cJSON_AddStringToObject(j, "appliedTimestamp", x->applied_timestamp);
      }
      cJSON_AddItemToObject(j, "currentValuesOfAttributes", cJSON_Createvalues_of_attributes(x->current_values_of_attributes));
      cJSON_AddItemToObject(j, "oldValuesOfAttributes", cJSON_Createvalues_of_attributes(x->old_values_of_attributes));
      if (NULL != x->ran_configuration_structure_name) {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", x->ran_configuration_structure_name);
      }
      else {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", "");
      }
    }
  }
  return j;
}

char * cJSON_Printran_configuration_structures_accepted_list_element(const ran_configuration_structures_accepted_list_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createran_configuration_structures_accepted_list_element(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteran_configuration_structures_accepted_list_element(ran_configuration_structures_accepted_list_element_t * x) {
  if (NULL != x) {
    if (NULL != x->applied_timestamp) {
      cJSON_free(x->applied_timestamp);
    }
    if (NULL != x->current_values_of_attributes) {
      cJSON_Deletevalues_of_attributes(x->current_values_of_attributes);
    }
    if (NULL != x->old_values_of_attributes) {
      cJSON_Deletevalues_of_attributes(x->old_values_of_attributes);
    }
    if (NULL != x->ran_configuration_structure_name) {
      cJSON_free(x->ran_configuration_structure_name);
    }
    cJSON_free(x);
  }
}

ran_configuration_structures_failed_list_element_t * cJSON_Parseran_configuration_structures_failed_list_element(const char * s) {
  ran_configuration_structures_failed_list_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getran_configuration_structures_failed_list_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ran_configuration_structures_failed_list_element_t * cJSON_Getran_configuration_structures_failed_list_elementValue(const cJSON * j) {
  ran_configuration_structures_failed_list_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ran_configuration_structures_failed_list_element_t)))) {
      memset(x, 0, sizeof(ran_configuration_structures_failed_list_element_t));
      if (cJSON_HasObjectItem(j, "cause")) {
        x->cause = cJSON_GetcauseValue(cJSON_GetObjectItemCaseSensitive(j, "cause"));
      }
      if (cJSON_HasObjectItem(j, "oldValuesOfAttributes")) {
        x->old_values_of_attributes = cJSON_Getvalues_of_attributesValue(cJSON_GetObjectItemCaseSensitive(j, "oldValuesOfAttributes"));
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructureName")) {
        x->ran_configuration_structure_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructureName")));
      }
      else {
        if (NULL != (x->ran_configuration_structure_name = cJSON_malloc(sizeof(char)))) {
          x->ran_configuration_structure_name[0] = '\0';
        }
      }
      if (cJSON_HasObjectItem(j, "requestedValuesOfAttributes")) {
        x->requested_values_of_attributes = cJSON_Getvalues_of_attributesValue(cJSON_GetObjectItemCaseSensitive(j, "requestedValuesOfAttributes"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createran_configuration_structures_failed_list_element(const ran_configuration_structures_failed_list_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "cause", cJSON_Createcause(x->cause));
      cJSON_AddItemToObject(j, "oldValuesOfAttributes", cJSON_Createvalues_of_attributes(x->old_values_of_attributes));
      if (NULL != x->ran_configuration_structure_name) {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", x->ran_configuration_structure_name);
      }
      else {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", "");
      }
      cJSON_AddItemToObject(j, "requestedValuesOfAttributes", cJSON_Createvalues_of_attributes(x->requested_values_of_attributes));
    }
  }
  return j;
}

char * cJSON_Printran_configuration_structures_failed_list_element(const ran_configuration_structures_failed_list_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createran_configuration_structures_failed_list_element(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteran_configuration_structures_failed_list_element(ran_configuration_structures_failed_list_element_t * x) {
  if (NULL != x) {
    if (NULL != x->old_values_of_attributes) {
      cJSON_Deletevalues_of_attributes(x->old_values_of_attributes);
    }
    if (NULL != x->ran_configuration_structure_name) {
      cJSON_free(x->ran_configuration_structure_name);
    }
    if (NULL != x->requested_values_of_attributes) {
      cJSON_Deletevalues_of_attributes(x->requested_values_of_attributes);
    }
    cJSON_free(x);
  }
}

list_of_cells_for_control_outcome_element_t * cJSON_Parselist_of_cells_for_control_outcome_element(const char * s) {
  list_of_cells_for_control_outcome_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_cells_for_control_outcome_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_cells_for_control_outcome_element_t * cJSON_Getlist_of_cells_for_control_outcome_elementValue(const cJSON * j) {
  list_of_cells_for_control_outcome_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_cells_for_control_outcome_element_t)))) {
      memset(x, 0, sizeof(list_of_cells_for_control_outcome_element_t));
      if (cJSON_HasObjectItem(j, "cellGlobalId")) {
        x->cell_global_id = cJSON_Getcell_global_idValue(cJSON_GetObjectItemCaseSensitive(j, "cellGlobalId"));
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructuresAcceptedList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructuresAcceptedList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getran_configuration_structures_accepted_list_elementValue(e1), sizeof(ran_configuration_structures_accepted_list_element_t *));
          }
          x->ran_configuration_structures_accepted_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructuresFailedList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructuresFailedList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getran_configuration_structures_failed_list_elementValue(e1), sizeof(ran_configuration_structures_failed_list_element_t *));
          }
          x->ran_configuration_structures_failed_list = x1;
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_cells_for_control_outcome_element(const list_of_cells_for_control_outcome_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "cellGlobalId", cJSON_Createcell_global_id(x->cell_global_id));
      if (NULL != x->ran_configuration_structures_accepted_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "ranConfigurationStructuresAcceptedList");
        if (NULL != j1) {
          ran_configuration_structures_accepted_list_element_t * x1 = list_get_head(x->ran_configuration_structures_accepted_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createran_configuration_structures_accepted_list_element(x1));
            x1 = list_get_next(x->ran_configuration_structures_accepted_list);
          }
        }
      }
      if (NULL != x->ran_configuration_structures_failed_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "ranConfigurationStructuresFailedList");
        if (NULL != j1) {
          ran_configuration_structures_failed_list_element_t * x1 = list_get_head(x->ran_configuration_structures_failed_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createran_configuration_structures_failed_list_element(x1));
            x1 = list_get_next(x->ran_configuration_structures_failed_list);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_cells_for_control_outcome_element(const list_of_cells_for_control_outcome_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_cells_for_control_outcome_element(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_cells_for_control_outcome_element(list_of_cells_for_control_outcome_element_t * x) {
  if (NULL != x) {
    if (NULL != x->cell_global_id) {
      cJSON_Deletecell_global_id(x->cell_global_id);
    }
    if (NULL != x->ran_configuration_structures_accepted_list) {
      ran_configuration_structures_accepted_list_element_t * x1 = list_get_head(x->ran_configuration_structures_accepted_list);
      while (NULL != x1) {
        cJSON_Deleteran_configuration_structures_accepted_list_element(x1);
        x1 = list_get_next(x->ran_configuration_structures_accepted_list);
      }
      list_release(x->ran_configuration_structures_accepted_list);
    }
    if (NULL != x->ran_configuration_structures_failed_list) {
      ran_configuration_structures_failed_list_element_t * x1 = list_get_head(x->ran_configuration_structures_failed_list);
      while (NULL != x1) {
        cJSON_Deleteran_configuration_structures_failed_list_element(x1);
        x1 = list_get_next(x->ran_configuration_structures_failed_list);
      }
      list_release(x->ran_configuration_structures_failed_list);
    }
    cJSON_free(x);
  }
}

control_outcome_format_json_t * cJSON_Parsecontrol_outcome_format(const char * s) {
  control_outcome_format_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getcontrol_outcome_formatValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

control_outcome_format_json_t * cJSON_Getcontrol_outcome_formatValue(const cJSON * j) {
  control_outcome_format_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(control_outcome_format_json_t)))) {
      memset(x, 0, sizeof(control_outcome_format_json_t));
      if (cJSON_HasObjectItem(j, "ranConfigurationStructuresAcceptedList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructuresAcceptedList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getran_configuration_structures_accepted_list_elementValue(e1), sizeof(ran_configuration_structures_accepted_list_element_t *));
          }
          x->ran_configuration_structures_accepted_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructuresFailedList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructuresFailedList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getran_configuration_structures_failed_list_elementValue(e1), sizeof(ran_configuration_structures_failed_list_element_t *));
          }
          x->ran_configuration_structures_failed_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "receivedTimestamp")) {
        x->received_timestamp = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "receivedTimestamp")));
      }
      if (cJSON_HasObjectItem(j, "listOfCellsForControlOutcome")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfCellsForControlOutcome");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_cells_for_control_outcome_elementValue(e1), sizeof(list_of_cells_for_control_outcome_element_t *));
          }
          x->list_of_cells_for_control_outcome = x1;
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createcontrol_outcome_format(const control_outcome_format_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->ran_configuration_structures_accepted_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "ranConfigurationStructuresAcceptedList");
        if (NULL != j1) {
          ran_configuration_structures_accepted_list_element_t * x1 = list_get_head(x->ran_configuration_structures_accepted_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createran_configuration_structures_accepted_list_element(x1));
            x1 = list_get_next(x->ran_configuration_structures_accepted_list);
          }
        }
      }
      if (NULL != x->ran_configuration_structures_failed_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "ranConfigurationStructuresFailedList");
        if (NULL != j1) {
          ran_configuration_structures_failed_list_element_t * x1 = list_get_head(x->ran_configuration_structures_failed_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createran_configuration_structures_failed_list_element(x1));
            x1 = list_get_next(x->ran_configuration_structures_failed_list);
          }
        }
      }
      if (NULL != x->received_timestamp) {
        cJSON_AddStringToObject(j, "receivedTimestamp", x->received_timestamp);
      }
      if (NULL != x->list_of_cells_for_control_outcome) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfCellsForControlOutcome");
        if (NULL != j1) {
          list_of_cells_for_control_outcome_element_t * x1 = list_get_head(x->list_of_cells_for_control_outcome);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_cells_for_control_outcome_element(x1));
            x1 = list_get_next(x->list_of_cells_for_control_outcome);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printcontrol_outcome_format(const control_outcome_format_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createcontrol_outcome_format(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletecontrol_outcome_format(control_outcome_format_json_t * x) {
  if (NULL != x) {
    if (NULL != x->ran_configuration_structures_accepted_list) {
      ran_configuration_structures_accepted_list_element_t * x1 = list_get_head(x->ran_configuration_structures_accepted_list);
      while (NULL != x1) {
        cJSON_Deleteran_configuration_structures_accepted_list_element(x1);
        x1 = list_get_next(x->ran_configuration_structures_accepted_list);
      }
      list_release(x->ran_configuration_structures_accepted_list);
    }
    if (NULL != x->ran_configuration_structures_failed_list) {
      ran_configuration_structures_failed_list_element_t * x1 = list_get_head(x->ran_configuration_structures_failed_list);
      while (NULL != x1) {
        cJSON_Deleteran_configuration_structures_failed_list_element(x1);
        x1 = list_get_next(x->ran_configuration_structures_failed_list);
      }
      list_release(x->ran_configuration_structures_failed_list);
    }
    if (NULL != x->received_timestamp) {
      cJSON_free(x->received_timestamp);
    }
    if (NULL != x->list_of_cells_for_control_outcome) {
      list_of_cells_for_control_outcome_element_t * x1 = list_get_head(x->list_of_cells_for_control_outcome);
      while (NULL != x1) {
        cJSON_Deletelist_of_cells_for_control_outcome_element(x1);
        x1 = list_get_next(x->list_of_cells_for_control_outcome);
      }
      list_release(x->list_of_cells_for_control_outcome);
    }
    cJSON_free(x);
  }
}

ric_control_outcome_json_t * cJSON_Parseric_control_outcome(const char * s) {
  ric_control_outcome_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getric_control_outcomeValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ric_control_outcome_json_t * cJSON_Getric_control_outcomeValue(const cJSON * j) {
  ric_control_outcome_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ric_control_outcome_json_t)))) {
      memset(x, 0, sizeof(ric_control_outcome_json_t));
      if (cJSON_HasObjectItem(j, "controlOutcomeFormat")) {
        x->control_outcome_format = cJSON_Getcontrol_outcome_formatValue(cJSON_GetObjectItemCaseSensitive(j, "controlOutcomeFormat"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createric_control_outcome(const ric_control_outcome_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "controlOutcomeFormat", cJSON_Createcontrol_outcome_format(x->control_outcome_format));
    }
  }
  return j;
}

char * cJSON_Printric_control_outcome(const ric_control_outcome_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createric_control_outcome(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteric_control_outcome(ric_control_outcome_json_t * x) {
  if (NULL != x) {
    if (NULL != x->control_outcome_format) {
      cJSON_Deletecontrol_outcome_format(x->control_outcome_format);
    }
    cJSON_free(x);
  }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
