/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_PrintUnformatted<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include "ric_event_trigger_definition_json.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

list_of_node_level_configuration_structures_for_event_trigger_element_t * cJSON_Parselist_of_node_level_configuration_structures_for_event_trigger_element(const char * s) {
  list_of_node_level_configuration_structures_for_event_trigger_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_node_level_configuration_structures_for_event_trigger_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_node_level_configuration_structures_for_event_trigger_element_t * cJSON_Getlist_of_node_level_configuration_structures_for_event_trigger_elementValue(const cJSON * j) {
  list_of_node_level_configuration_structures_for_event_trigger_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_node_level_configuration_structures_for_event_trigger_element_t)))) {
      memset(x, 0, sizeof(list_of_node_level_configuration_structures_for_event_trigger_element_t));
      if (cJSON_HasObjectItem(j, "listOfAttributes")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfAttributes");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
          }
          x->list_of_attributes = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructureName")) {
        x->ran_configuration_structure_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructureName")));
      }
      else {
        if (NULL != (x->ran_configuration_structure_name = cJSON_malloc(sizeof(char)))) {
          x->ran_configuration_structure_name[0] = '\0';
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_node_level_configuration_structures_for_event_trigger_element(const list_of_node_level_configuration_structures_for_event_trigger_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_attributes) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfAttributes");
        if (NULL != j1) {
          char * x1 = list_get_head(x->list_of_attributes);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
            x1 = list_get_next(x->list_of_attributes);
          }
        }
      }
      if (NULL != x->ran_configuration_structure_name) {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", x->ran_configuration_structure_name);
      }
      else {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", "");
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_node_level_configuration_structures_for_event_trigger_element(const list_of_node_level_configuration_structures_for_event_trigger_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_node_level_configuration_structures_for_event_trigger_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_node_level_configuration_structures_for_event_trigger_element(list_of_node_level_configuration_structures_for_event_trigger_element_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_attributes) {
      char * x1 = list_get_head(x->list_of_attributes);
      while (NULL != x1) {
        cJSON_free(x1);
        x1 = list_get_next(x->list_of_attributes);
      }
      list_release(x->list_of_attributes);
    }
    if (NULL != x->ran_configuration_structure_name) {
      cJSON_free(x->ran_configuration_structure_name);
    }
    cJSON_free(x);
  }
}

list_of_cell_level_configuration_structures_for_event_trigger_element_t * cJSON_Parselist_of_cell_level_configuration_structures_for_event_trigger_element(const char * s) {
  list_of_cell_level_configuration_structures_for_event_trigger_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_cell_level_configuration_structures_for_event_trigger_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_cell_level_configuration_structures_for_event_trigger_element_t * cJSON_Getlist_of_cell_level_configuration_structures_for_event_trigger_elementValue(const cJSON * j) {
  list_of_cell_level_configuration_structures_for_event_trigger_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_cell_level_configuration_structures_for_event_trigger_element_t)))) {
      memset(x, 0, sizeof(list_of_cell_level_configuration_structures_for_event_trigger_element_t));
      if (cJSON_HasObjectItem(j, "cellGlobalId")) {
        x->cell_global_id = cJSON_Getcell_global_idValue(cJSON_GetObjectItemCaseSensitive(j, "cellGlobalId"));
      }
      if (cJSON_HasObjectItem(j, "listOfRANConfigurationStructuresForEventTrigger")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfRANConfigurationStructuresForEventTrigger");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_node_level_configuration_structures_for_event_trigger_elementValue(e1), sizeof(list_of_node_level_configuration_structures_for_event_trigger_element_t *));
          }
          x->list_of_ran_configuration_structures_for_event_trigger = x1;
        }
      }
      else {
        x->list_of_ran_configuration_structures_for_event_trigger = list_create(false, NULL);
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_cell_level_configuration_structures_for_event_trigger_element(const list_of_cell_level_configuration_structures_for_event_trigger_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->cell_global_id) {
        cJSON_AddItemToObject(j, "cellGlobalId", cJSON_Createcell_global_id(x->cell_global_id));
      }
      if (NULL != x->list_of_ran_configuration_structures_for_event_trigger) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfRANConfigurationStructuresForEventTrigger");
        if (NULL != j1) {
          list_of_node_level_configuration_structures_for_event_trigger_element_t * x1 = list_get_head(x->list_of_ran_configuration_structures_for_event_trigger);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_node_level_configuration_structures_for_event_trigger_element(x1));
            x1 = list_get_next(x->list_of_ran_configuration_structures_for_event_trigger);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_cell_level_configuration_structures_for_event_trigger_element(const list_of_cell_level_configuration_structures_for_event_trigger_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_cell_level_configuration_structures_for_event_trigger_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_cell_level_configuration_structures_for_event_trigger_element(list_of_cell_level_configuration_structures_for_event_trigger_element_t * x) {
  if (NULL != x) {
    if (NULL != x->cell_global_id) {
      cJSON_Deletecell_global_id(x->cell_global_id);
    }
    if (NULL != x->list_of_ran_configuration_structures_for_event_trigger) {
      list_of_node_level_configuration_structures_for_event_trigger_element_t * x1 = list_get_head(x->list_of_ran_configuration_structures_for_event_trigger);
      while (NULL != x1) {
        cJSON_Deletelist_of_node_level_configuration_structures_for_event_trigger_element(x1);
        x1 = list_get_next(x->list_of_ran_configuration_structures_for_event_trigger);
      }
      list_release(x->list_of_ran_configuration_structures_for_event_trigger);
    }
    cJSON_free(x);
  }
}

event_trigger_definition_format_json_t * cJSON_Parseevent_trigger_definition_format(const char * s) {
  event_trigger_definition_format_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getevent_trigger_definition_formatValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

event_trigger_definition_format_json_t * cJSON_Getevent_trigger_definition_formatValue(const cJSON * j) {
  event_trigger_definition_format_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(event_trigger_definition_format_json_t)))) {
      memset(x, 0, sizeof(event_trigger_definition_format_json_t));
      if (cJSON_HasObjectItem(j, "listOfNodeLevelConfigurationStructuresForEventTrigger")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfNodeLevelConfigurationStructuresForEventTrigger");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_node_level_configuration_structures_for_event_trigger_elementValue(e1), sizeof(list_of_node_level_configuration_structures_for_event_trigger_element_t *));
          }
          x->list_of_node_level_configuration_structures_for_event_trigger = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "listOfCellLevelConfigurationStructuresForEventTrigger")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfCellLevelConfigurationStructuresForEventTrigger");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_cell_level_configuration_structures_for_event_trigger_elementValue(e1), sizeof(list_of_cell_level_configuration_structures_for_event_trigger_element_t *));
          }
          x->list_of_cell_level_configuration_structures_for_event_trigger = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "period")) {
        if (NULL != (x->period = cJSON_malloc(sizeof(int64_t)))) {
          *x->period = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "period"));
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createevent_trigger_definition_format(const event_trigger_definition_format_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_node_level_configuration_structures_for_event_trigger) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfNodeLevelConfigurationStructuresForEventTrigger");
        if (NULL != j1) {
          list_of_node_level_configuration_structures_for_event_trigger_element_t * x1 = list_get_head(x->list_of_node_level_configuration_structures_for_event_trigger);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_node_level_configuration_structures_for_event_trigger_element(x1));
            x1 = list_get_next(x->list_of_node_level_configuration_structures_for_event_trigger);
          }
        }
      }
      if (NULL != x->list_of_cell_level_configuration_structures_for_event_trigger) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfCellLevelConfigurationStructuresForEventTrigger");
        if (NULL != j1) {
          list_of_cell_level_configuration_structures_for_event_trigger_element_t * x1 = list_get_head(x->list_of_cell_level_configuration_structures_for_event_trigger);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_cell_level_configuration_structures_for_event_trigger_element(x1));
            x1 = list_get_next(x->list_of_cell_level_configuration_structures_for_event_trigger);
          }
        }
      }
      if (NULL != x->period) {
        cJSON_AddNumberToObject(j, "period", *x->period);
      }
    }
  }
  return j;
}

char * cJSON_Printevent_trigger_definition_format(const event_trigger_definition_format_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createevent_trigger_definition_format(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteevent_trigger_definition_format(event_trigger_definition_format_json_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_node_level_configuration_structures_for_event_trigger) {
      list_of_node_level_configuration_structures_for_event_trigger_element_t * x1 = list_get_head(x->list_of_node_level_configuration_structures_for_event_trigger);
      while (NULL != x1) {
        cJSON_Deletelist_of_node_level_configuration_structures_for_event_trigger_element(x1);
        x1 = list_get_next(x->list_of_node_level_configuration_structures_for_event_trigger);
      }
      list_release(x->list_of_node_level_configuration_structures_for_event_trigger);
    }
    if (NULL != x->list_of_cell_level_configuration_structures_for_event_trigger) {
      list_of_cell_level_configuration_structures_for_event_trigger_element_t * x1 = list_get_head(x->list_of_cell_level_configuration_structures_for_event_trigger);
      while (NULL != x1) {
        cJSON_Deletelist_of_cell_level_configuration_structures_for_event_trigger_element(x1);
        x1 = list_get_next(x->list_of_cell_level_configuration_structures_for_event_trigger);
      }
      list_release(x->list_of_cell_level_configuration_structures_for_event_trigger);
    }
    if (NULL != x->period) {
      cJSON_free(x->period);
    }
    cJSON_free(x);
  }
}

ric_event_trigger_definition_json_t * cJSON_Parseric_event_trigger_definition(const char * s) {
  ric_event_trigger_definition_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getric_event_trigger_definitionValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ric_event_trigger_definition_json_t * cJSON_Getric_event_trigger_definitionValue(const cJSON * j) {
  ric_event_trigger_definition_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ric_event_trigger_definition_json_t)))) {
      memset(x, 0, sizeof(ric_event_trigger_definition_json_t));
      if (cJSON_HasObjectItem(j, "eventTriggerDefinitionFormat")) {
        x->event_trigger_definition_format = cJSON_Getevent_trigger_definition_formatValue(cJSON_GetObjectItemCaseSensitive(j, "eventTriggerDefinitionFormat"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createric_event_trigger_definition(const ric_event_trigger_definition_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "eventTriggerDefinitionFormat", cJSON_Createevent_trigger_definition_format(x->event_trigger_definition_format));
    }
  }
  return j;
}

char * cJSON_Printric_event_trigger_definition(const ric_event_trigger_definition_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createric_event_trigger_definition(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteric_event_trigger_definition(ric_event_trigger_definition_json_t * x) {
  if (NULL != x) {
    if (NULL != x->event_trigger_definition_format) {
      cJSON_Deleteevent_trigger_definition_format(x->event_trigger_definition_format);
    }
    cJSON_free(x);
  }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
