/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "ric_control_message_json.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

list_of_configuration_structure_control_element_t * cJSON_Parselist_of_configuration_structure_control_element(const char * s) {
  list_of_configuration_structure_control_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_configuration_structure_control_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_configuration_structure_control_element_t * cJSON_Getlist_of_configuration_structure_control_elementValue(const cJSON * j) {
  list_of_configuration_structure_control_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_configuration_structure_control_element_t)))) {
      memset(x, 0, sizeof(list_of_configuration_structure_control_element_t));
      if (cJSON_HasObjectItem(j, "newValuesOfAttributes")) {
        x->new_values_of_attributes = cJSON_Getvalues_of_attributesValue(cJSON_GetObjectItemCaseSensitive(j, "newValuesOfAttributes"));
      }
      if (cJSON_HasObjectItem(j, "oldValuesOfAttributes")) {
        x->old_values_of_attributes = cJSON_Getvalues_of_attributesValue(cJSON_GetObjectItemCaseSensitive(j, "oldValuesOfAttributes"));
      }
      if (cJSON_HasObjectItem(j, "ranConfigurationStructureName")) {
        x->ran_configuration_structure_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructureName")));
      }
      else {
        if (NULL != (x->ran_configuration_structure_name = cJSON_malloc(sizeof(char)))) {
          x->ran_configuration_structure_name[0] = '\0';
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_configuration_structure_control_element(const list_of_configuration_structure_control_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "newValuesOfAttributes", cJSON_Createvalues_of_attributes(x->new_values_of_attributes));
      cJSON_AddItemToObject(j, "oldValuesOfAttributes", cJSON_Createvalues_of_attributes(x->old_values_of_attributes));
      if (NULL != x->ran_configuration_structure_name) {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", x->ran_configuration_structure_name);
      }
      else {
        cJSON_AddStringToObject(j, "ranConfigurationStructureName", "");
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_configuration_structure_control_element(const list_of_configuration_structure_control_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_configuration_structure_control_element(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_configuration_structure_control_element(list_of_configuration_structure_control_element_t * x) {
  if (NULL != x) {
    if (NULL != x->new_values_of_attributes) {
      cJSON_Deletevalues_of_attributes(x->new_values_of_attributes);
    }
    if (NULL != x->old_values_of_attributes) {
      cJSON_Deletevalues_of_attributes(x->old_values_of_attributes);
    }
    if (NULL != x->ran_configuration_structure_name) {
      cJSON_free(x->ran_configuration_structure_name);
    }
    cJSON_free(x);
  }
}

list_of_cells_controlled_element_t * cJSON_Parselist_of_cells_controlled_element(const char * s) {
  list_of_cells_controlled_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getlist_of_cells_controlled_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

list_of_cells_controlled_element_t * cJSON_Getlist_of_cells_controlled_elementValue(const cJSON * j) {
  list_of_cells_controlled_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(list_of_cells_controlled_element_t)))) {
      memset(x, 0, sizeof(list_of_cells_controlled_element_t));
      if (cJSON_HasObjectItem(j, "cellGlobalId")) {
        x->cell_global_id = cJSON_Getcell_global_idValue(cJSON_GetObjectItemCaseSensitive(j, "cellGlobalId"));
      }
      if (cJSON_HasObjectItem(j, "listOfConfigurationStructures")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfConfigurationStructures");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_configuration_structure_control_elementValue(e1), sizeof(list_of_configuration_structure_control_element_t *));
          }
          x->list_of_configuration_structures = x1;
        }
      }
      else {
        x->list_of_configuration_structures = list_create(false, NULL);
      }
    }
  }
  return x;
}

cJSON * cJSON_Createlist_of_cells_controlled_element(const list_of_cells_controlled_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "cellGlobalId", cJSON_Createcell_global_id(x->cell_global_id));
      if (NULL != x->list_of_configuration_structures) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfConfigurationStructures");
        if (NULL != j1) {
          list_of_configuration_structure_control_element_t * x1 = list_get_head(x->list_of_configuration_structures);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_configuration_structure_control_element(x1));
            x1 = list_get_next(x->list_of_configuration_structures);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printlist_of_cells_controlled_element(const list_of_cells_controlled_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createlist_of_cells_controlled_element(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletelist_of_cells_controlled_element(list_of_cells_controlled_element_t * x) {
  if (NULL != x) {
    if (NULL != x->cell_global_id) {
      cJSON_Deletecell_global_id(x->cell_global_id);
    }
    if (NULL != x->list_of_configuration_structures) {
      list_of_configuration_structure_control_element_t * x1 = list_get_head(x->list_of_configuration_structures);
      while (NULL != x1) {
        cJSON_Deletelist_of_configuration_structure_control_element(x1);
        x1 = list_get_next(x->list_of_configuration_structures);
      }
      list_release(x->list_of_configuration_structures);
    }
    cJSON_free(x);
  }
}

control_message_format_json_t * cJSON_Parsecontrol_message_format(const char * s) {
  control_message_format_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getcontrol_message_formatValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

control_message_format_json_t * cJSON_Getcontrol_message_formatValue(const cJSON * j) {
  control_message_format_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(control_message_format_json_t)))) {
      memset(x, 0, sizeof(control_message_format_json_t));
      if (cJSON_HasObjectItem(j, "listOfConfigurationStructures")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfConfigurationStructures");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_configuration_structure_control_elementValue(e1), sizeof(list_of_configuration_structure_control_element_t *));
          }
          x->list_of_configuration_structures = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "listOfCellsControlled")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "listOfCellsControlled");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getlist_of_cells_controlled_elementValue(e1), sizeof(list_of_cells_controlled_element_t *));
          }
          x->list_of_cells_controlled = x1;
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createcontrol_message_format(const control_message_format_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->list_of_configuration_structures) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfConfigurationStructures");
        if (NULL != j1) {
          list_of_configuration_structure_control_element_t * x1 = list_get_head(x->list_of_configuration_structures);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_configuration_structure_control_element(x1));
            x1 = list_get_next(x->list_of_configuration_structures);
          }
        }
      }
      if (NULL != x->list_of_cells_controlled) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "listOfCellsControlled");
        if (NULL != j1) {
          list_of_cells_controlled_element_t * x1 = list_get_head(x->list_of_cells_controlled);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createlist_of_cells_controlled_element(x1));
            x1 = list_get_next(x->list_of_cells_controlled);
          }
        }
      }
    }
  }
  return j;
}

char * cJSON_Printcontrol_message_format(const control_message_format_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createcontrol_message_format(x);
    if (NULL != j) {
      s = cJSON_Print(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletecontrol_message_format(control_message_format_json_t * x) {
  if (NULL != x) {
    if (NULL != x->list_of_configuration_structures) {
      list_of_configuration_structure_control_element_t * x1 = list_get_head(x->list_of_configuration_structures);
      while (NULL != x1) {
        cJSON_Deletelist_of_configuration_structure_control_element(x1);
        x1 = list_get_next(x->list_of_configuration_structures);
      }
      list_release(x->list_of_configuration_structures);
    }
    if (NULL != x->list_of_cells_controlled) {
      list_of_cells_controlled_element_t * x1 = list_get_head(x->list_of_cells_controlled);
      while (NULL != x1) {
        cJSON_Deletelist_of_cells_controlled_element(x1);
        x1 = list_get_next(x->list_of_cells_controlled);
      }
      list_release(x->list_of_cells_controlled);
    }
    cJSON_free(x);
  }
}

ric_control_message_json_t * cJSON_Parseric_control_message(const char * s) {
  ric_control_message_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getric_control_messageValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ric_control_message_json_t * cJSON_Getric_control_messageValue(const cJSON * j) {
  ric_control_message_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ric_control_message_json_t)))) {
      memset(x, 0, sizeof(ric_control_message_json_t));
      if (cJSON_HasObjectItem(j, "controlMessageFormat")) {
        x->control_message_format = cJSON_Getcontrol_message_formatValue(cJSON_GetObjectItemCaseSensitive(j, "controlMessageFormat"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createric_control_message(const ric_control_message_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "controlMessageFormat", cJSON_Createcontrol_message_format(x->control_message_format));
    }
  }
  return j;
}

char * cJSON_Printric_control_message(const ric_control_message_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createric_control_message(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteric_control_message(ric_control_message_json_t * x) {
  if (NULL != x) {
    if (NULL != x->control_message_format) {
      cJSON_Deletecontrol_message_format(x->control_message_format);
    }
    cJSON_free(x);
  }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
