/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <string.h>
#include <assert.h>
#include "values_of_attributes_json.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif


#ifdef __cplusplus
}
#endif


change_type_e cJSON_Getchange_typeValue(const cJSON * j) {
  change_type_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "addition")) x = CHANGE_TYPE_ADDITION;
    else if (!strcmp(cJSON_GetStringValue(j), "deletion")) x = CHANGE_TYPE_DELETION;
    else if (!strcmp(cJSON_GetStringValue(j), "modification")) x = CHANGE_TYPE_MODIFICATION;
    else if (!strcmp(cJSON_GetStringValue(j), "none")) x = CHANGE_TYPE_NONE;
  }
  return x;
}

cJSON * cJSON_Createchange_type(const change_type_e x) {
  cJSON * j = NULL;
  switch (x) {
    case CHANGE_TYPE_ADDITION: j = cJSON_CreateString("addition"); break;
    case CHANGE_TYPE_DELETION: j = cJSON_CreateString("deletion"); break;
    case CHANGE_TYPE_MODIFICATION: j = cJSON_CreateString("modification"); break;
    case CHANGE_TYPE_NONE: j = cJSON_CreateString("none"); break;
    default:
      assert(0 != 0 && "Unknown change type");
  }
  return j;
}

administrative_state_e cJSON_Getadministrative_stateValue(const cJSON * j) {
  administrative_state_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "LOCKED")) x = LOCKED_ADMINISTRATIVE_STATE;
    else if (!strcmp(cJSON_GetStringValue(j), "SHUTTINGDOWN")) x = SHUTTING_ADMINISTRATIVE_STATE;
    else if (!strcmp(cJSON_GetStringValue(j), "UNLOCKED")) x = UNLOCKED_ADMINISTRATIVE_STATE;
  }
  return x;
}

cJSON * cJSON_Createadministrative_state(const administrative_state_e x) {
  cJSON * j = NULL;
  switch (x) {
    case LOCKED_ADMINISTRATIVE_STATE: j = cJSON_CreateString("LOCKED"); break;
    case SHUTTING_ADMINISTRATIVE_STATE: j = cJSON_CreateString("SHUTTINGDOWN"); break;
    case UNLOCKED_ADMINISTRATIVE_STATE: j = cJSON_CreateString("UNLOCKED"); break;
    default:
      break;
  }
  return j;
}

bwp_context_e cJSON_Getbwp_contextValue(const cJSON * j) {
  bwp_context_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "DL")) x = DL_BWP_CONTEXT;
    else if (!strcmp(cJSON_GetStringValue(j), "SUL")) x = SUL_BWP_CONTEXT;
    else if (!strcmp(cJSON_GetStringValue(j), "UL")) x = UL_BWP_CONTEXT;
  }
  return x;
}

cJSON * cJSON_Createbwp_context(const bwp_context_e x) {
  cJSON * j = NULL;
  switch (x) {
    case DL_BWP_CONTEXT: j = cJSON_CreateString("DL"); break;
    case SUL_BWP_CONTEXT: j = cJSON_CreateString("SUL"); break;
    case UL_BWP_CONTEXT: j = cJSON_CreateString("UL"); break;
    default:
      break;
  }
  return j;
}

cyclic_prefix_e cJSON_Getcyclic_prefixValue(const cJSON * j) {
  cyclic_prefix_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "120")) x = CYCLIC_PREFIX_120;
    else if (!strcmp(cJSON_GetStringValue(j), "15")) x = CYCLIC_PREFIX_15;
    else if (!strcmp(cJSON_GetStringValue(j), "30")) x = CYCLIC_PREFIX_30;
    else if (!strcmp(cJSON_GetStringValue(j), "60")) x = CYCLIC_PREFIX_60;
  }
  return x;
}

cJSON * cJSON_Createcyclic_prefix(const cyclic_prefix_e x) {
  cJSON * j = NULL;
  switch (x) {
    case CYCLIC_PREFIX_120: j = cJSON_CreateString("120"); break;
    case CYCLIC_PREFIX_15: j = cJSON_CreateString("15"); break;
    case CYCLIC_PREFIX_30: j = cJSON_CreateString("30"); break;
    case CYCLIC_PREFIX_60: j = cJSON_CreateString("60"); break;
    default:
      break;
  }
  return j;
}

is_initial_bwp_e cJSON_Getis_initial_bwpValue(const cJSON * j) {
  is_initial_bwp_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "INITIAL")) x = INITIAL_IS_INITIAL_BWP;
    else if (!strcmp(cJSON_GetStringValue(j), "OTHER")) x = OTHER_IS_INITIAL_BWP;
    else if (!strcmp(cJSON_GetStringValue(j), "SUL")) x = SUL_IS_INITIAL_BWP;
  }
  return x;
}

cJSON * cJSON_Createis_initial_bwp(const is_initial_bwp_e x) {
  cJSON * j = NULL;
  switch (x) {
    case INITIAL_IS_INITIAL_BWP: j = cJSON_CreateString("INITIAL"); break;
    case OTHER_IS_INITIAL_BWP: j = cJSON_CreateString("OTHER"); break;
    case SUL_IS_INITIAL_BWP: j = cJSON_CreateString("SUL"); break;
    default:
      break;
  }
  return j;
}

cell_state_e cJSON_Getcell_stateValue(const cJSON * j) {
  cell_state_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "ACTIVE")) x = ACTIVE_CELL_STATE;
    else if (!strcmp(cJSON_GetStringValue(j), "IDLE")) x = IDLE_CELL_STATE;
    else if (!strcmp(cJSON_GetStringValue(j), "INACTIVE")) x = INACTIVE_CELL_STATE;
  }
  return x;
}

cJSON * cJSON_Createcell_state(const cell_state_e x) {
  cJSON * j = NULL;
  switch (x) {
    case ACTIVE_CELL_STATE: j = cJSON_CreateString("ACTIVE"); break;
    case IDLE_CELL_STATE: j = cJSON_CreateString("IDLE"); break;
    case INACTIVE_CELL_STATE: j = cJSON_CreateString("INACTIVE"); break;
    default:
      break;
  }
  return j;
}

energy_saving_control_e cJSON_Getenergy_saving_controlValue(const cJSON * j) {
  energy_saving_control_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "toBeEnergySaving")) x = TO_BE_ENERGY_SAVING_CONTROL;
    else if (!strcmp(cJSON_GetStringValue(j), "toBeNotEnergySaving")) x = TO_BE_NOT_ENERGY_SAVING_CONTROL;
  }
  return x;
}

cJSON * cJSON_Createenergy_saving_control(const energy_saving_control_e x) {
  cJSON * j = NULL;
  switch (x) {
    case TO_BE_ENERGY_SAVING_CONTROL: j = cJSON_CreateString("toBeEnergySaving"); break;
    case TO_BE_NOT_ENERGY_SAVING_CONTROL: j = cJSON_CreateString("toBeNotEnergySaving"); break;
    default:
      break;
  }
  return j;
}

energy_saving_state_e cJSON_Getenergy_saving_stateValue(const cJSON * j) {
  energy_saving_state_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "isEnergySaving")) x = IS_ENERGY_SAVING_STATE;
    else if (!strcmp(cJSON_GetStringValue(j), "isNotEnergySaving")) x = IS_NOT_ENERGY_SAVING_STATE;
  }
  return x;
}

cJSON * cJSON_Createenergy_saving_state(const energy_saving_state_e x) {
  cJSON * j = NULL;
  switch (x) {
    case IS_ENERGY_SAVING_STATE: j = cJSON_CreateString("isEnergySaving"); break;
    case IS_NOT_ENERGY_SAVING_STATE: j = cJSON_CreateString("isNotEnergySaving"); break;
    default:
      break;
  }
  return j;
}

operational_state_e cJSON_Getoperational_stateValue(const cJSON * j) {
  operational_state_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "DISABLED")) x = DISABLED_OPERATIONAL_STATE;
    else if (!strcmp(cJSON_GetStringValue(j), "ENABLED")) x = ENABLED_OPERATIONAL_STATE;
  }
  return x;
}

cJSON * cJSON_Createoperational_state(const operational_state_e x) {
  cJSON * j = NULL;
  switch (x) {
    case DISABLED_OPERATIONAL_STATE: j = cJSON_CreateString("DISABLED"); break;
    case ENABLED_OPERATIONAL_STATE: j = cJSON_CreateString("ENABLED"); break;
    default:
      break;
  }
  return j;
}

resource_type_e cJSON_Getresource_typeValue(const cJSON * j) {
  resource_type_e x = 0;
  if (NULL != j) {
    if (!strcmp(cJSON_GetStringValue(j), "DRB")) x = DRB_RESOURCE_TYPE;
    else if (!strcmp(cJSON_GetStringValue(j), "PRB_DL")) x = PRB_DL_RESOURCE_TYPE;
    else if (!strcmp(cJSON_GetStringValue(j), "PRB_UL")) x = PRB_UL_RESOURCE_TYPE;
    else if (!strcmp(cJSON_GetStringValue(j), "RRC")) x = RRC_RESOURCE_TYPE;
  }
  return x;
}

cJSON * cJSON_Createresource_type(const resource_type_e x) {
  cJSON * j = NULL;
  switch (x) {
    case DRB_RESOURCE_TYPE: j = cJSON_CreateString("DRB"); break;
    case PRB_DL_RESOURCE_TYPE: j = cJSON_CreateString("PRB_DL"); break;
    case PRB_UL_RESOURCE_TYPE: j = cJSON_CreateString("PRB_UL"); break;
    case RRC_RESOURCE_TYPE: j = cJSON_CreateString("RRC"); break;
    default:
      assert("Not supported current resource type");
  }
  return j;
}

bwp_list_element_t * cJSON_Parsebwp_list_element(const char * s) {
  bwp_list_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getbwp_list_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

bwp_list_element_t * cJSON_Getbwp_list_elementValue(const cJSON * j) {
  bwp_list_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(bwp_list_element_t)))) {
      memset(x, 0, sizeof(bwp_list_element_t));
      if (cJSON_HasObjectItem(j, "bwpContext")) {
        if (NULL != (x->bwp_context = cJSON_malloc(sizeof(bwp_context_e)))) {
          *x->bwp_context = cJSON_Getbwp_contextValue(cJSON_GetObjectItemCaseSensitive(j, "bwpContext"));
        }
      }
      if (cJSON_HasObjectItem(j, "cyclicPrefix")) {
        if (NULL != (x->cyclic_prefix = cJSON_malloc(sizeof(cyclic_prefix_e)))) {
          *x->cyclic_prefix = cJSON_Getcyclic_prefixValue(cJSON_GetObjectItemCaseSensitive(j, "cyclicPrefix"));
        }
      }
      if (cJSON_HasObjectItem(j, "isInitialBwp")) {
        if (NULL != (x->is_initial_bwp = cJSON_malloc(sizeof(is_initial_bwp_e)))) {
          *x->is_initial_bwp = cJSON_Getis_initial_bwpValue(cJSON_GetObjectItemCaseSensitive(j, "isInitialBwp"));
        }
      }
      if (cJSON_HasObjectItem(j, "numberOfRBs")) {
        if (NULL != (x->number_of_r_bs = cJSON_malloc(sizeof(int64_t)))) {
          *x->number_of_r_bs = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "numberOfRBs"));
        }
      }
      if (cJSON_HasObjectItem(j, "startRB")) {
        if (NULL != (x->start_rb = cJSON_malloc(sizeof(uint32_t)))) {
          *x->start_rb = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "startRB"));
        }
      }
      if (cJSON_HasObjectItem(j, "subCarrierSpacing")) {
        if (NULL != (x->sub_carrier_spacing = cJSON_malloc(sizeof(int64_t)))) {
          *x->sub_carrier_spacing = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "subCarrierSpacing"));
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createbwp_list_element(const bwp_list_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->bwp_context) {
        cJSON_AddItemToObject(j, "bwpContext", cJSON_Createbwp_context(*x->bwp_context));
      }
      if (NULL != x->cyclic_prefix) {
        cJSON_AddItemToObject(j, "cyclicPrefix", cJSON_Createcyclic_prefix(*x->cyclic_prefix));
      }
      if (NULL != x->is_initial_bwp) {
        cJSON_AddItemToObject(j, "isInitialBwp", cJSON_Createis_initial_bwp(*x->is_initial_bwp));
      }
      if (NULL != x->number_of_r_bs) {
        cJSON_AddNumberToObject(j, "numberOfRBs", *x->number_of_r_bs);
      }
      if (NULL != x->start_rb) {
        cJSON_AddNumberToObject(j, "startRB", *x->start_rb);
      }
      if (NULL != x->sub_carrier_spacing) {
        cJSON_AddNumberToObject(j, "subCarrierSpacing", *x->sub_carrier_spacing);
      }
    }
  }
  return j;
}

char * cJSON_Printbwp_list_element(const bwp_list_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createbwp_list_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletebwp_list_element(bwp_list_element_t * x) {
  if (NULL != x) {
    if (NULL != x->bwp_context) {
      cJSON_free(x->bwp_context);
    }
    if (NULL != x->cyclic_prefix) {
      cJSON_free(x->cyclic_prefix);
    }
    if (NULL != x->is_initial_bwp) {
      cJSON_free(x->is_initial_bwp);
    }
    if (NULL != x->number_of_r_bs) {
      cJSON_free(x->number_of_r_bs);
    }
    if (NULL != x->start_rb) {
      cJSON_free(x->start_rb);
    }
    if (NULL != x->sub_carrier_spacing) {
      cJSON_free(x->sub_carrier_spacing);
    }
    cJSON_free(x);
  }
}

snssai_json_t * cJSON_Parsesnssai(const char * s) {
  snssai_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_GetsnssaiValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

snssai_json_t * cJSON_GetsnssaiValue(const cJSON * j) {
  snssai_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(snssai_json_t)))) {
      memset(x, 0, sizeof(snssai_json_t));
      if (cJSON_HasObjectItem(j, "sd")) {
        x->sd = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "sd")));
      }
      if (cJSON_HasObjectItem(j, "sst")) {
        if (NULL != (x->sst = cJSON_malloc(sizeof(uint8_t)))) {
          *x->sst = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "sst"));
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createsnssai(const snssai_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->sd) {
        cJSON_AddStringToObject(j, "sd", x->sd);
      }
      if (NULL != x->sst) {
        cJSON_AddNumberToObject(j, "sst", *x->sst);
      }
    }
  }
  return j;
}

char * cJSON_Printsnssai(const snssai_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createsnssai(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletesnssai(snssai_json_t * x) {
  if (NULL != x) {
    if (NULL != x->sd) {
      cJSON_free(x->sd);
    }
    if (NULL != x->sst) {
      cJSON_free(x->sst);
    }
    cJSON_free(x);
  }
}

partition_flow_list_element_t * cJSON_Parsepartition_flow_list_element(const char * s) {
  partition_flow_list_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getpartition_flow_list_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

partition_flow_list_element_t * cJSON_Getpartition_flow_list_elementValue(const cJSON * j) {
  partition_flow_list_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(partition_flow_list_element_t)))) {
      memset(x, 0, sizeof(partition_flow_list_element_t));
      if (cJSON_HasObjectItem(j, "5qiList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "5qiList");
          cJSON_ArrayForEach(e1, j1) {
            int64_t * tmp = cJSON_malloc(sizeof(int64_t));
            if (NULL != tmp) {
              * tmp = cJSON_GetNumberValue(e1);
              list_add_tail(x1, tmp, sizeof(int64_t *));
            }
          }
          x->the_5_qi_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "plmnId")) {
        x->plmn_id = cJSON_Getplmn_idValue(cJSON_GetObjectItemCaseSensitive(j, "plmnId"));
      }
      if (cJSON_HasObjectItem(j, "snssai")) {
        x->snssai = cJSON_GetsnssaiValue(cJSON_GetObjectItemCaseSensitive(j, "snssai"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createpartition_flow_list_element(const partition_flow_list_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->the_5_qi_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "5qiList");
        if (NULL != j1) {
          int64_t * x1 = list_get_head(x->the_5_qi_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_CreateNumber(*x1));
            x1 = list_get_next(x->the_5_qi_list);
          }
        }
      }
      if (NULL != x->plmn_id) {
        cJSON_AddItemToObject(j, "plmnId", cJSON_Createplmn_id(x->plmn_id));
      }
      if (NULL != x->snssai) {
        cJSON_AddItemToObject(j, "snssai", cJSON_Createsnssai(x->snssai));
      }
    }
  }
  return j;
}

char * cJSON_Printpartition_flow_list_element(const partition_flow_list_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createpartition_flow_list_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletepartition_flow_list_element(partition_flow_list_element_t * x) {
  if (NULL != x) {
    if (NULL != x->the_5_qi_list) {
      int64_t * x1 = list_get_head(x->the_5_qi_list);
      while (NULL != x1) {
        cJSON_free(x1);
        x1 = list_get_next(x->the_5_qi_list);
      }
      list_release(x->the_5_qi_list);
    }
    if (NULL != x->plmn_id) {
      cJSON_Deleteplmn_id(x->plmn_id);
    }
    if (NULL != x->snssai) {
      cJSON_Deletesnssai(x->snssai);
    }
    cJSON_free(x);
  }
}

partition_list_element_t * cJSON_Parsepartition_list_element(const char * s) {
  partition_list_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getpartition_list_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

partition_list_element_t * cJSON_Getpartition_list_elementValue(const cJSON * j) {
  partition_list_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(partition_list_element_t)))) {
      memset(x, 0, sizeof(partition_list_element_t));
      if (cJSON_HasObjectItem(j, "partitionFlowList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "partitionFlowList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getpartition_flow_list_elementValue(e1), sizeof(partition_flow_list_element_t *));
          }
          x->partition_flow_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "pNumberOfRBs")) {
        if (NULL != (x->p_number_of_r_bs = cJSON_malloc(sizeof(uint32_t)))) {
          *x->p_number_of_r_bs = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "pNumberOfRBs"));
        }
      }
      if (cJSON_HasObjectItem(j, "pOffsetToPointA")) {
        if (NULL != (x->p_offset_to_point_a = cJSON_malloc(sizeof(int64_t)))) {
          *x->p_offset_to_point_a = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "pOffsetToPointA"));
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createpartition_list_element(const partition_list_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->partition_flow_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "partitionFlowList");
        if (NULL != j1) {
          partition_flow_list_element_t * x1 = list_get_head(x->partition_flow_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createpartition_flow_list_element(x1));
            x1 = list_get_next(x->partition_flow_list);
          }
        }
      }
      if (NULL != x->p_number_of_r_bs) {
        cJSON_AddNumberToObject(j, "pNumberOfRBs", *x->p_number_of_r_bs);
      }
      if (NULL != x->p_offset_to_point_a) {
        cJSON_AddNumberToObject(j, "pOffsetToPointA", *x->p_offset_to_point_a);
      }
    }
  }
  return j;
}

char * cJSON_Printpartition_list_element(const partition_list_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createpartition_list_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletepartition_list_element(partition_list_element_t * x) {
  if (NULL != x) {
    if (NULL != x->partition_flow_list) {
      partition_flow_list_element_t * x1 = list_get_head(x->partition_flow_list);
      while (NULL != x1) {
        cJSON_Deletepartition_flow_list_element(x1);
        x1 = list_get_next(x->partition_flow_list);
      }
      list_release(x->partition_flow_list);
    }
    if (NULL != x->p_number_of_r_bs) {
      cJSON_free(x->p_number_of_r_bs);
    }
    if (NULL != x->p_offset_to_point_a) {
      cJSON_free(x->p_offset_to_point_a);
    }
    cJSON_free(x);
  }
}

plmn_info_list_element_t * cJSON_Parseplmn_info_list_element(const char * s) {
  plmn_info_list_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getplmn_info_list_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

plmn_info_list_element_t * cJSON_Getplmn_info_list_elementValue(const cJSON * j) {
  plmn_info_list_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(plmn_info_list_element_t)))) {
      memset(x, 0, sizeof(plmn_info_list_element_t));
      if (cJSON_HasObjectItem(j, "plmnId")) {
        x->plmn_id = cJSON_Getplmn_idValue(cJSON_GetObjectItemCaseSensitive(j, "plmnId"));
      }
      if (cJSON_HasObjectItem(j, "snssai")) {
        x->snssai = cJSON_GetsnssaiValue(cJSON_GetObjectItemCaseSensitive(j, "snssai"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createplmn_info_list_element(const plmn_info_list_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->plmn_id) {
        cJSON_AddItemToObject(j, "plmnId", cJSON_Createplmn_id(x->plmn_id));
      }
      if (NULL != x->snssai) {
        cJSON_AddItemToObject(j, "snssai", cJSON_Createsnssai(x->snssai));
      }
    }
  }
  return j;
}

char * cJSON_Printplmn_info_list_element(const plmn_info_list_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createplmn_info_list_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteplmn_info_list_element(plmn_info_list_element_t * x) {
  if (NULL != x) {
    if (NULL != x->plmn_id) {
      cJSON_Deleteplmn_id(x->plmn_id);
    }
    if (NULL != x->snssai) {
      cJSON_Deletesnssai(x->snssai);
    }
    cJSON_free(x);
  }
}

r_rm_policy_member_list_element_t * cJSON_Parser_rm_policy_member_list_element(const char * s) {
  r_rm_policy_member_list_element_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getr_rm_policy_member_list_elementValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

r_rm_policy_member_list_element_t * cJSON_Getr_rm_policy_member_list_elementValue(const cJSON * j) {
  r_rm_policy_member_list_element_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(r_rm_policy_member_list_element_t)))) {
      memset(x, 0, sizeof(r_rm_policy_member_list_element_t));
      if (cJSON_HasObjectItem(j, "plmnId")) {
        x->plmn_id = cJSON_Getplmn_idValue(cJSON_GetObjectItemCaseSensitive(j, "plmnId"));
      }
      if (cJSON_HasObjectItem(j, "snssai")) {
        x->snssai = cJSON_GetsnssaiValue(cJSON_GetObjectItemCaseSensitive(j, "snssai"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Creater_rm_policy_member_list_element(const r_rm_policy_member_list_element_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->plmn_id) {
        cJSON_AddItemToObject(j, "plmnId", cJSON_Createplmn_id(x->plmn_id));
      }
      if (NULL != x->snssai) {
        cJSON_AddItemToObject(j, "snssai", cJSON_Createsnssai(x->snssai));
      }
    }
  }
  return j;
}

char * cJSON_Printr_rm_policy_member_list_element(const r_rm_policy_member_list_element_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Creater_rm_policy_member_list_element(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleter_rm_policy_member_list_element(r_rm_policy_member_list_element_t * x) {
  if (NULL != x) {
    if (NULL != x->plmn_id) {
      cJSON_Deleteplmn_id(x->plmn_id);
    }
    if (NULL != x->snssai) {
      cJSON_Deletesnssai(x->snssai);
    }
    cJSON_free(x);
  }
}

ran_configuration_structure_json_t * cJSON_Parseran_configuration_structure(const char * s) {
  ran_configuration_structure_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getran_configuration_structureValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

ran_configuration_structure_json_t * cJSON_Getran_configuration_structureValue(const cJSON * j) {
  ran_configuration_structure_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(ran_configuration_structure_json_t)))) {
      memset(x, 0, sizeof(ran_configuration_structure_json_t));
      if (cJSON_HasObjectItem(j, "gnbCuName")) {
        x->gnb_cu_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "gnbCuName")));
      }
      if (cJSON_HasObjectItem(j, "gnbId")) {
        if (NULL != (x->gnb_id = cJSON_malloc(sizeof(uint32_t)))) {
          *x->gnb_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "gnbId"));
        }
      }
      if (cJSON_HasObjectItem(j, "gnbIdLength")) {
        if (NULL != (x->gnb_id_length = cJSON_malloc(sizeof(uint8_t)))) {
          *x->gnb_id_length = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "gnbIdLength"));
        }
      }
      if (cJSON_HasObjectItem(j, "plmnId")) {
        x->plmn_id = cJSON_Getplmn_idValue(cJSON_GetObjectItemCaseSensitive(j, "plmnId"));
      }
      if (cJSON_HasObjectItem(j, "x2AllowList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "x2AllowList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
          }
          x->x2_allow_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "x2BlockList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "x2BlockList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
          }
          x->x2_block_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "x2HOBlockList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "x2HOBlockList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
          }
          x->x2_ho_block_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "xnAllowList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "xnAllowList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
          }
          x->xn_allow_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "xnBlockList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "xnBlockList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
          }
          x->xn_block_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "xnHOBlockList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "xnHOBlockList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
          }
          x->xn_ho_block_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "gnbCuUpId")) {
        if (NULL != (x->gnb_cu_up_id = cJSON_malloc(sizeof(uint64_t)))) {
          *x->gnb_cu_up_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "gnbCuUpId"));
        }
      }
      if (cJSON_HasObjectItem(j, "plmnInfoList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "plmnInfoList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getplmn_info_list_elementValue(e1), sizeof(plmn_info_list_element_t *));
          }
          x->plmn_info_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "gnbDuId")) {
        if (NULL != (x->gnb_du_id = cJSON_malloc(sizeof(uint64_t)))) {
          *x->gnb_du_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "gnbDuId"));
        }
      }
      if (cJSON_HasObjectItem(j, "gnbDuName")) {
        x->gnb_du_name = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "gnbDuName")));
      }
      if (cJSON_HasObjectItem(j, "cellLocalId")) {
        if (NULL != (x->cell_local_id = cJSON_malloc(sizeof(uint32_t)))) {
          *x->cell_local_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "cellLocalId"));
        }
      }
      if (cJSON_HasObjectItem(j, "administrativeState")) {
        if (NULL != (x->administrative_state = cJSON_malloc(sizeof(administrative_state_e)))) {
          *x->administrative_state = cJSON_Getadministrative_stateValue(cJSON_GetObjectItemCaseSensitive(j, "administrativeState"));
        }
      }
      if (cJSON_HasObjectItem(j, "arfcnDL")) {
        if (NULL != (x->arfcn_dl = cJSON_malloc(sizeof(int64_t)))) {
          *x->arfcn_dl = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "arfcnDL"));
        }
      }
      if (cJSON_HasObjectItem(j, "arfcnSUL")) {
        if (NULL != (x->arfcn_sul = cJSON_malloc(sizeof(int64_t)))) {
          *x->arfcn_sul = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "arfcnSUL"));
        }
      }
      if (cJSON_HasObjectItem(j, "arfcnUL")) {
        if (NULL != (x->arfcn_ul = cJSON_malloc(sizeof(int64_t)))) {
          *x->arfcn_ul = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "arfcnUL"));
        }
      }
      if (cJSON_HasObjectItem(j, "bSChannelBwDL")) {
        if (NULL != (x->b_s_channel_bw_dl = cJSON_malloc(sizeof(int64_t)))) {
          *x->b_s_channel_bw_dl = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "bSChannelBwDL"));
        }
      }
      if (cJSON_HasObjectItem(j, "bSChannelBwSUL")) {
        if (NULL != (x->b_s_channel_bw_sul = cJSON_malloc(sizeof(int64_t)))) {
          *x->b_s_channel_bw_sul = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "bSChannelBwSUL"));
        }
      }
      if (cJSON_HasObjectItem(j, "bSChannelBwUL")) {
        if (NULL != (x->b_s_channel_bw_ul = cJSON_malloc(sizeof(int64_t)))) {
          *x->b_s_channel_bw_ul = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "bSChannelBwUL"));
        }
      }
      if (cJSON_HasObjectItem(j, "bwpList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "bwpList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getbwp_list_elementValue(e1), sizeof(bwp_list_element_t *));
          }
          x->bwp_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "cellState")) {
        if (NULL != (x->cell_state = cJSON_malloc(sizeof(cell_state_e)))) {
          *x->cell_state = cJSON_Getcell_stateValue(cJSON_GetObjectItemCaseSensitive(j, "cellState"));
        }
      }
      if (cJSON_HasObjectItem(j, "nrPci")) {
        if (NULL != (x->nr_pci = cJSON_malloc(sizeof(int64_t)))) {
          *x->nr_pci = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "nrPci"));
        }
      }
      if (cJSON_HasObjectItem(j, "nrTac")) {
        if (NULL != (x->nr_tac = cJSON_malloc(sizeof(int64_t)))) {
          *x->nr_tac = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "nrTac"));
        }
      }
      if (cJSON_HasObjectItem(j, "operationalState")) {
        if (NULL != (x->operational_state = cJSON_malloc(sizeof(operational_state_e)))) {
          *x->operational_state = cJSON_Getoperational_stateValue(cJSON_GetObjectItemCaseSensitive(j, "operationalState"));
        }
      }
      if (cJSON_HasObjectItem(j, "partitionList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "partitionList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getpartition_list_elementValue(e1), sizeof(partition_list_element_t *));
          }
          x->partition_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "ssbDuration")) {
        if (NULL != (x->ssb_duration = cJSON_malloc(sizeof(int64_t)))) {
          *x->ssb_duration = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ssbDuration"));
        }
      }
      if (cJSON_HasObjectItem(j, "ssbFrequency")) {
        if (NULL != (x->ssb_frequency = cJSON_malloc(sizeof(int64_t)))) {
          *x->ssb_frequency = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ssbFrequency"));
        }
      }
      if (cJSON_HasObjectItem(j, "ssbOffset")) {
        if (NULL != (x->ssb_offset = cJSON_malloc(sizeof(int64_t)))) {
          *x->ssb_offset = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ssbOffset"));
        }
      }
      if (cJSON_HasObjectItem(j, "ssbPeriodicity")) {
        if (NULL != (x->ssb_periodicity = cJSON_malloc(sizeof(int64_t)))) {
          *x->ssb_periodicity = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ssbPeriodicity"));
        }
      }
      if (cJSON_HasObjectItem(j, "ssbSubCarrierSpacing")) {
        if (NULL != (x->ssb_sub_carrier_spacing = cJSON_malloc(sizeof(int64_t)))) {
          *x->ssb_sub_carrier_spacing = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ssbSubCarrierSpacing"));
        }
      }
      if (cJSON_HasObjectItem(j, "resourceType")) {
        if (NULL != (x->resource_type = cJSON_malloc(sizeof(resource_type_e)))) {
          *x->resource_type = cJSON_Getresource_typeValue(cJSON_GetObjectItemCaseSensitive(j, "resourceType"));
        }
      }
      if (cJSON_HasObjectItem(j, "rRMPolicyDedicatedRatio")) {
        if (NULL != (x->r_rm_policy_dedicated_ratio = cJSON_malloc(sizeof(uint8_t)))) {
          *x->r_rm_policy_dedicated_ratio = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "rRMPolicyDedicatedRatio"));
        }
      }
      if (cJSON_HasObjectItem(j, "rRMPolicyMaxRatio")) {
        if (NULL != (x->r_rm_policy_max_ratio = cJSON_malloc(sizeof(uint8_t)))) {
          *x->r_rm_policy_max_ratio = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "rRMPolicyMaxRatio"));
        }
      }
      if (cJSON_HasObjectItem(j, "rRMPolicyMemberList")) {
        list_t * x1 = list_create(false, NULL);
        if (NULL != x1) {
          cJSON * e1 = NULL;
          cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "rRMPolicyMemberList");
          cJSON_ArrayForEach(e1, j1) {
            list_add_tail(x1, cJSON_Getr_rm_policy_member_list_elementValue(e1), sizeof(r_rm_policy_member_list_element_t *));
          }
          x->r_rm_policy_member_list = x1;
        }
      }
      if (cJSON_HasObjectItem(j, "rRMPolicyMinRatio")) {
        if (NULL != (x->r_rm_policy_min_ratio = cJSON_malloc(sizeof(uint8_t)))) {
          *x->r_rm_policy_min_ratio = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "rRMPolicyMinRatio"));
        }
      }
      if (cJSON_HasObjectItem(j, "bwpContext")) {
        if (NULL != (x->bwp_context = cJSON_malloc(sizeof(bwp_context_e)))) {
          *x->bwp_context = cJSON_Getbwp_contextValue(cJSON_GetObjectItemCaseSensitive(j, "bwpContext"));
        }
      }
      if (cJSON_HasObjectItem(j, "cyclicPrefix")) {
        if (NULL != (x->cyclic_prefix = cJSON_malloc(sizeof(cyclic_prefix_e)))) {
          *x->cyclic_prefix = cJSON_Getcyclic_prefixValue(cJSON_GetObjectItemCaseSensitive(j, "cyclicPrefix"));
        }
      }
      if (cJSON_HasObjectItem(j, "isInitialBwp")) {
        if (NULL != (x->is_initial_bwp = cJSON_malloc(sizeof(is_initial_bwp_e)))) {
          *x->is_initial_bwp = cJSON_Getis_initial_bwpValue(cJSON_GetObjectItemCaseSensitive(j, "isInitialBwp"));
        }
      }
      if (cJSON_HasObjectItem(j, "numberOfRBs")) {
        if (NULL != (x->number_of_r_bs = cJSON_malloc(sizeof(int64_t)))) {
          *x->number_of_r_bs = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "numberOfRBs"));
        }
      }
      if (cJSON_HasObjectItem(j, "startRB")) {
        if (NULL != (x->start_rb = cJSON_malloc(sizeof(int64_t)))) {
          *x->start_rb = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "startRB"));
        }
      }
      if (cJSON_HasObjectItem(j, "subCarrierSpacing")) {
        if (NULL != (x->sub_carrier_spacing = cJSON_malloc(sizeof(uint32_t)))) {
          *x->sub_carrier_spacing = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "subCarrierSpacing"));
        }
      }
      if (cJSON_HasObjectItem(j, "cesSwitch")) {
        if (NULL != (x->ces_switch = cJSON_malloc(sizeof(bool)))) {
          *x->ces_switch = cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(j, "cesSwitch"));
        }
      }
      if (cJSON_HasObjectItem(j, "energySavingControl")) {
        if (NULL != (x->energy_saving_control = cJSON_malloc(sizeof(energy_saving_control_e)))) {
          *x->energy_saving_control = cJSON_Getenergy_saving_controlValue(cJSON_GetObjectItemCaseSensitive(j, "energySavingControl"));
        }
      }
      if (cJSON_HasObjectItem(j, "energySavingState")) {
        if (NULL != (x->energy_saving_state = cJSON_malloc(sizeof(energy_saving_state_e)))) {
          *x->energy_saving_state = cJSON_Getenergy_saving_stateValue(cJSON_GetObjectItemCaseSensitive(j, "energySavingState"));
        }
      }
    }
  }
  return x;
}

cJSON * cJSON_Createran_configuration_structure(const ran_configuration_structure_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      if (NULL != x->gnb_cu_name) {
        cJSON_AddStringToObject(j, "gnbCuName", x->gnb_cu_name);
      }
      if (NULL != x->gnb_id) {
        cJSON_AddNumberToObject(j, "gnbId", *x->gnb_id);
      }
      if (NULL != x->gnb_id_length) {
        cJSON_AddNumberToObject(j, "gnbIdLength", *x->gnb_id_length);
      }
      if (NULL != x->plmn_id) {
        cJSON_AddItemToObject(j, "plmnId", cJSON_Createplmn_id(x->plmn_id));
      }
      if (NULL != x->x2_allow_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "x2AllowList");
        if (NULL != j1) {
          char * x1 = list_get_head(x->x2_allow_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
            x1 = list_get_next(x->x2_allow_list);
          }
        }
      }
      if (NULL != x->x2_block_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "x2BlockList");
        if (NULL != j1) {
          char * x1 = list_get_head(x->x2_block_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
            x1 = list_get_next(x->x2_block_list);
          }
        }
      }
      if (NULL != x->x2_ho_block_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "x2HOBlockList");
        if (NULL != j1) {
          char * x1 = list_get_head(x->x2_ho_block_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
            x1 = list_get_next(x->x2_ho_block_list);
          }
        }
      }
      if (NULL != x->xn_allow_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "xnAllowList");
        if (NULL != j1) {
          char * x1 = list_get_head(x->xn_allow_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
            x1 = list_get_next(x->xn_allow_list);
          }
        }
      }
      if (NULL != x->xn_block_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "xnBlockList");
        if (NULL != j1) {
          char * x1 = list_get_head(x->xn_block_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
            x1 = list_get_next(x->xn_block_list);
          }
        }
      }
      if (NULL != x->xn_ho_block_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "xnHOBlockList");
        if (NULL != j1) {
          char * x1 = list_get_head(x->xn_ho_block_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
            x1 = list_get_next(x->xn_ho_block_list);
          }
        }
      }
      if (NULL != x->gnb_cu_up_id) {
        cJSON_AddNumberToObject(j, "gnbCuUpId", *x->gnb_cu_up_id);
      }
      if (NULL != x->plmn_info_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "plmnInfoList");
        if (NULL != j1) {
          plmn_info_list_element_t * x1 = list_get_head(x->plmn_info_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createplmn_info_list_element(x1));
            x1 = list_get_next(x->plmn_info_list);
          }
        }
      }
      if (NULL != x->gnb_du_id) {
        cJSON_AddNumberToObject(j, "gnbDuId", *x->gnb_du_id);
      }
      if (NULL != x->gnb_du_name) {
        cJSON_AddStringToObject(j, "gnbDuName", x->gnb_du_name);
      }
      if (NULL != x->cell_local_id) {
        cJSON_AddNumberToObject(j, "cellLocalId", *x->cell_local_id);
      }
      if (NULL != x->administrative_state) {
        cJSON_AddItemToObject(j, "administrativeState", cJSON_Createadministrative_state(*x->administrative_state));
      }
      if (NULL != x->arfcn_dl) {
        cJSON_AddNumberToObject(j, "arfcnDL", *x->arfcn_dl);
      }
      if (NULL != x->arfcn_sul) {
        cJSON_AddNumberToObject(j, "arfcnSUL", *x->arfcn_sul);
      }
      if (NULL != x->arfcn_ul) {
        cJSON_AddNumberToObject(j, "arfcnUL", *x->arfcn_ul);
      }
      if (NULL != x->b_s_channel_bw_dl) {
        cJSON_AddNumberToObject(j, "bSChannelBwDL", *x->b_s_channel_bw_dl);
      }
      if (NULL != x->b_s_channel_bw_sul) {
        cJSON_AddNumberToObject(j, "bSChannelBwSUL", *x->b_s_channel_bw_sul);
      }
      if (NULL != x->b_s_channel_bw_ul) {
        cJSON_AddNumberToObject(j, "bSChannelBwUL", *x->b_s_channel_bw_ul);
      }
      if (NULL != x->bwp_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "bwpList");
        if (NULL != j1) {
          bwp_list_element_t * x1 = list_get_head(x->bwp_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createbwp_list_element(x1));
            x1 = list_get_next(x->bwp_list);
          }
        }
      }
      if (NULL != x->cell_state) {
        cJSON_AddItemToObject(j, "cellState", cJSON_Createcell_state(*x->cell_state));
      }
      if (NULL != x->nr_pci) {
        cJSON_AddNumberToObject(j, "nrPci", *x->nr_pci);
      }
      if (NULL != x->nr_tac) {
        cJSON_AddNumberToObject(j, "nrTac", *x->nr_tac);
      }
      if (NULL != x->operational_state) {
        cJSON_AddItemToObject(j, "operationalState", cJSON_Createoperational_state(*x->operational_state));
      }
      if (NULL != x->partition_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "partitionList");
        if (NULL != j1) {
          partition_list_element_t * x1 = list_get_head(x->partition_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Createpartition_list_element(x1));
            x1 = list_get_next(x->partition_list);
          }
        }
      }
      if (NULL != x->ssb_duration) {
        cJSON_AddNumberToObject(j, "ssbDuration", *x->ssb_duration);
      }
      if (NULL != x->ssb_frequency) {
        cJSON_AddNumberToObject(j, "ssbFrequency", *x->ssb_frequency);
      }
      if (NULL != x->ssb_offset) {
        cJSON_AddNumberToObject(j, "ssbOffset", *x->ssb_offset);
      }
      if (NULL != x->ssb_periodicity) {
        cJSON_AddNumberToObject(j, "ssbPeriodicity", *x->ssb_periodicity);
      }
      if (NULL != x->ssb_sub_carrier_spacing) {
        cJSON_AddNumberToObject(j, "ssbSubCarrierSpacing", *x->ssb_sub_carrier_spacing);
      }
      if (NULL != x->resource_type) {
        cJSON_AddItemToObject(j, "resourceType", cJSON_Createresource_type(*x->resource_type));
      }
      if (NULL != x->r_rm_policy_dedicated_ratio) {
        cJSON_AddNumberToObject(j, "rRMPolicyDedicatedRatio", *x->r_rm_policy_dedicated_ratio);
      }
      if (NULL != x->r_rm_policy_max_ratio) {
        cJSON_AddNumberToObject(j, "rRMPolicyMaxRatio", *x->r_rm_policy_max_ratio);
      }
      if (NULL != x->r_rm_policy_member_list) {
        cJSON * j1 = cJSON_AddArrayToObject(j, "rRMPolicyMemberList");
        if (NULL != j1) {
          r_rm_policy_member_list_element_t * x1 = list_get_head(x->r_rm_policy_member_list);
          while (NULL != x1) {
            cJSON_AddItemToArray(j1, cJSON_Creater_rm_policy_member_list_element(x1));
            x1 = list_get_next(x->r_rm_policy_member_list);
          }
        }
      }
      if (NULL != x->r_rm_policy_min_ratio) {
        cJSON_AddNumberToObject(j, "rRMPolicyMinRatio", *x->r_rm_policy_min_ratio);
      }
      if (NULL != x->bwp_context) {
        cJSON_AddItemToObject(j, "bwpContext", cJSON_Createbwp_context(*x->bwp_context));
      }
      if (NULL != x->cyclic_prefix) {
        cJSON_AddItemToObject(j, "cyclicPrefix", cJSON_Createcyclic_prefix(*x->cyclic_prefix));
      }
      if (NULL != x->is_initial_bwp) {
        cJSON_AddItemToObject(j, "isInitialBwp", cJSON_Createis_initial_bwp(*x->is_initial_bwp));
      }
      if (NULL != x->number_of_r_bs) {
        cJSON_AddNumberToObject(j, "numberOfRBs", *x->number_of_r_bs);
      }
      if (NULL != x->start_rb) {
        cJSON_AddNumberToObject(j, "startRB", *x->start_rb);
      }
      if (NULL != x->sub_carrier_spacing) {
        cJSON_AddNumberToObject(j, "subCarrierSpacing", *x->sub_carrier_spacing);
      }
      if (NULL != x->ces_switch) {
        cJSON_AddBoolToObject(j, "cesSwitch", *x->ces_switch);
      }
      if (NULL != x->energy_saving_control) {
        cJSON_AddItemToObject(j, "energySavingControl", cJSON_Createenergy_saving_control(*x->energy_saving_control));
      }
      if (NULL != x->energy_saving_state) {
        cJSON_AddItemToObject(j, "energySavingState", cJSON_Createenergy_saving_state(*x->energy_saving_state));
      }
    }
  }
  return j;
}

char * cJSON_Printran_configuration_structure(const ran_configuration_structure_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createran_configuration_structure(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deleteran_configuration_structure(ran_configuration_structure_json_t * x) {
  if (NULL != x) {
    if (NULL != x->gnb_cu_name) {
      cJSON_free(x->gnb_cu_name);
    }
    if (NULL != x->gnb_id) {
      cJSON_free(x->gnb_id);
    }
    if (NULL != x->gnb_id_length) {
      cJSON_free(x->gnb_id_length);
    }
    if (NULL != x->plmn_id) {
      cJSON_Deleteplmn_id(x->plmn_id);
    }
    if (NULL != x->x2_allow_list) {
      char * x1 = list_get_head(x->x2_allow_list);
      while (NULL != x1) {
        cJSON_free(x1);
        x1 = list_get_next(x->x2_allow_list);
      }
      list_release(x->x2_allow_list);
    }
    if (NULL != x->x2_block_list) {
      char * x1 = list_get_head(x->x2_block_list);
      while (NULL != x1) {
        cJSON_free(x1);
        x1 = list_get_next(x->x2_block_list);
      }
      list_release(x->x2_block_list);
    }
    if (NULL != x->x2_ho_block_list) {
      char * x1 = list_get_head(x->x2_ho_block_list);
      while (NULL != x1) {
        cJSON_free(x1);
        x1 = list_get_next(x->x2_ho_block_list);
      }
      list_release(x->x2_ho_block_list);
    }
    if (NULL != x->xn_allow_list) {
      char * x1 = list_get_head(x->xn_allow_list);
      while (NULL != x1) {
        cJSON_free(x1);
        x1 = list_get_next(x->xn_allow_list);
      }
      list_release(x->xn_allow_list);
    }
    if (NULL != x->xn_block_list) {
      char * x1 = list_get_head(x->xn_block_list);
      while (NULL != x1) {
        cJSON_free(x1);
        x1 = list_get_next(x->xn_block_list);
      }
      list_release(x->xn_block_list);
    }
    if (NULL != x->xn_ho_block_list) {
      char * x1 = list_get_head(x->xn_ho_block_list);
      while (NULL != x1) {
        cJSON_free(x1);
        x1 = list_get_next(x->xn_ho_block_list);
      }
      list_release(x->xn_ho_block_list);
    }
    if (NULL != x->gnb_cu_up_id) {
      cJSON_free(x->gnb_cu_up_id);
    }
    if (NULL != x->plmn_info_list) {
      plmn_info_list_element_t * x1 = list_get_head(x->plmn_info_list);
      while (NULL != x1) {
        cJSON_Deleteplmn_info_list_element(x1);
        x1 = list_get_next(x->plmn_info_list);
      }
      list_release(x->plmn_info_list);
    }
    if (NULL != x->gnb_du_id) {
      cJSON_free(x->gnb_du_id);
    }
    if (NULL != x->gnb_du_name) {
      cJSON_free(x->gnb_du_name);
    }
    if (NULL != x->cell_local_id) {
      cJSON_free(x->cell_local_id);
    }
    if (NULL != x->administrative_state) {
      cJSON_free(x->administrative_state);
    }
    if (NULL != x->arfcn_dl) {
      cJSON_free(x->arfcn_dl);
    }
    if (NULL != x->arfcn_sul) {
      cJSON_free(x->arfcn_sul);
    }
    if (NULL != x->arfcn_ul) {
      cJSON_free(x->arfcn_ul);
    }
    if (NULL != x->b_s_channel_bw_dl) {
      cJSON_free(x->b_s_channel_bw_dl);
    }
    if (NULL != x->b_s_channel_bw_sul) {
      cJSON_free(x->b_s_channel_bw_sul);
    }
    if (NULL != x->b_s_channel_bw_ul) {
      cJSON_free(x->b_s_channel_bw_ul);
    }
    if (NULL != x->bwp_list) {
      bwp_list_element_t * x1 = list_get_head(x->bwp_list);
      while (NULL != x1) {
        cJSON_Deletebwp_list_element(x1);
        x1 = list_get_next(x->bwp_list);
      }
      list_release(x->bwp_list);
    }
    if (NULL != x->cell_state) {
      cJSON_free(x->cell_state);
    }
    if (NULL != x->nr_pci) {
      cJSON_free(x->nr_pci);
    }
    if (NULL != x->nr_tac) {
      cJSON_free(x->nr_tac);
    }
    if (NULL != x->operational_state) {
      cJSON_free(x->operational_state);
    }
    if (NULL != x->partition_list) {
      partition_list_element_t * x1 = list_get_head(x->partition_list);
      while (NULL != x1) {
        cJSON_Deletepartition_list_element(x1);
        x1 = list_get_next(x->partition_list);
      }
      list_release(x->partition_list);
    }
    if (NULL != x->ssb_duration) {
      cJSON_free(x->ssb_duration);
    }
    if (NULL != x->ssb_frequency) {
      cJSON_free(x->ssb_frequency);
    }
    if (NULL != x->ssb_offset) {
      cJSON_free(x->ssb_offset);
    }
    if (NULL != x->ssb_periodicity) {
      cJSON_free(x->ssb_periodicity);
    }
    if (NULL != x->ssb_sub_carrier_spacing) {
      cJSON_free(x->ssb_sub_carrier_spacing);
    }
    if (NULL != x->resource_type) {
      cJSON_free(x->resource_type);
    }
    if (NULL != x->r_rm_policy_dedicated_ratio) {
      cJSON_free(x->r_rm_policy_dedicated_ratio);
    }
    if (NULL != x->r_rm_policy_max_ratio) {
      cJSON_free(x->r_rm_policy_max_ratio);
    }
    if (NULL != x->r_rm_policy_member_list) {
      r_rm_policy_member_list_element_t * x1 = list_get_head(x->r_rm_policy_member_list);
      while (NULL != x1) {
        cJSON_Deleter_rm_policy_member_list_element(x1);
        x1 = list_get_next(x->r_rm_policy_member_list);
      }
      list_release(x->r_rm_policy_member_list);
    }
    if (NULL != x->r_rm_policy_min_ratio) {
      cJSON_free(x->r_rm_policy_min_ratio);
    }
    if (NULL != x->bwp_context) {
      cJSON_free(x->bwp_context);
    }
    if (NULL != x->cyclic_prefix) {
      cJSON_free(x->cyclic_prefix);
    }
    if (NULL != x->is_initial_bwp) {
      cJSON_free(x->is_initial_bwp);
    }
    if (NULL != x->number_of_r_bs) {
      cJSON_free(x->number_of_r_bs);
    }
    if (NULL != x->start_rb) {
      cJSON_free(x->start_rb);
    }
    if (NULL != x->sub_carrier_spacing) {
      cJSON_free(x->sub_carrier_spacing);
    }
    if (NULL != x->ces_switch) {
      cJSON_free(x->ces_switch);
    }
    if (NULL != x->energy_saving_control) {
      cJSON_free(x->energy_saving_control);
    }
    if (NULL != x->energy_saving_state) {
      cJSON_free(x->energy_saving_state);
    }
    cJSON_free(x);
  }
}

values_of_attributes_json_t * cJSON_Parsevalues_of_attributes(const char * s) {
  values_of_attributes_json_t * x = NULL;
  if (NULL != s) {
    cJSON * j = cJSON_Parse(s);
    if (NULL != j) {
      x = cJSON_Getvalues_of_attributesValue(j);
      cJSON_Delete(j);
    }
  }
  return x;
}

values_of_attributes_json_t * cJSON_Getvalues_of_attributesValue(const cJSON * j) {
  values_of_attributes_json_t * x = NULL;
  if (NULL != j) {
    if (NULL != (x = cJSON_malloc(sizeof(values_of_attributes_json_t)))) {
      memset(x, 0, sizeof(values_of_attributes_json_t));
      if (cJSON_HasObjectItem(j, "ranConfigurationStructure")) {
        x->ran_configuration_structure = cJSON_Getran_configuration_structureValue(cJSON_GetObjectItemCaseSensitive(j, "ranConfigurationStructure"));
      }
    }
  }
  return x;
}

cJSON * cJSON_Createvalues_of_attributes(const values_of_attributes_json_t * x) {
  cJSON * j = NULL;
  if (NULL != x) {
    if (NULL != (j = cJSON_CreateObject())) {
      cJSON_AddItemToObject(j, "ranConfigurationStructure", cJSON_Createran_configuration_structure(x->ran_configuration_structure));
    }
  }
  return j;
}

char * cJSON_Printvalues_of_attributes(const values_of_attributes_json_t * x) {
  char * s = NULL;
  if (NULL != x) {
    cJSON * j = cJSON_Createvalues_of_attributes(x);
    if (NULL != j) {
      s = cJSON_PrintUnformatted(j);
      cJSON_Delete(j);
    }
  }
  return s;
}

void cJSON_Deletevalues_of_attributes(values_of_attributes_json_t * x) {
  if (NULL != x) {
    if (NULL != x->ran_configuration_structure) {
      cJSON_Deleteran_configuration_structure(x->ran_configuration_structure);
    }
    cJSON_free(x);
  }
}


#endif /* __STDOUT__ */
