/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RRCStats-IEs"
 * 	found in "../e2sm_rrc_v00.asn"
 * 	`asn1c -gen-PER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#include "E2SM-RRCStats-ControlMessage-Format1.h"

static int
controlMsgParam_2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_controlMsgParam_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static asn_per_constraints_t asn_PER_type_controlMsgParam_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_controlMsgParam_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_controlMsgParam_specs_2 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_controlMsgParam_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_controlMsgParam_2 = {
	"controlMsgParam",
	"controlMsgParam",
	&asn_OP_NativeInteger,
	asn_DEF_controlMsgParam_tags_2,
	sizeof(asn_DEF_controlMsgParam_tags_2)
		/sizeof(asn_DEF_controlMsgParam_tags_2[0]) - 1, /* 1 */
	asn_DEF_controlMsgParam_tags_2,	/* Same as above */
	sizeof(asn_DEF_controlMsgParam_tags_2)
		/sizeof(asn_DEF_controlMsgParam_tags_2[0]), /* 2 */
	{ 0, &asn_PER_type_controlMsgParam_constr_2, controlMsgParam_2_constraint },
	0, 0,	/* No members */
	&asn_SPC_controlMsgParam_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2SM_RRCStats_ControlMessage_Format1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RRCStats_ControlMessage_Format1, controlMsgParam),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_controlMsgParam_2,
		0,
		{ 0, &asn_PER_memb_controlMsgParam_constr_2,  memb_controlMsgParam_constraint_1 },
		0, 0, /* No default value */
		"controlMsgParam"
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_RRCStats_ControlMessage_Format1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RRCStats_ControlMessage_Format1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* controlMsgParam */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_RRCStats_ControlMessage_Format1_specs_1 = {
	sizeof(struct E2SM_RRCStats_ControlMessage_Format1),
	offsetof(struct E2SM_RRCStats_ControlMessage_Format1, _asn_ctx),
	asn_MAP_E2SM_RRCStats_ControlMessage_Format1_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RRCStats_ControlMessage_Format1 = {
	"E2SM-RRCStats-ControlMessage-Format1",
	"E2SM-RRCStats-ControlMessage-Format1",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RRCStats_ControlMessage_Format1_tags_1,
	sizeof(asn_DEF_E2SM_RRCStats_ControlMessage_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_RRCStats_ControlMessage_Format1_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RRCStats_ControlMessage_Format1_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RRCStats_ControlMessage_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_RRCStats_ControlMessage_Format1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RRCStats_ControlMessage_Format1_1,
	1,	/* Elements count */
	&asn_SPC_E2SM_RRCStats_ControlMessage_Format1_specs_1	/* Additional specs */
};

