/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RRCStats-IEs"
 * 	found in "../e2sm_rrc_v00.asn"
 * 	`asn1c -gen-PER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_RRCStats_ControlOutcome_H_
#define	_RRCStats_ControlOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCStats_ControlOutcome {
	RRCStats_ControlOutcome_rrcCtrlOutcomeOk	= 0,
	RRCStats_ControlOutcome_rrcCtrlOutcomeEnd	= 1
	/*
	 * Enumeration is extensible
	 */
} e_RRCStats_ControlOutcome;

/* RRCStats-ControlOutcome */
typedef long	 RRCStats_ControlOutcome_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RRCStats_ControlOutcome_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RRCStats_ControlOutcome;
extern const asn_INTEGER_specifics_t asn_SPC_RRCStats_ControlOutcome_specs_1;
asn_struct_free_f RRCStats_ControlOutcome_free;
asn_struct_print_f RRCStats_ControlOutcome_print;
asn_constr_check_f RRCStats_ControlOutcome_constraint;
ber_type_decoder_f RRCStats_ControlOutcome_decode_ber;
der_type_encoder_f RRCStats_ControlOutcome_encode_der;
xer_type_decoder_f RRCStats_ControlOutcome_decode_xer;
xer_type_encoder_f RRCStats_ControlOutcome_encode_xer;
per_type_decoder_f RRCStats_ControlOutcome_decode_uper;
per_type_encoder_f RRCStats_ControlOutcome_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCStats_ControlOutcome_H_ */
#include <asn_internal.h>
