/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RRCStats-IEs"
 * 	found in "../e2sm_rrc_v00.asn"
 * 	`asn1c -gen-PER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#include "RRCStats-Message.h"

#include "RRCUeStats.h"
static asn_TYPE_member_t asn_MBR_ueStats_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RRCUeStats,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ueStats_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ueStats_specs_2 = {
	sizeof(struct RRCStats_Message__ueStats),
	offsetof(struct RRCStats_Message__ueStats, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ueStats_2 = {
	"ueStats",
	"ueStats",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ueStats_tags_2,
	sizeof(asn_DEF_ueStats_tags_2)
		/sizeof(asn_DEF_ueStats_tags_2[0]) - 1, /* 1 */
	asn_DEF_ueStats_tags_2,	/* Same as above */
	sizeof(asn_DEF_ueStats_tags_2)
		/sizeof(asn_DEF_ueStats_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_ueStats_2,
	1,	/* Single element */
	&asn_SPC_ueStats_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RRCStats_Message_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCStats_Message, ueStats),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ueStats_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueStats"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCStats_Message, tstamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tstamp"
		},
};
static const ber_tlv_tag_t asn_DEF_RRCStats_Message_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRCStats_Message_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ueStats */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tstamp */
};
asn_SEQUENCE_specifics_t asn_SPC_RRCStats_Message_specs_1 = {
	sizeof(struct RRCStats_Message),
	offsetof(struct RRCStats_Message, _asn_ctx),
	asn_MAP_RRCStats_Message_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RRCStats_Message = {
	"RRCStats-Message",
	"RRCStats-Message",
	&asn_OP_SEQUENCE,
	asn_DEF_RRCStats_Message_tags_1,
	sizeof(asn_DEF_RRCStats_Message_tags_1)
		/sizeof(asn_DEF_RRCStats_Message_tags_1[0]), /* 1 */
	asn_DEF_RRCStats_Message_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCStats_Message_tags_1)
		/sizeof(asn_DEF_RRCStats_Message_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RRCStats_Message_1,
	2,	/* Elements count */
	&asn_SPC_RRCStats_Message_specs_1	/* Additional specs */
};

