/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RRCStats-IEs"
 * 	found in "../e2sm_rrc_v00.asn"
 * 	`asn1c -gen-PER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_RRCStats_Header_H_
#define	_RRCStats_Header_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCStats-Header */
typedef long	 RRCStats_Header_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCStats_Header;
asn_struct_free_f RRCStats_Header_free;
asn_struct_print_f RRCStats_Header_print;
asn_constr_check_f RRCStats_Header_constraint;
ber_type_decoder_f RRCStats_Header_decode_ber;
der_type_encoder_f RRCStats_Header_encode_der;
xer_type_decoder_f RRCStats_Header_decode_xer;
xer_type_encoder_f RRCStats_Header_encode_xer;
per_type_decoder_f RRCStats_Header_decode_uper;
per_type_encoder_f RRCStats_Header_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCStats_Header_H_ */
#include <asn_internal.h>
