/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RRCStats-IEs"
 * 	found in "../e2sm_rrc_v00.asn"
 * 	`asn1c -gen-PER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_RRCStats_TriggerNature_H_
#define	_RRCStats_TriggerNature_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCStats_TriggerNature {
	RRCStats_TriggerNature_oneMs	= 0,
	RRCStats_TriggerNature_twoMs	= 1,
	RRCStats_TriggerNature_fiveMs	= 2
	/*
	 * Enumeration is extensible
	 */
} e_RRCStats_TriggerNature;

/* RRCStats-TriggerNature */
typedef long	 RRCStats_TriggerNature_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RRCStats_TriggerNature_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RRCStats_TriggerNature;
extern const asn_INTEGER_specifics_t asn_SPC_RRCStats_TriggerNature_specs_1;
asn_struct_free_f RRCStats_TriggerNature_free;
asn_struct_print_f RRCStats_TriggerNature_print;
asn_constr_check_f RRCStats_TriggerNature_constraint;
ber_type_decoder_f RRCStats_TriggerNature_decode_ber;
der_type_encoder_f RRCStats_TriggerNature_encode_der;
xer_type_decoder_f RRCStats_TriggerNature_decode_xer;
xer_type_encoder_f RRCStats_TriggerNature_encode_xer;
per_type_decoder_f RRCStats_TriggerNature_decode_uper;
per_type_encoder_f RRCStats_TriggerNature_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCStats_TriggerNature_H_ */
#include <asn_internal.h>
