/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RRCStats-IEs"
 * 	found in "../e2sm_rrc_v00.asn"
 * 	`asn1c -gen-PER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_RRCUeStats_H_
#define	_RRCUeStats_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCUeStats */
typedef struct RRCUeStats {
	unsigned long	 rnti;
	long	 rbid;
	struct RRCUeStats__drbActive {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} drbActive;
	long	 statusRrc;
	long	 setupPduSession;
	long	 nbOfPdusessions;
	long	 ueRrcInactivityTimer;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCUeStats_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rnti_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCUeStats;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCUeStats_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCUeStats_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCUeStats_H_ */
#include <asn_internal.h>
