noPoll websocket implementation , WebSocket implementation, RFC 6455 implementation, (Servidores Linux http://www.aspl.es)
nopoll_base64_decode
nopoll_base64_encode
nopoll_cleanup_library
nopoll_cmp
nopoll_get_32bit
nopoll_mutex_create
nopoll_mutex_destroy
nopoll_mutex_lock
nopoll_mutex_unlock
nopoll_ncmp
nopoll_nonce
nopoll_sleep
nopoll_strdup
nopoll_strdup_printf
nopoll_strdup_printfv
nopoll_thread_handlers
nopoll_timeval_substract
nopoll_trim
nopoll_vprintf_len
nopoll_mutex_lock()
void nopoll_mutex_lock (noPollPtr mutex)
Implements a mutex lock operation on the provided reference.
The function just skip when no mutex reference is received o no lock handler was defined.
See nopoll_thread_handlers for more information.
Parameters
mutex The mutex where do the lock operation.
The function will just return if the reference isn't defined or the lock handler wasn't installed.
Referenced by nopoll_conn_is_ready(), nopoll_conn_opts_ref(), nopoll_conn_ref(), nopoll_conn_unref(), nopoll_ctx_foreach_conn(), nopoll_ctx_ref(), nopoll_ctx_ref_count(), nopoll_ctx_unref(), nopoll_msg_ref(), nopoll_msg_ref_count(), and nopoll_msg_unref().