#ifndef CELL_LEVEL_RAN_CONFIGURATION_NAME_CONTROL_H
#define CELL_LEVEL_RAN_CONFIGURATION_NAME_CONTROL_H

/* 8.2.2 Cell Level RAN Configuration Name CONTROL  */

typedef enum {
    O_NR_Cell_CU_RAN_CONF_NAME_CONTROL,
    O_BWP_RAN_CONF_NAME_CONTROL,
    O_RRM_POLICY_RATIO_RAN_CONF_NAME_CONTROL,

    END_CELL_RAN_CONF_NAME_CONTROL

} cell_level_ran_conf_struct_name_control_e;

#endif
