#ifndef CELL_LEVEL_RAN_CONFIGURATION_NAME_REPORT_H
#define CELL_LEVEL_RAN_CONFIGURATION_NAME_REPORT_H

/* 8.2.2 Cell Level RAN Configuration Name REPORT  */

typedef enum {
    O_NR_Cell_CU_RAN_CONF_NAME_REPORT,
    O_NR_Cell_DU_RAN_CONF_NAME_REPORT,
    O_BWP_RAN_CONF_NAME_REPORT,
    O_RRM_POLICY_RATIO_RAN_CONF_NAME_REPORT,

    END_CELL_RAN_CONF_NAME_REPORT

} cell_level_ran_conf_struct_name_report_e;



#endif
