#ifndef CONTROL_CAUSE_FAILURE_CCC_H
#define CONTROL_CAUSE_FAILURE_CCC_H

/*  9.3.11  Cause  */

typedef enum {
    NOT_SUPPORTED_CONTROL_CAUSE_FAILURE_CCC,
    NOT_AVAILABLE_CONTROL_CAUSE_FAILURE_CCC,
    INCOMPATIBLE_STATE_CONTROL_CAUSE_FAILURE_CCC,
    JSON_ERROR_CONTROL_CAUSE_FAILURE_CCC,
    SEMANTIC_ERROR_CONTROL_CAUSE_FAILURE_CCC,
    UNSPECIFIED_CONTROL_CAUSE_FAILURE_CCC,

    END_CONTROL_CAUSE_FAILURE_CCC

} control_cause_failure_e;



#endif
