#ifndef O_BWP_ATTRIBUTE_NAME_H
#define O_BWP_ATTRIBUTE_NAME_H

// 8.8.2.3  O-BWP - REPORT & CONTROL services

typedef enum {
    BWP_CONTEXT_ATTRIBUTE_NAME_BWP_CELL,
    IS_INITIAL_BWP_ATTRIBUTE_NAME_BWP_CELL,
    SUB_CARRIER_SPACING_ATTRIBUTE_NAME_BWP_CELL,
    CYCLIC_PREFIX_ATTRIBUTE_NAME_BWP_CELL,
    START_RB_ATTRIBUTE_NAME_BWP_CELL,
    NUMBER_OF_RBS_ATTRIBUTE_NAME_BWP_CELL,

    END_ATTRIBUTE_NAME_BWP_CELL

} o_bwp_attribute_name_e;  //  for event trigger and action definition


#endif
