#ifndef O_GNB_CU_CP_NODE_ATTRIBUTE_NAME_H
#define O_GNB_CU_CP_NODE_ATTRIBUTE_NAME_H

#include <stdint.h>


// 8.8.1.2  O-GNBCUCPFunction - REPORT & CONTROL services

typedef enum {
    GNB_ID_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,
    GNB_ID_LENGTH_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,
    GNB_CU_NAME_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,
    PLMN_ID_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,
    X2_EXCLUDE_LIST_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,
    XN_EXCLUDE_LIST_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,
    X2_INCLUDE_LIST_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,
    XN_INCLUDE_LIST_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,

    END_NODE_ATTRIBUTE_NAME_O_GNB_CU_CP_FUNCTION,

} o_gnb_cu_cp_node_attribute_name_e;  //  for event trigger and action definition



#endif
