#ifndef O_NR_CELL_DU_ATTRIBUTE_NAME_H
#define O_NR_CELL_DU_ATTRIBUTE_NAME_H


//  8.8.2.2  O-NRCellDU - REPORT service

typedef enum {
    CELL_LOCAL_ID_ATTRIBUTE_NAME_REPORT,
    OPERATIONAL_STATE_ATTRIBUTE_NAME_REPORT,
    ADMINISTRATIVE_STATE_ATTRIBUTE_NAME_REPORT,
    CELL_STATE_ATTRIBUTE_NAME_REPORT,
    PLMN_INFO_LIST_ATTRIBUTE_NAME_REPORT,
    N_RPCI_ATTRIBUTE_NAME_REPORT,
    N_RTAC_ATTRIBUTE_NAME_REPORT,
    ARFCN_DL_ATTRIBUTE_NAME_REPORT,
    ARFCN_UL_ATTRIBUTE_NAME_REPORT,
    ARFCN_SUL_ATTRIBUTE_NAME_REPORT,
    BS_CHANNEL_BW_DL_ATTRIBUTE_NAME_REPORT,
    SSB_FREQUENCY_ATTRIBUTE_NAME_REPORT,
    SSB_PERIODICITY_ATTRIBUTE_NAME_REPORT,
    SSB_SUB_CARRIER_SPACING_ATTRIBUTE_NAME_REPORT,
    SSB_OFFSET_ATTRIBUTE_NAME_REPORT,
    SSB_DURATION_ATTRIBUTE_NAME_REPORT,
    BS_CHANNEL_BW_UL_ATTRIBUTE_NAME_REPORT,
    BS_CHANNEL_BW_SUL_ATTRIBUTE_NAME_REPORT,
    BWP_LIST_ATTRIBUTE_NAME_REPORT,

    END_O_NR_CELL_DU_ATTRIBUTE_NAME_REPORT

} o_nr_cell_du_attribute_name_e;  //  for event trigger and action definition


#endif
