#ifndef O_NR_CELL_DU_ATTRIBUTE_NAME_H
#define O_NR_CELL_DU_ATTRIBUTE_NAME_H


//  8.8.2.2  O-NRCellDU - REPORT service

typedef enum {
    CELL_LOCAL_ID_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    OPERATIONAL_STATE_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    ADMINISTRATIVE_STATE_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    CELL_STATE_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    PLMN_INFO_LIST_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    N_RPCI_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    N_RTAC_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    ARFCN_DL_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    ARFCN_UL_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    ARFCN_SUL_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    BS_CHANNEL_BW_DL_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    SSB_FREQUENCY_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    SSB_PERIODICITY_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    SSB_SUB_CARRIER_SPACING_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    SSB_OFFSET_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    SSB_DURATION_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    BS_CHANNEL_BW_UL_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    BS_CHANNEL_BW_SUL_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,
    BWP_LIST_ATTRIBUTE_NAME_REPORT_NR_CELL_DU,

    END_ATTRIBUTE_NAME_REPORT_NR_CELL_DU

} o_nr_cell_du_attribute_name_e;  //  for event trigger and action definition


#endif
