#ifndef COUNTER_MSGS_AMARISOFT_H
#define COUNTER_MSGS_AMARISOFT_H 


// type in amarisoft bash: $ cevent help msg
typedef struct {

// Global events:
//Message events: 

int s1_handover_required; 
//int s1_handover_command 
//int s1_handover_preparation_failure 
//int s1_handover_request 
//int s1_handover_request_ack 
//int s1_handover_failure 
//int s1_handover_notify 
//int s1_path_switch_request 
//int s1_path_switch_request_ack 
//int s1_path_switch_request_failure 
//int s1_handover_cancel 
//int s1_handover_cancel_ack 
//int s1_erab_setup_request 
//int s1_erab_setup_response 
//int s1_erab_modify_request 
//int s1_erab_modify_response 
//int s1_erab_release_command 
//int s1_erab_release_response 
//int s1_erab_release_indication 
//int s1_initial_context_setup_request 
//int s1_initial_context_setup_response 
//int s1_initial_context_setup_failure 
//int s1_paging 
//int s1_downlink_nas_transport 
//int s1_initial_ue_message 
//int s1_uplink_nas_transport 
//int s1_reset 
//int s1_reset_ack 
//int s1_error_indication 
//int s1_nas_non_delivery_indication 
//int s1_setup_request 
//int s1_setup_response 
//int s1_setup_failure 
//int s1_downlink_s1_cdma2000_tunnelling 
//int s1_uplink_s1_cdma2000_tunnelling 
//int s1_ue_context_modification_request 
//int s1_ue_context_modification_response 
//int s1_ue_context_modification_failure 
//int s1_ue_capability_info_indication 
//int s1_ue_context_release_request 
//int s1_ue_context_release_command 
//int s1_ue_context_release_complete 
//int s1_enb_status_transfer 
//int s1_mme_status_transfer 
//int s1_deactivate_trace 
//int s1_trace_start 
//int s1_trace_failure_indication 
//int s1_enb_configuration_update 
//int s1_enb_configuration_update_ack 
//int s1_enb_configuration_update_failure 
//int s1_mme_configuration_update 
//int s1_mme_configuration_update_ack 
//int s1_mme_configuration_update_failure 
//int s1_location_reporting_control 
//int s1_location_reporting_failure_indication 
//int s1_location_report 
//int s1_overload_start 
//int s1_overload_stop 
//int s1_write_replace_warning_request 
//int s1_write_replace_warning_response 
//int s1_enb_direct_information_transfer 
//int s1_mme_direct_information_transfer 
//int s1_private_message 
//int s1_enb_configuration_transfer 
//int s1_mme_configuration_transfer 
//int s1_cell_traffic_trace 
//int s1_kill_request 
//int s1_kill_response 
//int s1_downlink_ue_associated_lppa_transport 
//int s1_uplink_ue_associated_lppa_transport 
//int s1_downlink_non_ue_associated_lppa_transport 
//int s1_uplink_non_ue_associated_lppa_transport 
//int s1_ue_radio_capability_match_request 
//int s1_ue_radio_capability_match_response 
//int s1_pws_restart_indication 
//int s1_erab_modification_indication 
//int s1_erab_modification_confirm 
//int s1_pws_failure_indication 
//int s1_reroute_nas_request 
//int s1_ue_context_modification_indication 
//int s1_ue_context_modification_confirm 
//int s1_connection_establishment_indication 
//int s1_ue_context_suspend_request 
//int s1_ue_context_suspend_response 
//int s1_ue_context_resume_request 
//int s1_ue_context_resume_response 
//int s1_ue_context_resume_failure 
//int s1_nas_delivery_indication 
//int s1_retrieve_ue_information 
//int s1_ue_information_transfer 
//int s1_enb_cp_relocation_indication 
//int s1_mme_cp_relocation_indication 
//int s1_secondary_rat_data_usage_report 
//int s1_ue_radio_capability_id_mapping_request 
//int s1_ue_radio_capability_id_mapping_response 
//int s1_handover_success 
//int s1_enb_early_status_transfer 
//int s1_mme_early_status_transfer 
//int x2_handover_request_sent 
//int x2_handover_request_recv 
//int x2_handover_request_ack_sent 
//int x2_handover_request_ack_recv 
//int x2_handover_preparation_failure_sent 
//int x2_handover_preparation_failure_recv 
//int x2_handover_cancel_sent 
//int x2_handover_cancel_recv 
//int x2_load_indication_sent 
//int x2_load_indication_recv 
//int x2_error_indication_sent 
//int x2_error_indication_recv 
//int x2_sn_status_transfer_sent 
//int x2_sn_status_transfer_recv 
//int x2_ue_context_release_sent 
//int x2_ue_context_release_recv 
//int x2_setup_request_sent 
//int x2_setup_request_recv 
//int x2_setup_response_sent 
//int x2_setup_response_recv 
//int x2_setup_failure_sent 
//int x2_setup_failure_recv 
//int x2_reset_sent 
//int x2_reset_recv 
//int x2_reset_response_sent 
//int x2_reset_response_recv 
//int x2_enb_configuration_update_sent 
//int x2_enb_configuration_update_recv 
//int x2_enb_configuration_update_ack_sent 
//int x2_enb_configuration_update_ack_recv 
//int x2_enb_configuration_update_failure_sent 
//int x2_enb_configuration_update_failure_recv 
//int x2_resource_status_request_sent 
//int x2_resource_status_request_recv 
//int x2_resource_status_response_sent 
//int x2_resource_status_response_recv 
//int x2_resource_status_failure_sent 
//int x2_resource_status_failure_recv 
//int x2_resource_status_update_sent 
//int x2_resource_status_update_recv 
//int x2_private_message_sent 
//int x2_private_message_recv 
//int x2_mobility_change_request_sent 
//int x2_mobility_change_request_recv 
//int x2_mobility_change_ack_sent 
//int x2_mobility_change_ack_recv 
//int x2_mobility_change_failure_sent 
//int x2_mobility_change_failure_recv 
//int x2_rlf_indication_sent 
//int x2_rlf_indication_recv 
//int x2_handover_report_sent 
//int x2_handover_report_recv 
//int x2_cell_activation_request_sent 
//int x2_cell_activation_request_recv 
//int x2_cell_activation_response_sent 
//int x2_cell_activation_response_recv 
//int x2_cell_activation_failure_sent 
//int x2_cell_activation_failure_recv 
//int x2_release_sent 
//int x2_release_recv 
//int x2_message_transfer_sent 
//int x2_message_transfer_recv 
//int x2_removal_request_sent 
//int x2_removal_request_recv 
//int x2_removal_response_sent 
//int x2_removal_response_recv 
//int x2_removal_failure_sent 
//int x2_removal_failure_recv 
//int x2_senb_addition_request_sent 
//int x2_senb_addition_request_recv 
//int x2_senb_addition_request_acknowledge_sent 
//int x2_senb_addition_request_acknowledge_recv 
//int x2_senb_addition_request_reject_sent 
//int x2_senb_addition_request_reject_recv 
//int x2_senb_reconfiguration_complete_sent 
//int x2_senb_reconfiguration_complete_recv 
//int x2_senb_modification_request_sent 
//int x2_senb_modification_request_recv 
//int x2_senb_modification_request_acknowledge_sent 
//int x2_senb_modification_request_acknowledge_recv 
//int x2_senb_modification_request_reject_sent 
//int x2_senb_modification_request_reject_recv 
//int x2_senb_modification_required_sent 
//int x2_senb_modification_required_recv 
//int x2_senb_modification_confirm_sent 
//int x2_senb_modification_confirm_recv 
//int x2_senb_modification_refuse_sent 
//int x2_senb_modification_refuse_recv 
//int x2_senb_release_request_sent 
//int x2_senb_release_request_recv 
//int x2_senb_release_required_sent 
//int x2_senb_release_required_recv 
//int x2_senb_release_confirm_sent 
//int x2_senb_release_confirm_recv 
//int x2_senb_counter_check_request_sent 
//int x2_senb_counter_check_request_recv 
//int x2_retrieve_ue_context_request_sent 
//int x2_retrieve_ue_context_request_recv 
//int x2_retrieve_ue_context_response_sent 
//int x2_retrieve_ue_context_response_recv 
//int x2_retrieve_ue_context_failure_sent 
//int x2_retrieve_ue_context_failure_recv 
//int x2_sgnb_addition_request_sent 
//int x2_sgnb_addition_request_recv 
//int x2_sgnb_addition_request_acknowledge_sent 
//int x2_sgnb_addition_request_acknowledge_recv 
//int x2_sgnb_addition_request_reject_sent 
//int x2_sgnb_addition_request_reject_recv 
//int x2_sgnb_reconfiguration_complete_sent 
//int x2_sgnb_reconfiguration_complete_recv 
//int x2_sgnb_modification_request_sent 
//int x2_sgnb_modification_request_recv 
//int x2_sgnb_modification_request_acknowledge_sent 
//int x2_sgnb_modification_request_acknowledge_recv 
//int x2_sgnb_modification_request_reject_sent 
//int x2_sgnb_modification_request_reject_recv 
//int x2_sgnb_modification_required_sent 
//int x2_sgnb_modification_required_recv 
//int x2_sgnb_modification_confirm_sent 
//int x2_sgnb_modification_confirm_recv 
//int x2_sgnb_modification_refuse_sent 
//int x2_sgnb_modification_refuse_recv 
//int x2_sgnb_release_request_sent 
//int x2_sgnb_release_request_recv 
//int x2_sgnb_release_request_acknowledge_sent 
//int x2_sgnb_release_request_acknowledge_recv 
//int x2_sgnb_release_request_reject_sent 
//int x2_sgnb_release_request_reject_recv 
//int x2_sgnb_release_required_sent 
//int x2_sgnb_release_required_recv 
//int x2_sgnb_release_confirm_sent 
//int x2_sgnb_release_confirm_recv 
//int x2_sgnb_counter_check_request_sent 
//int x2_sgnb_counter_check_request_recv 
//int x2_sgnb_change_required_sent 
//int x2_sgnb_change_required_recv 
//int x2_sgnb_change_confirm_sent 
//int x2_sgnb_change_confirm_recv 
//int x2_sgnb_change_refuse_sent 
//int x2_sgnb_change_refuse_recv 
//int x2_rrc_transfer_sent 
//int x2_rrc_transfer_recv 
//int x2_endc_x2_setup_request_sent 
//int x2_endc_x2_setup_request_recv 
//int x2_endc_x2_setup_response_sent 
//int x2_endc_x2_setup_response_recv 
//int x2_endc_x2_setup_failure_sent 
//int x2_endc_x2_setup_failure_recv 
//int x2_endc_configuration_update_sent 
//int x2_endc_configuration_update_recv 
//int x2_endc_configuration_update_acknowledge_sent 
//int x2_endc_configuration_update_acknowledge_recv 
//int x2_endc_configuration_update_failure_sent 
//int x2_endc_configuration_update_failure_recv 
//int x2_secondary_rat_data_usage_report_sent 
//int x2_secondary_rat_data_usage_report_recv 
//int x2_endc_cell_activation_request_sent 
//int x2_endc_cell_activation_request_recv 
//int x2_endc_cell_activation_response_sent 
//int x2_endc_cell_activation_response_recv 
//int x2_endc_cell_activation_failure_sent 
//int x2_endc_cell_activation_failure_recv 
//int x2_endc_partial_reset_required_sent 
//int x2_endc_partial_reset_required_recv 
//int x2_endc_partial_reset_confirm_sent 
//int x2_endc_partial_reset_confirm_recv 
//int x2_endc_eutran_nr_cell_resource_coordination_request_sent 
//int x2_endc_eutran_nr_cell_resource_coordination_request_recv 
//int x2_endc_eutran_nr_cell_resource_coordination_response_sent 
//int x2_endc_eutran_nr_cell_resource_coordination_response_recv 
//int x2_sgnb_activity_notification_sent 
//int x2_sgnb_activity_notification_recv 
//int x2_endc_x2_removal_request_sent 
//int x2_endc_x2_removal_request_recv 
//int x2_endc_x2_removal_response_sent 
//int x2_endc_x2_removal_response_recv 
//int x2_endc_x2_removal_failure_sent 
//int x2_endc_x2_removal_failure_recv 
//int x2_data_forwarding_address_indication_sent 
//int x2_data_forwarding_address_indication_recv 
//int x2_gnb_status_indication_sent 
//int x2_gnb_status_indication_recv 
//int x2_deactivate_trace_sent 
//int x2_deactivate_trace_recv 
//int x2_trace_start_sent 
//int x2_trace_start_recv 
//int x2_endc_configuration_transfer_sent 
//int x2_endc_configuration_transfer_recv 
//int x2_handover_success_sent 
//int x2_handover_success_recv 
//int x2_conditional_handover_cancel_sent 
//int x2_conditional_handover_cancel_recv 
//int x2_early_status_transfer_sent 
//int x2_early_status_transfer_recv 
//int x2_cell_traffic_trace_sent 
//int x2_cell_traffic_trace_recv 
//int x2_endc_resource_status_update_sent 
//int x2_endc_resource_status_update_recv 
//int x2_endc_resource_status_request_sent 
//int x2_endc_resource_status_request_recv 
//int x2_endc_resource_status_response_sent 
//int x2_endc_resource_status_response_recv 
//int x2_endc_resource_status_failure_sent 
//int x2_endc_resource_status_failure_recv 
//int x2_f1c_traffic_transfer_sent 
//int x2_f1c_traffic_transfer_recv 
//int x2_ue_radio_capability_id_mapping_request_sent 
//int x2_ue_radio_capability_id_mapping_request_recv 
//int x2_ue_radio_capability_id_mapping_response_sent 
//int x2_ue_radio_capability_id_mapping_response_recv 
//int x2_access_and_mobility_indication_sent 
//int x2_access_and_mobility_indication_recv 
//int x2_cpc_cancel_sent 
//int x2_cpc_cancel_recv 
//int ng_amf_configuration_update 
//int ng_amf_configuration_update_acknowledge 
//int ng_amf_configuration_update_failure 
//int ng_amf_status_indication 
//int ng_cell_traffic_trace 
//int ng_deactivate_trace 
//int ng_downlink_nas_transport 
//int ng_downlink_non_ue_associated_nrppa_transport 
//int ng_downlink_ran_configuration_transfer 
//int ng_downlink_ran_status_transfer 
//int ng_downlink_ue_associated_nrppa_transport 
//int ng_error_indication 
//int ng_handover_cancel 
//int ng_handover_cancel_acknowledge 
//int ng_handover_notify 
//int ng_handover_required 
//int ng_handover_command 
//int ng_handover_preparation_failure 
//int ng_handover_request 
//int ng_handover_request_acknowledge 
//int ng_handover_failure 
//int ng_initial_context_setup_request 
//int ng_initial_context_setup_response 
//int ng_initial_context_setup_failure 
//int ng_initial_ue_message 
//int ng_location_reporting_control 
//int ng_location_reporting_failure_indication 
//int ng_location_report 
//int ng_nas_non_delivery_indication 
//int ng_reset 
//int ng_reset_acknowledge 
//int ng_setup_request 
//int ng_setup_response 
//int ng_setup_failure 
//int ng_overload_start 
//int ng_overload_stop 
//int ng_paging 
//int ng_path_switch_request 
//int ng_path_switch_request_acknowledge 
//int ng_path_switch_request_failure 
//int ng_pdu_session_resource_modify_request 
//int ng_pdu_session_resource_modify_response 
//int ng_pdu_session_resource_modify_indication 
//int ng_pdu_session_resource_modify_confirm 
//int ng_pdu_session_resource_release_command 
//int ng_pdu_session_resource_release_response 
//int ng_pdu_session_resource_setup_request 
//int ng_pdu_session_resource_setup_response 
//int ng_pdu_session_resource_notify 
//int ng_private_message 
//int ng_pws_cancel_request 
//int ng_pws_cancel_response 
//int ng_pws_failure_indication 
//int ng_pws_restart_indication 
//int ng_ran_configuration_update 
//int ng_ran_configuration_update_acknowledge 
//int ng_ran_configuration_update_failure 
//int ng_reroute_nas_request 
//int ng_rrc_inactive_transition_report 
//int ng_trace_failure_indication 
//int ng_trace_start 
//int ng_ue_context_modification_request 
//int ng_ue_context_modification_response 
//int ng_ue_context_modification_failure 
//int ng_ue_context_release_command 
//int ng_ue_context_release_complete 
//int ng_ue_context_release_request 
//int ng_ue_radio_capability_check_request 
//int ng_ue_radio_capability_check_response 
//int ng_ue_radio_capability_info_indication 
//int ng_ue_tnla_binding_release_request 
//int ng_uplink_nas_transport 
//int ng_uplink_non_ue_associated_nrppa_transport 
//int ng_uplink_ran_configuration_transfer 
//int ng_uplink_ran_status_transfer 
//int ng_uplink_ue_associated_nrppa_transport 
//int ng_write_replace_warning_request 
//int ng_write_replace_warning_response 
//int ng_secondary_rat_data_usage_report 
//int ng_uplink_rim_information_transfer 
//int ng_downlink_rim_information_transfer 
//int ng_retrieve_ue_information 
//int ng_ue_information_transfer 
//int ng_ran_cp_relocation_indication 
//int ng_ue_context_resume_request 
//int ng_ue_context_resume_response 
//int ng_ue_context_resume_failure 
//int ng_ue_context_suspend_request 
//int ng_ue_context_suspend_response 
//int ng_ue_context_suspend_failure 
//int ng_ue_radio_capability_id_mapping_request 
//int ng_ue_radio_capability_id_mapping_response 
//int ng_handover_success 
//int ng_uplink_ran_early_status_transfer 
//int ng_downlink_ran_early_status_transfer 
//int ng_amf_cp_relocation_indication 
//int ng_connection_establishment_indication 
//int ng_broadcast_session_modification_request 
//int ng_broadcast_session_modification_response 
//int ng_broadcast_session_modification_failure 
//int ng_broadcast_session_release_request 
//int ng_broadcast_session_release_response 
//int ng_broadcast_session_setup_request 
//int ng_broadcast_session_setup_response 
//int ng_broadcast_session_setup_failure 
//int ng_distribution_setup_request 
//int ng_distribution_setup_response 
//int ng_distribution_setup_failure 
//int ng_distribution_release_request 
//int ng_distribution_release_response 
//int ng_multicast_session_activation_request 
//int ng_multicast_session_activation_response 
//int ng_multicast_session_activation_failure 
//int ng_multicast_session_deactivation_request 
//int ng_multicast_session_deactivation_response 
//int ng_multicast_session_update_request 
//int ng_multicast_session_update_response 
//int ng_multicast_session_update_failure 
//int ng_multicast_group_paging 
//int ng_broadcast_session_release_required 
//int xn_handover_request_sent 
//int xn_handover_request_recv 
//int xn_handover_request_acknowledge_sent 
//int xn_handover_request_acknowledge_recv 
//int xn_handover_preparation_failure_sent 
//int xn_handover_preparation_failure_recv 
//int xn_sn_status_transfer_sent 
//int xn_sn_status_transfer_recv 
//int xn_handover_cancel_sent 
//int xn_handover_cancel_recv 
//int xn_retrieve_ue_context_sent 
//int xn_retrieve_ue_context_recv 
//int xn_retrieve_ue_context_response_sent 
//int xn_retrieve_ue_context_response_recv 
//int xn_retrieve_ue_context_failure_sent 
//int xn_retrieve_ue_context_failure_recv 
//int xn_ran_paging_sent 
//int xn_ran_paging_recv 
//int xn_u_address_indication_sent 
//int xn_u_address_indication_recv 
//int xn_ue_context_release_sent 
//int xn_ue_context_release_recv 
//int xn_s_node_addition_request_sent 
//int xn_s_node_addition_request_recv 
//int xn_s_node_addition_request_acknowledge_sent 
//int xn_s_node_addition_request_acknowledge_recv 
//int xn_s_node_addition_request_reject_sent 
//int xn_s_node_addition_request_reject_recv 
//int xn_s_node_reconfiguration_complete_sent 
//int xn_s_node_reconfiguration_complete_recv 
//int xn_s_node_modification_request_sent 
//int xn_s_node_modification_request_recv 
//int xn_s_node_modification_request_acknowledge_sent 
//int xn_s_node_modification_request_acknowledge_recv 
//int xn_s_node_modification_request_reject_sent 
//int xn_s_node_modification_request_reject_recv 
//int xn_s_node_modification_required_sent 
//int xn_s_node_modification_required_recv 
//int xn_s_node_modification_confirm_sent 
//int xn_s_node_modification_confirm_recv 
//int xn_s_node_modification_refuse_sent 
//int xn_s_node_modification_refuse_recv 
//int xn_s_node_release_request_sent 
//int xn_s_node_release_request_recv 
//int xn_s_node_release_request_acknowledge_sent 
//int xn_s_node_release_request_acknowledge_recv 
//int xn_s_node_release_reject_sent 
//int xn_s_node_release_reject_recv 
//int xn_s_node_release_required_sent 
//int xn_s_node_release_required_recv 
//int xn_s_node_release_confirm_sent 
//int xn_s_node_release_confirm_recv 
//int xn_s_node_counter_check_request_sent 
//int xn_s_node_counter_check_request_recv 
//int xn_s_node_change_required_sent 
//int xn_s_node_change_required_recv 
//int xn_s_node_change_confirm_sent 
//int xn_s_node_change_confirm_recv 
//int xn_s_node_change_refuse_sent 
//int xn_s_node_change_refuse_recv 
//int xn_rrc_transfer_sent 
//int xn_rrc_transfer_recv 
//int xn_removal_request_sent 
//int xn_removal_request_recv 
//int xn_removal_response_sent 
//int xn_removal_response_recv 
//int xn_removal_failure_sent 
//int xn_removal_failure_recv 
//int xn_setup_request_sent 
//int xn_setup_request_recv 
//int xn_setup_response_sent 
//int xn_setup_response_recv 
//int xn_setup_failure_sent 
//int xn_setup_failure_recv 
//int xn_ng_ran_node_configuration_update_sent 
//int xn_ng_ran_node_configuration_update_recv 
//int xn_ng_ran_node_configuration_update_acknowledge_sent 
//int xn_ng_ran_node_configuration_update_acknowledge_recv 
//int xn_ng_ran_node_configuration_update_failure_sent 
//int xn_ng_ran_node_configuration_update_failure_recv 
//int xn_cell_activation_request_sent 
//int xn_cell_activation_request_recv 
//int xn_cell_activation_response_sent 
//int xn_cell_activation_response_recv 
//int xn_cell_activation_failure_sent 
//int xn_cell_activation_failure_recv 
//int xn_reset_request_sent 
//int xn_reset_request_recv 
//int xn_reset_response_sent 
//int xn_reset_response_recv 
//int xn_error_indication_sent 
//int xn_error_indication_recv 
//int xn_private_message_sent 
//int xn_private_message_recv 
//int xn_notification_control_indication_sent 
//int xn_notification_control_indication_recv 
//int xn_activity_notification_sent 
//int xn_activity_notification_recv 
//int xn_eutra_nr_cell_resource_coordination_request_sent 
//int xn_eutra_nr_cell_resource_coordination_request_recv 
//int xn_eutra_nr_cell_resource_coordination_response_sent 
//int xn_eutra_nr_cell_resource_coordination_response_recv 
//int xn_secondary_rat_data_usage_report_sent 
//int xn_secondary_rat_data_usage_report_recv 
//int xn_deactivate_trace_sent 
//int xn_deactivate_trace_recv 
//int xn_trace_start_sent 
//int xn_trace_start_recv 
//int xn_handover_success_sent 
//int xn_handover_success_recv 
//int xn_conditional_handover_cancel_sent 
//int xn_conditional_handover_cancel_recv 
//int xn_early_status_transfer_sent 
//int xn_early_status_transfer_recv 
//int xn_failure_indication_sent 
//int xn_failure_indication_recv 
//int xn_handover_report_sent 
//int xn_handover_report_recv 
//int xn_resource_status_request_sent 
//int xn_resource_status_request_recv 
//int xn_resource_status_response_sent 
//int xn_resource_status_response_recv 
//int xn_resource_status_failure_sent 
//int xn_resource_status_failure_recv 
//int xn_resource_status_update_sent 
//int xn_resource_status_update_recv 
//int xn_mobility_change_request_sent 
//int xn_mobility_change_request_recv 
//int xn_mobility_change_acknowledge_sent 
//int xn_mobility_change_acknowledge_recv 
//int xn_mobility_change_failure_sent 
//int xn_mobility_change_failure_recv 
//int xn_access_and_mobility_indication_sent 
//int xn_access_and_mobility_indication_recv 
//int xn_cell_traffic_class_sent 
//int xn_cell_traffic_class_recv 
//int xn_ran_multicast_group_paging_sent 
//int xn_ran_multicast_group_paging_recv 
//int xn_scg_failure_information_report_sent 
//int xn_scg_failure_information_report_recv 
//int xn_scg_failure_transfer_sent 
//int xn_scg_failure_transfer_recv 
//int xn_f1c_traffic_transfer_sent 
//int xn_f1c_traffic_transfer_recv 
//int xn_iab_transport_migration_management_request_sent 
//int xn_iab_transport_migration_management_request_recv 
//int xn_iab_transport_migration_management_response_sent 
//int xn_iab_transport_migration_management_response_recv 
//int xn_iab_transport_migration_management_reject_sent 
//int xn_iab_transport_migration_management_reject_recv 
//int xn_iab_transport_migration_modification_request_sent 
//int xn_iab_transport_migration_modification_request_recv 
//int xn_iab_transport_migration_modification_response_sent 
//int xn_iab_transport_migration_modification_response_recv 
//int xn_iab_resource_coordination_request_sent 
//int xn_iab_resource_coordination_request_recv 
//int xn_iab_resource_coordination_response_sent 
//int xn_iab_resource_coordination_response_recv 
//int xn_retrieve_ue_context_confirm_sent 
//int xn_retrieve_ue_context_confirm_recv 
//int xn_cpc_cancel_sent 
//int xn_cpc_cancel_recv 
//int xn_partial_ue_context_transfer_sent 
//int xn_partial_ue_context_transfer_recv 
//int xn_partial_ue_context_transfer_acknowledge_sent 
//int xn_partial_ue_context_transfer_acknowledge_recv 
//int xn_partial_ue_context_transfer_failure_sent 
//int xn_partial_ue_context_transfer_failure_recv 
//int m2_session_start_request 
//int m2_session_start_response 
//int m2_session_start_failure 
//int m2_session_stop_request 
//int m2_session_stop_response 
//int m2_mbms_scheduling_information 
//int m2_mbms_scheduling_information_response 
//int m2_error_indication 
//int m2_reset 
//int m2_reset_acknowledge 
//int m2_m2_setup_request 
//int m2_m2_setup_response 
//int m2_m2_setup_failure 
//int m2_enb_configuration_update 
//int m2_enb_configuration_update_acknowledge 
//int m2_enb_configuration_update_failure 
//int m2_mce_configuration_update 
//int m2_mce_configuration_update_acknowledge 
//int m2_mce_configuration_update_failure 
//int m2_private_message 
//int m2_session_update_request 
//int m2_session_update_response 
//int m2_session_update_failure 
//int m2_mbms_service_counting_request 
//int m2_mbms_service_counting_response 
//int m2_mbms_service_counting_failure 
//int m2_mbms_service_counting_results_report 
//int m2_mbms_overload_notification 
//int lppa_asn1_decode_error 
//int lppa_error_indication 
//int lppa_private_message 
//int lppa_ecid_measurement_initiation_request 
//int lppa_ecid_measurement_failure_indication 
//int lppa_ecid_measurement_report 
//int lppa_ecid_measurement_termination 
//int lppa_otdoa_information_request 
//int lppa_utdoa_information_request 
//int lppa_utdoa_information_update 
//int lppa_assistance_information_control 
//int lppa_assistance_information_feedback 
//int lppa_ecid_measurement_initiation_response 
//int lppa_otdoa_information_response 
//int lppa_utdoa_information_response 
//int lppa_ecid_measurement_initiation_failure 
//int lppa_otdoa_information_failure 
//int lppa_utdoa_information_failure 
//int nrppa_asn1_decode_error 
//int nrppa_ecid_measurement_initiation_request 
//int nrppa_ecid_measurement_failure_indication 
//int nrppa_ecid_measurement_report 
//int nrppa_ecid_measurement_termination 
//int nrppa_otdoa_information_exchange 
//int nrppa_assistance_information_control 
//int nrppa_assistance_information_feedback 
//int nrppa_error_indication 
//int nrppa_private_message 
//int nrppa_positioning_information_exchange 
//int nrppa_positioning_information_update 
//int nrppa_measurement_request 
//int nrppa_measurement_report 
//int nrppa_measurement_update 
//int nrppa_measurement_abort 
//int nrppa_measurement_failure_indication 
//int nrppa_trp_information_exchange 
//int nrppa_positioning_activation_request 
//int nrppa_positioning_deactivation_request 
//int nrppa_ecid_measurement_initiation_response 
//int nrppa_otdoa_information_response 
//int nrppa_positioning_information_response 
//int nrppa_measurement_response 
//int nrppa_trp_information_response 
//int nrppa_positioning_activation_response 
//int nrppa_ecid_measurement_failure 
//int nrppa_otdoa_information_failure 
//int nrppa_positioning_information_failure 
//int nrppa_measurement_failure 
//int nrppa_trp_information_failure 
//int nrppa_positioning_activation_failure
//
//// # Cell 1 events : 
//// Message events : 
//int prach 
//int handover_command 
//int handover_preparation 
//int handover_source_success 
//int handover_target_success 
//int nr_scg_reconf_with_sync_success 
//int rrc_connection_request 
//int rrc_connection_reject 
//int rrc_connection_setup 
//int rrc_connection_setup_complete 
//int rrc_ul_information_transfer 
//int rrc_dl_information_transfer 
//int rrc_security_mode_command 
//int rrc_security_mode_complete 
//int rrc_security_mode_failure 
//int rrc_ue_capability_enquiry 
//int rrc_ue_capability_information 
//int rrc_connection_reconfiguration 
//int rrc_connection_reconfiguration_complete 
//int rrc_connection_reestablishment_request 
//int rrc_connection_reestablishment_reject 
//int rrc_connection_reestablishment 
//int rrc_connection_reestablishment_complete 
//int rrc_measurement_report 
//int rrc_connection_release 
//int rrc_ue_information_request 
//int rrc_ue_information_response 
//int rrc_connection_resume_request 
//int rrc_csfb_parameters_response_cdma2000 
//int rrc_handover_from_eutra_preparation_request 
//int rrc_mobility_from_eutra_command 
//int rrc_counter_check 
//int rrc_logged_measurement_configuration 
//int rrc_rn_reconfiguration 
//int rrc_connection_resume 
//int rrc_dl_dedicated_message_segment 
//int rrc_csfb_parameters_request_cdma2000 
//int rrc_ul_handover_preparation_transfer 
//int rrc_counter_check_response 
//int rrc_proximity_indication 
//int rrc_rn_reconfiguration_complete 
//int rrc_mbms_counting_response 
//int rrc_inter_freq_rstd_measurement_indication 
//int rrc_ue_assistance_information 
//int rrc_in_device_coex_indication 
//int rrc_mbms_interest_indication 
//int rrc_scg_failure_information 
//int rrc_sidelink_ue_information 
//int rrc_wlan_connection_status_report 
//int rrc_connection_resume_complete 
//int rrc_ul_information_transfer_mrdc 
//int rrc_scg_failure_information_nr 
//int rrc_measurement_report_application_layer 
//int rrc_failure_information 
//int rrc_ul_dedicated_message_segment 
//int rrc_pur_configuration_request 
//int rrc_failure_information_r16 
//int rrc_mcg_failure_information 
//int rrc_ul_information_transfer_irat 
//int rrc_early_data_request 
//int rrc_early_data_complete 
//int rrc_paging 
//int rrc_connection_reestablishment_nb 
//int rrc_connection_reestablishment_reject_nb 
//int rrc_connection_reject_nb 
//int rrc_connection_setup_nb 
//int rrc_dl_information_transfer_nb 
//int rrc_connection_reconfiguration_nb 
//int rrc_connection_release_nb 
//int rrc_security_mode_command_nb 
//int rrc_ue_capability_enquiry_nb 
//int rrc_connection_resume_nb 
//int rrc_ue_information_request_nb 
//int rrc_connection_reestablishment_request_nb 
//int rrc_connection_request_nb 
//int rrc_connection_resume_request_nb 
//int rrc_connection_reconfiguration_complete_nb 
//int rrc_connection_reestablishment_complete_nb 
//int rrc_connection_setup_complete_nb 
//int rrc_security_mode_complete_nb 
//int rrc_security_mode_failure_nb 
//int rrc_ue_capability_information_nb 
//int rrc_ul_information_transfer_nb 
//int rrc_connection_resume_complete_nb 
//int rrc_ue_information_response_nb 
//int rrc_pur_configuration_request_nb 
//int rrc_early_data_request_nb 
//int rrc_early_data_complete_nb 
//int rrc_paging_nb 
//int nr_rrc_reject 
//int nr_rrc_setup 
//int nr_rrc_setup_request 
//int nr_rrc_resume_request 
//int nr_rrc_reestablishment_request 
//int nr_rrc_system_info_request 
//int nr_rrc_resume_request_1 
//int nr_rrc_reconfiguration 
//int nr_rrc_resume 
//int nr_rrc_release 
//int nr_rrc_reestablishment 
//int nr_rrc_security_mode_command 
//int nr_rrc_dl_information_transfer 
//int nr_rrc_ue_capability_enquiry 
//int nr_rrc_counter_check 
//int nr_rrc_mobility_from_nr_command 
//int nr_rrc_dl_dedicated_message_segment 
//int nr_rrc_ue_information_request 
//int nr_rrc_dl_information_transfer_mrdc 
//int nr_rrc_logged_measurement_configuration 
//int nr_rrc_measurement_report 
//int nr_rrc_reconfiguration_complete 
//int nr_rrc_setup_complete 
//int nr_rrc_reestablishment_complete 
//int nr_rrc_resume_complete 
//int nr_rrc_security_mode_complete 
//int nr_rrc_security_mode_failure 
//int nr_rrc_ul_information_transfer 
//int nr_rrc_location_measurement_indication 
//int nr_rrc_ue_capability_information 
//int nr_rrc_counter_check_response 
//int nr_rrc_ue_assistance_information 
//int nr_rrc_failure_information 
//int nr_rrc_ul_information_transfer_mrdc 
//int nr_rrc_scg_failure_information 
//int nr_rrc_scg_failure_information_eutra 
//int nr_rrc_ul_dedicated_message_segment 
//int nr_rrc_dedicated_sib_request 
//int nr_rrc_mcg_failure_information 
//int nr_rrc_ue_information_response 
//int nr_rrc_sidelink_ue_information_nr 
//int nr_rrc_ul_information_transfer_irat 
//int nr_rrc_iab_other_information 
//int nr_rrc_mbs_interest_indication 
//int nr_rrc_ue_positioning_assistance_info 
//int nr_rrc_measurement_report_app_layer 
//int nr_rrc_paging

} cnt_msgs_amr_t;

void free_cnt_msgs_amr(cnt_msgs_amr_t* src);


#endif
