/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

struct errors {
};

struct cell_counters {
    hashtable_t * messages;
    struct errors * errors;
};

struct cell {
    int64_t dl_bitrate;
    int64_t ul_bitrate;
    int64_t dl_tx;
    int64_t ul_tx;
    int64_t dl_err;
    int64_t ul_err;
    int64_t dl_retx;
    int64_t ul_retx;
    int64_t dl_use_min;
    double dl_use_max;
    double dl_use_avg;
    double ul_use_min;
    double ul_use_max;
    double ul_use_avg;
    int64_t dl_sched_users_min;
    int64_t dl_sched_users_max;
    double dl_sched_users_avg;
    int64_t ul_sched_users_min;
    int64_t ul_sched_users_max;
    double ul_sched_users_avg;
    int64_t ue_count_min;
    int64_t ue_count_max;
    int64_t ue_count_avg;
    int64_t ue_active_count_min;
    int64_t ue_active_count_max;
    int64_t ue_active_count_avg;
    int64_t ue_inactive_count_min;
    int64_t ue_inactive_count_max;
    int64_t ue_inactive_count_avg;
    int64_t drb_count_min;
    int64_t drb_count_max;
    int64_t drb_count_avg;
    int64_t dl_gbr_use_min;
    int64_t dl_gbr_use_max;
    int64_t dl_gbr_use_avg;
    int64_t ul_gbr_use_min;
    int64_t ul_gbr_use_max;
    int64_t ul_gbr_use_avg;
    struct cell_counters * counters;
};

struct messages {
    int64_t ng_setup_request;
    int64_t ng_setup_failure;
};

struct msg_stats_counters {
    struct messages * messages;
    struct errors * errors;
};

struct cpu {
    int64_t global;
};

struct rxtx_delay {
    double min;
    double max;
    double avg;
    double sd;
};

struct the_0 {
    struct rxtx_delay * rxtx_delay;
};

struct rf_ports {
    struct the_0 * the_0;
};

struct msg_stats {
    char * message;
    int64_t message_id;
    char * instance_id;
    struct cpu * cpu;
    int64_t gtp_rx_bitrate;
    int64_t gtp_tx_bitrate;
    hashtable_t * cells;
    struct rf_ports * rf_ports;
    struct msg_stats_counters * counters;
    double duration;
    double time;
    double utc;
};

struct errors * cJSON_Parseerrors(const char * s);
struct errors * cJSON_GeterrorsValue(const cJSON * j);
cJSON * cJSON_Createerrors(const struct errors * x);
char * cJSON_Printerrors(const struct errors * x);
void cJSON_Deleteerrors(struct errors * x);

struct cell_counters * cJSON_Parsecell_counters(const char * s);
struct cell_counters * cJSON_Getcell_countersValue(const cJSON * j);
cJSON * cJSON_Createcell_counters(const struct cell_counters * x);
char * cJSON_Printcell_counters(const struct cell_counters * x);
void cJSON_Deletecell_counters(struct cell_counters * x);

struct cell * cJSON_Parsecell(const char * s);
struct cell * cJSON_GetcellValue(const cJSON * j);
cJSON * cJSON_Createcell(const struct cell * x);
char * cJSON_Printcell(const struct cell * x);
void cJSON_Deletecell(struct cell * x);

struct messages * cJSON_Parsemessages(const char * s);
struct messages * cJSON_GetmessagesValue(const cJSON * j);
cJSON * cJSON_Createmessages(const struct messages * x);
char * cJSON_Printmessages(const struct messages * x);
void cJSON_Deletemessages(struct messages * x);

struct msg_stats_counters * cJSON_Parsemsg_stats_counters(const char * s);
struct msg_stats_counters * cJSON_Getmsg_stats_countersValue(const cJSON * j);
cJSON * cJSON_Createmsg_stats_counters(const struct msg_stats_counters * x);
char * cJSON_Printmsg_stats_counters(const struct msg_stats_counters * x);
void cJSON_Deletemsg_stats_counters(struct msg_stats_counters * x);

struct cpu * cJSON_Parsecpu(const char * s);
struct cpu * cJSON_GetcpuValue(const cJSON * j);
cJSON * cJSON_Createcpu(const struct cpu * x);
char * cJSON_Printcpu(const struct cpu * x);
void cJSON_Deletecpu(struct cpu * x);

struct rxtx_delay * cJSON_Parserxtx_delay(const char * s);
struct rxtx_delay * cJSON_Getrxtx_delayValue(const cJSON * j);
cJSON * cJSON_Createrxtx_delay(const struct rxtx_delay * x);
char * cJSON_Printrxtx_delay(const struct rxtx_delay * x);
void cJSON_Deleterxtx_delay(struct rxtx_delay * x);

struct the_0 * cJSON_Parsethe_0(const char * s);
struct the_0 * cJSON_Getthe_0Value(const cJSON * j);
cJSON * cJSON_Createthe_0(const struct the_0 * x);
char * cJSON_Printthe_0(const struct the_0 * x);
void cJSON_Deletethe_0(struct the_0 * x);

struct rf_ports * cJSON_Parserf_ports(const char * s);
struct rf_ports * cJSON_Getrf_portsValue(const cJSON * j);
cJSON * cJSON_Createrf_ports(const struct rf_ports * x);
char * cJSON_Printrf_ports(const struct rf_ports * x);
void cJSON_Deleterf_ports(struct rf_ports * x);

struct msg_stats * cJSON_Parsemsg_stats(const char * s);
struct msg_stats * cJSON_Getmsg_statsValue(const cJSON * j);
cJSON * cJSON_Createmsg_stats(const struct msg_stats * x);
char * cJSON_Printmsg_stats(const struct msg_stats * x);
void cJSON_Deletemsg_stats(struct msg_stats * x);

struct errors * cJSON_Parseerrors(const char * s) {
    struct errors * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GeterrorsValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct errors * cJSON_GeterrorsValue(const cJSON * j) {
    struct errors * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct errors)))) {
            memset(x, 0, sizeof(struct errors));
        }
    }
    return x;
}

cJSON * cJSON_Createerrors(const struct errors * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
        }
    }
    return j;
}

char * cJSON_Printerrors(const struct errors * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createerrors(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deleteerrors(struct errors * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

struct cell_counters * cJSON_Parsecell_counters(const char * s) {
    struct cell_counters * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_Getcell_countersValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct cell_counters * cJSON_Getcell_countersValue(const cJSON * j) {
    struct cell_counters * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct cell_counters)))) {
            memset(x, 0, sizeof(struct cell_counters));
            if (cJSON_HasObjectItem(j, "messages")) {
                hashtable_t * x1 = hashtable_create(64, false);
                if (NULL != x1) {
                    cJSON * e1 = NULL;
                    cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "messages");
                    cJSON_ArrayForEach(e1, j1) {
                        int64_t * tmp = cJSON_malloc(sizeof(int64_t));
                        if (NULL != tmp) {
                            * tmp = cJSON_GetNumberValue(e1);
                            hashtable_add(x1, e1->string, tmp, sizeof(int64_t *));
                        }
                    }
                    x->messages = x1;
                }
            }
            else {
                x->messages = hashtable_create(64, false);
            }
            if (cJSON_HasObjectItem(j, "errors")) {
                x->errors = cJSON_GeterrorsValue(cJSON_GetObjectItemCaseSensitive(j, "errors"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createcell_counters(const struct cell_counters * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->messages) {
                cJSON * j1 = cJSON_CreateObject();
                if (NULL != j1) {
                    char **keys1 = NULL;
                    size_t count1 = hashtable_get_keys(x->messages, &keys1);
                    if (NULL != keys1) {
                        for (size_t index1 = 0; index1 < count1; index1++) {
                            int64_t *x1 = hashtable_lookup(x->messages, keys1[index1]);
                            cJSON_AddItemToObject(j1, keys1[index1], cJSON_CreateNumber(*x1));
                        }
                        cJSON_free(keys1);
                    }
                    cJSON_AddItemToObject(j, "messages", j1);
                }
            }
            cJSON_AddItemToObject(j, "errors", cJSON_Createerrors(x->errors));
        }
    }
    return j;
}

char * cJSON_Printcell_counters(const struct cell_counters * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createcell_counters(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deletecell_counters(struct cell_counters * x) {
    if (NULL != x) {
        if (NULL != x->messages) {
            char **keys1 = NULL;
            size_t count1 = hashtable_get_keys(x->messages, &keys1);
            if (NULL != keys1) {
                for (size_t index1 = 0; index1 < count1; index1++) {
                    int64_t *x1 = hashtable_lookup(x->messages, keys1[index1]);
                    if (NULL != x1) {
                        cJSON_free(x1);
                    }
                }
                cJSON_free(keys1);
            }
            hashtable_release(x->messages);
        }
        if (NULL != x->errors) {
            cJSON_Deleteerrors(x->errors);
        }
        cJSON_free(x);
    }
}

struct cell * cJSON_Parsecell(const char * s) {
    struct cell * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetcellValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct cell * cJSON_GetcellValue(const cJSON * j) {
    struct cell * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct cell)))) {
            memset(x, 0, sizeof(struct cell));
            if (cJSON_HasObjectItem(j, "dl_bitrate")) {
                x->dl_bitrate = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_bitrate"));
            }
            if (cJSON_HasObjectItem(j, "ul_bitrate")) {
                x->ul_bitrate = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_bitrate"));
            }
            if (cJSON_HasObjectItem(j, "dl_tx")) {
                x->dl_tx = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_tx"));
            }
            if (cJSON_HasObjectItem(j, "ul_tx")) {
                x->ul_tx = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_tx"));
            }
            if (cJSON_HasObjectItem(j, "dl_err")) {
                x->dl_err = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_err"));
            }
            if (cJSON_HasObjectItem(j, "ul_err")) {
                x->ul_err = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_err"));
            }
            if (cJSON_HasObjectItem(j, "dl_retx")) {
                x->dl_retx = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_retx"));
            }
            if (cJSON_HasObjectItem(j, "ul_retx")) {
                x->ul_retx = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_retx"));
            }
            if (cJSON_HasObjectItem(j, "dl_use_min")) {
                x->dl_use_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_use_min"));
            }
            if (cJSON_HasObjectItem(j, "dl_use_max")) {
                x->dl_use_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_use_max"));
            }
            if (cJSON_HasObjectItem(j, "dl_use_avg")) {
                x->dl_use_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_use_avg"));
            }
            if (cJSON_HasObjectItem(j, "ul_use_min")) {
                x->ul_use_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_use_min"));
            }
            if (cJSON_HasObjectItem(j, "ul_use_max")) {
                x->ul_use_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_use_max"));
            }
            if (cJSON_HasObjectItem(j, "ul_use_avg")) {
                x->ul_use_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_use_avg"));
            }
            if (cJSON_HasObjectItem(j, "dl_sched_users_min")) {
                x->dl_sched_users_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_sched_users_min"));
            }
            if (cJSON_HasObjectItem(j, "dl_sched_users_max")) {
                x->dl_sched_users_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_sched_users_max"));
            }
            if (cJSON_HasObjectItem(j, "dl_sched_users_avg")) {
                x->dl_sched_users_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_sched_users_avg"));
            }
            if (cJSON_HasObjectItem(j, "ul_sched_users_min")) {
                x->ul_sched_users_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_sched_users_min"));
            }
            if (cJSON_HasObjectItem(j, "ul_sched_users_max")) {
                x->ul_sched_users_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_sched_users_max"));
            }
            if (cJSON_HasObjectItem(j, "ul_sched_users_avg")) {
                x->ul_sched_users_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_sched_users_avg"));
            }
            if (cJSON_HasObjectItem(j, "ue_count_min")) {
                x->ue_count_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_count_min"));
            }
            if (cJSON_HasObjectItem(j, "ue_count_max")) {
                x->ue_count_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_count_max"));
            }
            if (cJSON_HasObjectItem(j, "ue_count_avg")) {
                x->ue_count_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_count_avg"));
            }
            if (cJSON_HasObjectItem(j, "ue_active_count_min")) {
                x->ue_active_count_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_active_count_min"));
            }
            if (cJSON_HasObjectItem(j, "ue_active_count_max")) {
                x->ue_active_count_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_active_count_max"));
            }
            if (cJSON_HasObjectItem(j, "ue_active_count_avg")) {
                x->ue_active_count_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_active_count_avg"));
            }
            if (cJSON_HasObjectItem(j, "ue_inactive_count_min")) {
                x->ue_inactive_count_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_inactive_count_min"));
            }
            if (cJSON_HasObjectItem(j, "ue_inactive_count_max")) {
                x->ue_inactive_count_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_inactive_count_max"));
            }
            if (cJSON_HasObjectItem(j, "ue_inactive_count_avg")) {
                x->ue_inactive_count_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ue_inactive_count_avg"));
            }
            if (cJSON_HasObjectItem(j, "drb_count_min")) {
                x->drb_count_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "drb_count_min"));
            }
            if (cJSON_HasObjectItem(j, "drb_count_max")) {
                x->drb_count_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "drb_count_max"));
            }
            if (cJSON_HasObjectItem(j, "drb_count_avg")) {
                x->drb_count_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "drb_count_avg"));
            }
            if (cJSON_HasObjectItem(j, "dl_gbr_use_min")) {
                x->dl_gbr_use_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_gbr_use_min"));
            }
            if (cJSON_HasObjectItem(j, "dl_gbr_use_max")) {
                x->dl_gbr_use_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_gbr_use_max"));
            }
            if (cJSON_HasObjectItem(j, "dl_gbr_use_avg")) {
                x->dl_gbr_use_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "dl_gbr_use_avg"));
            }
            if (cJSON_HasObjectItem(j, "ul_gbr_use_min")) {
                x->ul_gbr_use_min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_gbr_use_min"));
            }
            if (cJSON_HasObjectItem(j, "ul_gbr_use_max")) {
                x->ul_gbr_use_max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_gbr_use_max"));
            }
            if (cJSON_HasObjectItem(j, "ul_gbr_use_avg")) {
                x->ul_gbr_use_avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ul_gbr_use_avg"));
            }
            if (cJSON_HasObjectItem(j, "counters")) {
                x->counters = cJSON_Getcell_countersValue(cJSON_GetObjectItemCaseSensitive(j, "counters"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createcell(const struct cell * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddNumberToObject(j, "dl_bitrate", x->dl_bitrate);
            cJSON_AddNumberToObject(j, "ul_bitrate", x->ul_bitrate);
            cJSON_AddNumberToObject(j, "dl_tx", x->dl_tx);
            cJSON_AddNumberToObject(j, "ul_tx", x->ul_tx);
            cJSON_AddNumberToObject(j, "dl_err", x->dl_err);
            cJSON_AddNumberToObject(j, "ul_err", x->ul_err);
            cJSON_AddNumberToObject(j, "dl_retx", x->dl_retx);
            cJSON_AddNumberToObject(j, "ul_retx", x->ul_retx);
            cJSON_AddNumberToObject(j, "dl_use_min", x->dl_use_min);
            cJSON_AddNumberToObject(j, "dl_use_max", x->dl_use_max);
            cJSON_AddNumberToObject(j, "dl_use_avg", x->dl_use_avg);
            cJSON_AddNumberToObject(j, "ul_use_min", x->ul_use_min);
            cJSON_AddNumberToObject(j, "ul_use_max", x->ul_use_max);
            cJSON_AddNumberToObject(j, "ul_use_avg", x->ul_use_avg);
            cJSON_AddNumberToObject(j, "dl_sched_users_min", x->dl_sched_users_min);
            cJSON_AddNumberToObject(j, "dl_sched_users_max", x->dl_sched_users_max);
            cJSON_AddNumberToObject(j, "dl_sched_users_avg", x->dl_sched_users_avg);
            cJSON_AddNumberToObject(j, "ul_sched_users_min", x->ul_sched_users_min);
            cJSON_AddNumberToObject(j, "ul_sched_users_max", x->ul_sched_users_max);
            cJSON_AddNumberToObject(j, "ul_sched_users_avg", x->ul_sched_users_avg);
            cJSON_AddNumberToObject(j, "ue_count_min", x->ue_count_min);
            cJSON_AddNumberToObject(j, "ue_count_max", x->ue_count_max);
            cJSON_AddNumberToObject(j, "ue_count_avg", x->ue_count_avg);
            cJSON_AddNumberToObject(j, "ue_active_count_min", x->ue_active_count_min);
            cJSON_AddNumberToObject(j, "ue_active_count_max", x->ue_active_count_max);
            cJSON_AddNumberToObject(j, "ue_active_count_avg", x->ue_active_count_avg);
            cJSON_AddNumberToObject(j, "ue_inactive_count_min", x->ue_inactive_count_min);
            cJSON_AddNumberToObject(j, "ue_inactive_count_max", x->ue_inactive_count_max);
            cJSON_AddNumberToObject(j, "ue_inactive_count_avg", x->ue_inactive_count_avg);
            cJSON_AddNumberToObject(j, "drb_count_min", x->drb_count_min);
            cJSON_AddNumberToObject(j, "drb_count_max", x->drb_count_max);
            cJSON_AddNumberToObject(j, "drb_count_avg", x->drb_count_avg);
            cJSON_AddNumberToObject(j, "dl_gbr_use_min", x->dl_gbr_use_min);
            cJSON_AddNumberToObject(j, "dl_gbr_use_max", x->dl_gbr_use_max);
            cJSON_AddNumberToObject(j, "dl_gbr_use_avg", x->dl_gbr_use_avg);
            cJSON_AddNumberToObject(j, "ul_gbr_use_min", x->ul_gbr_use_min);
            cJSON_AddNumberToObject(j, "ul_gbr_use_max", x->ul_gbr_use_max);
            cJSON_AddNumberToObject(j, "ul_gbr_use_avg", x->ul_gbr_use_avg);
            cJSON_AddItemToObject(j, "counters", cJSON_Createcell_counters(x->counters));
        }
    }
    return j;
}

char * cJSON_Printcell(const struct cell * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createcell(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deletecell(struct cell * x) {
    if (NULL != x) {
        if (NULL != x->counters) {
            cJSON_Deletecell_counters(x->counters);
        }
        cJSON_free(x);
    }
}

struct messages * cJSON_Parsemessages(const char * s) {
    struct messages * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetmessagesValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct messages * cJSON_GetmessagesValue(const cJSON * j) {
    struct messages * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct messages)))) {
            memset(x, 0, sizeof(struct messages));
            if (cJSON_HasObjectItem(j, "ng_setup_request")) {
                x->ng_setup_request = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ng_setup_request"));
            }
            if (cJSON_HasObjectItem(j, "ng_setup_failure")) {
                x->ng_setup_failure = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "ng_setup_failure"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createmessages(const struct messages * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddNumberToObject(j, "ng_setup_request", x->ng_setup_request);
            cJSON_AddNumberToObject(j, "ng_setup_failure", x->ng_setup_failure);
        }
    }
    return j;
}

char * cJSON_Printmessages(const struct messages * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createmessages(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deletemessages(struct messages * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

struct msg_stats_counters * cJSON_Parsemsg_stats_counters(const char * s) {
    struct msg_stats_counters * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_Getmsg_stats_countersValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct msg_stats_counters * cJSON_Getmsg_stats_countersValue(const cJSON * j) {
    struct msg_stats_counters * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct msg_stats_counters)))) {
            memset(x, 0, sizeof(struct msg_stats_counters));
            if (cJSON_HasObjectItem(j, "messages")) {
                x->messages = cJSON_GetmessagesValue(cJSON_GetObjectItemCaseSensitive(j, "messages"));
            }
            if (cJSON_HasObjectItem(j, "errors")) {
                x->errors = cJSON_GeterrorsValue(cJSON_GetObjectItemCaseSensitive(j, "errors"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createmsg_stats_counters(const struct msg_stats_counters * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddItemToObject(j, "messages", cJSON_Createmessages(x->messages));
            cJSON_AddItemToObject(j, "errors", cJSON_Createerrors(x->errors));
        }
    }
    return j;
}

char * cJSON_Printmsg_stats_counters(const struct msg_stats_counters * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createmsg_stats_counters(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deletemsg_stats_counters(struct msg_stats_counters * x) {
    if (NULL != x) {
        if (NULL != x->messages) {
            cJSON_Deletemessages(x->messages);
        }
        if (NULL != x->errors) {
            cJSON_Deleteerrors(x->errors);
        }
        cJSON_free(x);
    }
}

struct cpu * cJSON_Parsecpu(const char * s) {
    struct cpu * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetcpuValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct cpu * cJSON_GetcpuValue(const cJSON * j) {
    struct cpu * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct cpu)))) {
            memset(x, 0, sizeof(struct cpu));
            if (cJSON_HasObjectItem(j, "global")) {
                x->global = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "global"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createcpu(const struct cpu * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddNumberToObject(j, "global", x->global);
        }
    }
    return j;
}

char * cJSON_Printcpu(const struct cpu * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createcpu(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deletecpu(struct cpu * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

struct rxtx_delay * cJSON_Parserxtx_delay(const char * s) {
    struct rxtx_delay * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_Getrxtx_delayValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct rxtx_delay * cJSON_Getrxtx_delayValue(const cJSON * j) {
    struct rxtx_delay * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct rxtx_delay)))) {
            memset(x, 0, sizeof(struct rxtx_delay));
            if (cJSON_HasObjectItem(j, "min")) {
                x->min = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "min"));
            }
            if (cJSON_HasObjectItem(j, "max")) {
                x->max = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "max"));
            }
            if (cJSON_HasObjectItem(j, "avg")) {
                x->avg = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "avg"));
            }
            if (cJSON_HasObjectItem(j, "sd")) {
                x->sd = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "sd"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createrxtx_delay(const struct rxtx_delay * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddNumberToObject(j, "min", x->min);
            cJSON_AddNumberToObject(j, "max", x->max);
            cJSON_AddNumberToObject(j, "avg", x->avg);
            cJSON_AddNumberToObject(j, "sd", x->sd);
        }
    }
    return j;
}

char * cJSON_Printrxtx_delay(const struct rxtx_delay * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createrxtx_delay(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deleterxtx_delay(struct rxtx_delay * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

struct the_0 * cJSON_Parsethe_0(const char * s) {
    struct the_0 * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_Getthe_0Value(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct the_0 * cJSON_Getthe_0Value(const cJSON * j) {
    struct the_0 * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct the_0)))) {
            memset(x, 0, sizeof(struct the_0));
            if (cJSON_HasObjectItem(j, "rxtx_delay")) {
                x->rxtx_delay = cJSON_Getrxtx_delayValue(cJSON_GetObjectItemCaseSensitive(j, "rxtx_delay"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createthe_0(const struct the_0 * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddItemToObject(j, "rxtx_delay", cJSON_Createrxtx_delay(x->rxtx_delay));
        }
    }
    return j;
}

char * cJSON_Printthe_0(const struct the_0 * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createthe_0(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deletethe_0(struct the_0 * x) {
    if (NULL != x) {
        if (NULL != x->rxtx_delay) {
            cJSON_Deleterxtx_delay(x->rxtx_delay);
        }
        cJSON_free(x);
    }
}

struct rf_ports * cJSON_Parserf_ports(const char * s) {
    struct rf_ports * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_Getrf_portsValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct rf_ports * cJSON_Getrf_portsValue(const cJSON * j) {
    struct rf_ports * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct rf_ports)))) {
            memset(x, 0, sizeof(struct rf_ports));
            if (cJSON_HasObjectItem(j, "0")) {
                x->the_0 = cJSON_Getthe_0Value(cJSON_GetObjectItemCaseSensitive(j, "0"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createrf_ports(const struct rf_ports * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddItemToObject(j, "0", cJSON_Createthe_0(x->the_0));
        }
    }
    return j;
}

char * cJSON_Printrf_ports(const struct rf_ports * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createrf_ports(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deleterf_ports(struct rf_ports * x) {
    if (NULL != x) {
        if (NULL != x->the_0) {
            cJSON_Deletethe_0(x->the_0);
        }
        cJSON_free(x);
    }
}

struct msg_stats * cJSON_Parsemsg_stats(const char * s) {
    struct msg_stats * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_Getmsg_statsValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

struct msg_stats * cJSON_Getmsg_statsValue(const cJSON * j) {
    struct msg_stats * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct msg_stats)))) {
            memset(x, 0, sizeof(struct msg_stats));
            if (cJSON_HasObjectItem(j, "message")) {
                x->message = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "message")));
            }
            else {
                if (NULL != (x->message = cJSON_malloc(sizeof(char)))) {
                    x->message[0] = '\0';
                }
            }
            if (cJSON_HasObjectItem(j, "message_id")) {
                x->message_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "message_id"));
            }
            if (cJSON_HasObjectItem(j, "instance_id")) {
                x->instance_id = strdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "instance_id")));
            }
            else {
                if (NULL != (x->instance_id = cJSON_malloc(sizeof(char)))) {
                    x->instance_id[0] = '\0';
                }
            }
            if (cJSON_HasObjectItem(j, "cpu")) {
                x->cpu = cJSON_GetcpuValue(cJSON_GetObjectItemCaseSensitive(j, "cpu"));
            }
            if (cJSON_HasObjectItem(j, "gtp_rx_bitrate")) {
                x->gtp_rx_bitrate = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "gtp_rx_bitrate"));
            }
            if (cJSON_HasObjectItem(j, "gtp_tx_bitrate")) {
                x->gtp_tx_bitrate = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "gtp_tx_bitrate"));
            }
            if (cJSON_HasObjectItem(j, "cells")) {
                hashtable_t * x1 = hashtable_create(64, false);
                if (NULL != x1) {
                    cJSON * e1 = NULL;
                    cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "cells");
                    cJSON_ArrayForEach(e1, j1) {
                        hashtable_add(x1, e1->string, cJSON_GetcellValue(e1), sizeof(struct cell *));
                    }
                    x->cells = x1;
                }
            }
            else {
                x->cells = hashtable_create(64, false);
            }
            if (cJSON_HasObjectItem(j, "rf_ports")) {
                x->rf_ports = cJSON_Getrf_portsValue(cJSON_GetObjectItemCaseSensitive(j, "rf_ports"));
            }
            if (cJSON_HasObjectItem(j, "counters")) {
                x->counters = cJSON_Getmsg_stats_countersValue(cJSON_GetObjectItemCaseSensitive(j, "counters"));
            }
            if (cJSON_HasObjectItem(j, "duration")) {
                x->duration = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "duration"));
            }
            if (cJSON_HasObjectItem(j, "time")) {
                x->time = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "time"));
            }
            if (cJSON_HasObjectItem(j, "utc")) {
                x->utc = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "utc"));
            }
        }
    }
    return x;
}

cJSON * cJSON_Createmsg_stats(const struct msg_stats * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->message) {
                cJSON_AddStringToObject(j, "message", x->message);
            }
            else {
                cJSON_AddStringToObject(j, "message", "");
            }
            cJSON_AddNumberToObject(j, "message_id", x->message_id);
            if (NULL != x->instance_id) {
                cJSON_AddStringToObject(j, "instance_id", x->instance_id);
            }
            else {
                cJSON_AddStringToObject(j, "instance_id", "");
            }
            cJSON_AddItemToObject(j, "cpu", cJSON_Createcpu(x->cpu));
            cJSON_AddNumberToObject(j, "gtp_rx_bitrate", x->gtp_rx_bitrate);
            cJSON_AddNumberToObject(j, "gtp_tx_bitrate", x->gtp_tx_bitrate);
            if (NULL != x->cells) {
                cJSON * j1 = cJSON_CreateObject();
                if (NULL != j1) {
                    char **keys1 = NULL;
                    size_t count1 = hashtable_get_keys(x->cells, &keys1);
                    if (NULL != keys1) {
                        for (size_t index1 = 0; index1 < count1; index1++) {
                            struct cell *x1 = hashtable_lookup(x->cells, keys1[index1]);
                            cJSON_AddItemToObject(j1, keys1[index1], cJSON_Createcell(x1));
                        }
                        cJSON_free(keys1);
                    }
                    cJSON_AddItemToObject(j, "cells", j1);
                }
            }
            cJSON_AddItemToObject(j, "rf_ports", cJSON_Createrf_ports(x->rf_ports));
            cJSON_AddItemToObject(j, "counters", cJSON_Createmsg_stats_counters(x->counters));
            cJSON_AddNumberToObject(j, "duration", x->duration);
            cJSON_AddNumberToObject(j, "time", x->time);
            cJSON_AddNumberToObject(j, "utc", x->utc);
        }
    }
    return j;
}

char * cJSON_Printmsg_stats(const struct msg_stats * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_Createmsg_stats(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

void cJSON_Deletemsg_stats(struct msg_stats * x) {
    if (NULL != x) {
        if (NULL != x->message) {
            cJSON_free(x->message);
        }
        if (NULL != x->instance_id) {
            cJSON_free(x->instance_id);
        }
        if (NULL != x->cpu) {
            cJSON_Deletecpu(x->cpu);
        }
        if (NULL != x->cells) {
            char **keys1 = NULL;
            size_t count1 = hashtable_get_keys(x->cells, &keys1);
            if (NULL != keys1) {
                for (size_t index1 = 0; index1 < count1; index1++) {
                    struct cell *x1 = hashtable_lookup(x->cells, keys1[index1]);
                    if (NULL != x1) {
                        cJSON_Deletecell(x1);
                    }
                }
                cJSON_free(keys1);
            }
            hashtable_release(x->cells);
        }
        if (NULL != x->rf_ports) {
            cJSON_Deleterf_ports(x->rf_ports);
        }
        if (NULL != x->counters) {
            cJSON_Deletemsg_stats_counters(x->counters);
        }
        cJSON_free(x);
    }
}









#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */


