noPoll websocket implementation , WebSocket implementation, RFC 6455 implementation, (Servidores Linux http://www.aspl.es)
nopoll_msg_get_payload
nopoll_msg_get_payload_size
nopoll_msg_is_final
nopoll_msg_is_fragment
nopoll_msg_join
nopoll_msg_opcode
nopoll_msg_ref
nopoll_msg_ref_count
nopoll_msg_unref
nopoll_msg_unref()
void nopoll_msg_unref (noPollMsg * msg)
Allows to release the reference acquired, finished the object if all references are terminated.
Parameters
msg The websocket message to be finished.
References nopoll_free(), nopoll_mutex_destroy(), nopoll_mutex_lock(), and nopoll_mutex_unlock().
Referenced by nopoll_conn_read().