#ifndef WEBSOCKET_ORIGINATED_MSG_H
#define WEBSOCKET_ORIGINATED_MSG_H 

typedef enum{
  READY_MSG_ORIGINATED_MSG_E,
  KPM_ORIGINATED_MSG_E,
  RC_ORIGINATED_MSG_E,
  CCC_ORIGINATED_MSG_E,

  END_ORIGINATED_MSG_E

} ws_orig_msg_e ;

#endif

